../obj/$(PLAT)/qbrdg.$(OXT): blksvd/qbrdg.F90 blksvd/gbrdg.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/qbrdg.F90

../obj/$(PLAT)/ybrdg.$(OXT): blksvd/ybrdg.F90 blksvd/gbrdg.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/ybrdg.F90

../obj/$(PLAT)/xbrdg.$(OXT): blksvd/xbrdg.F90 blksvd/gbrdg.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/xbrdg.F90

../obj/$(PLAT)/wbrdg.$(OXT): blksvd/wbrdg.F90 blksvd/gbrdg.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/wbrdg.F90

../obj/$(PLAT)/qksvd0.$(OXT): blksvd/qksvd0.F90 blksvd/gksvd0.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/qksvd0.F90

../obj/$(PLAT)/yksvd0.$(OXT): blksvd/yksvd0.F90 blksvd/hksvd0.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/yksvd0.F90

../obj/$(PLAT)/xksvd0.$(OXT): blksvd/xksvd0.F90 blksvd/gksvd0.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/xksvd0.F90

../obj/$(PLAT)/wksvd0.$(OXT): blksvd/wksvd0.F90 blksvd/hksvd0.F90 $(MKFS) blksvd/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/blksvd/wksvd0.F90
