!>@brief \b WKSVD0 computes the SVD of G as U S V^H, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE WKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
  USE, INTRINSIC :: ISO_C_BINDING
#ifdef NDEBUG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, OUTPUT_UNIT
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE

#define CR_HYPOT HYPOT
  INTERFACE
     SUBROUTINE WLANGO(N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=c_long_double), INTENT(IN) :: G(N,LDG)
       REAL(KIND=c_long_double), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE WSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       COMPLEX(KIND=c_long_double), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE WMK3PQ(K, N, G, LDG, W, O, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: K, N, LDG
       COMPLEX(KIND=c_long_double), INTENT(IN) :: G(LDG,N)
       REAL(KIND=c_long_double), INTENT(OUT) :: W(N*N)
       INTEGER, INTENT(OUT) :: O(2*N*(N-1))
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WMK3PQ
  END INTERFACE
  INTERFACE
     SUBROUTINE WKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       COMPLEX(KIND=c_long_double), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=c_long_double), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=c_long_double), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE WKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE WCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       COMPLEX(KIND=c_long_double), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=c_long_double), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE WCVGPP
  END INTERFACE
  INTERFACE
     SUBROUTINE WROTC(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=c_long_double), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=c_long_double), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WROTC
  END INTERFACE
  INTERFACE
     SUBROUTINE WROTR(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=c_long_double), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=c_long_double), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE

  INTEGER, PARAMETER :: K = c_long_double, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  COMPLEX(KIND=K), PARAMETER :: CZERO = (ZERO,ZERO), CONE = (ONE,ZERO)
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
#ifdef ANIMATE
  REAL(KIND=K), INTENT(INOUT), TARGET :: SV(N)
#else
  REAL(KIND=K), INTENT(OUT) :: SV(N)
#endif
  REAL(KIND=K), INTENT(OUT) :: W(*)
  INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
  INTEGER, INTENT(OUT) :: R(2,*)

  COMPLEX(KIND=K) :: G2(2,2), U2(2,2), V2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TT, TM, SM
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP, ES(3)
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  INTEGER(KIND=c_size_t) :: LDF
  INTEGER(KIND=c_int), EXTERNAL :: PVN_CVIS_FRAME_L
#define PVN_CVIS_FRAME PVN_CVIS_FRAME_L
#endif

#define LANGO WLANGO
#define SCALG WSCALG
#define MK3PQ WMK3PQ
#define KSVD2 WKSVD2
#define CVGPP WCVGPP
#define ROTC WROTC
#define ROTR WROTR
#include "hksvd0.F90"
#ifndef NDEBUG
9 FORMAT(A,ES30.21E4)
#endif
END SUBROUTINE WKSVD0
