../obj/$(PLAT)/xksvd2.$(OXT): ksvd2/xksvd2.F90 ksvd2/gksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xksvd2.F90

../obj/$(PLAT)/wksvd2.$(OXT): ksvd2/wksvd2.F90 ksvd2/hksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/wksvd2.F90

../obj/$(PLAT)/xcvgpp.$(OXT): ksvd2/xcvgpp.F90 ksvd2/gcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xcvgpp.F90

../obj/$(PLAT)/wcvgpp.$(OXT): ksvd2/wcvgpp.F90 ksvd2/hcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/wcvgpp.F90

../obj/$(PLAT)/xlmsv2.$(OXT): ksvd2/xlmsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xlmsv2.F90

../obj/$(PLAT)/xlwsv2.$(OXT): ksvd2/xlwsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xlwsv2.F90

../obj/$(PLAT)/xkerr2.$(OXT): ksvd2/xkerr2.F90 ksvd2/gkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xkerr2.F90

../obj/$(PLAT)/wkerr2.$(OXT): ksvd2/wkerr2.F90 ksvd2/hkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/wkerr2.F90
