!>@brief \b CKSVD2X tests the CKSVD2 routine.
PROGRAM CKSVD2X
  IMPLICIT NONE
  EXTERNAL :: CKSVD2
  CALL CTEST(CKSVD2)
CONTAINS
  !>@brief \b CTEST calls KSVD2.
  !!
  !!@param KSVD2 is CKSVD2.
  SUBROUTINE CTEST(KSVD2)
#ifdef __NVCOMPILER
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
#else
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64, REAL128
#endif
    IMPLICIT NONE
#ifdef __NVCOMPILER
#ifdef CR_MATH
    INTERFACE
       ! TODO: cr_hypot might change errno but a copy can be made that does not
       PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
         USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
         REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
         REAL(KIND=c_double) :: CR_HYPOT
       END FUNCTION CR_HYPOT
    END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
    INTEGER, PARAMETER :: KX = REAL64
#else
#define CR_HYPOT HYPOT
    INTEGER, PARAMETER :: KX = REAL128
#endif
    INTEGER, PARAMETER :: IERR = -HUGE(0), CLAL = 132
    EXTERNAL :: KSVD2
    CHARACTER(LEN=CLAL) :: CLA
    COMPLEX(KIND=REAL32) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=REAL32) :: S(2)
    INTEGER :: INFO
    LOGICAL :: ONCE
    COMPLEX(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2)
    REAL(KIND=KX) :: SX(2,2)
#include "uksvd2.F90"
1   FORMAT(A,ES16.9E2)
2   FORMAT(A,'(',ES16.9E2,',',ES16.9E2,')')
3   FORMAT(A,I4)
  END SUBROUTINE CTEST
END PROGRAM CKSVD2X
