!>@brief \b CKSVD2X tests the CKSVD2 routine.
PROGRAM CKSVD2X
  IMPLICIT NONE
  CALL CTEST
CONTAINS
  !>@brief \b CTEST calls CKSVD2.
  SUBROUTINE CTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL32, REAL128
    IMPLICIT NONE
    INTERFACE
       SUBROUTINE CKSVD2(G, U, V, S, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
         IMPLICIT NONE
         COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2)
         COMPLEX(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2)
         REAL(KIND=REAL32), INTENT(OUT) :: S(2)
         INTEGER, INTENT(INOUT) :: INFO(3)
       END SUBROUTINE CKSVD2
    END INTERFACE
    INTERFACE
       SUBROUTINE CKERR2(G, U, V, S, E, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
         IMPLICIT NONE
         COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
         REAL(KIND=REAL32), INTENT(IN) :: S(2)
         REAL(KIND=REAL128), INTENT(OUT) :: E(3)
         INTEGER, INTENT(IN) :: INFO(3)
       END SUBROUTINE CKERR2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0)-1, CLAL = 132
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=KX) :: E(3)
    COMPLEX(KIND=REAL32) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=REAL32) :: S(2)
    INTEGER :: I, J, INFO(3)
    LOGICAL :: ONCE
#define KSVD2 CKSVD2
#define KERR2 CKERR2
#include "uksvd2.F90"
1   FORMAT(A,ES16.9E2)
2   FORMAT(A,'(',ES16.9E2,',',ES16.9E2,')')
3   FORMAT(A,I4)
  END SUBROUTINE CTEST
END PROGRAM CKSVD2X
