!>@brief \b CKSVD0X tests the CKSVD0 routine.
PROGRAM CKSVD0X
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE CBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       COMPLEX(KIND=REAL32), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE CRDINP(BN, M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: BN
       INTEGER, INTENT(IN) :: M, N, LDG
       COMPLEX(KIND=REAL32), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE CRDINP
  END INTERFACE
  INTERFACE
     SUBROUTINE JSWEEP(J, N, S, P, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N
       INTEGER, INTENT(OUT) :: S, P, O(2,*), INFO
     END SUBROUTINE JSWEEP
  END INTERFACE
  INTERFACE
     SUBROUTINE CKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL128), INTENT(OUT), TARGET :: SV(N)
       REAL(KIND=REAL32), INTENT(INOUT) :: W(MAX(N,5)*N)
       INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
     END SUBROUTINE CKSVD0
  END INTERFACE
  INTERFACE
     SUBROUTINE CWROUT(BN, J, N, U, LDU, V, LDV, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: BN
       INTEGER, INTENT(IN) :: J, N, LDU, LDV
       COMPLEX(KIND=REAL32), INTENT(IN) :: U(LDU,N), V(LDV,N)
       REAL(KIND=REAL128), INTENT(IN) :: S(N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE CWROUT
  END INTERFACE

#ifdef ANIMATE
  INTERFACE
     FUNCTION PVN_CVIS_START(mA, nA, act, rname, iname) BIND(C,name='pvn_cvis_start_f_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_ptr, c_char
       IMPLICIT NONE
       INTEGER(KIND=c_int), INTENT(IN), TARGET :: mA, nA, act
       CHARACTER(KIND=c_char), INTENT(IN), TARGET :: rname(*), iname(*)
       TYPE(c_ptr) :: PVN_CVIS_START
     END FUNCTION PVN_CVIS_START
  END INTERFACE
  INTERFACE
     FUNCTION PVN_CVIS_STOP(ctx, sx, sy, rbpp, rcmap, ibpp, icmap) BIND(C,name='pvn_cvis_stop_f_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_ptr, c_char
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), TARGET :: ctx
       INTEGER(KIND=c_int), INTENT(IN), TARGET :: sx, sy, rbpp, ibpp
       CHARACTER(KIND=c_char), INTENT(IN), TARGET :: rcmap(*), icmap(*)
       INTEGER(KIND=c_int) :: PVN_CVIS_STOP
     END FUNCTION PVN_CVIS_STOP
  END INTERFACE
#endif

  INTEGER, PARAMETER :: K = REAL32, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER, TARGET :: JOB, M
  INTEGER :: N, LDG, LDU, LDV, INFO, I, J, L, S, P
  COMPLEX(KIND=K), ALLOCATABLE, TARGET :: G(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: G
  COMPLEX(KIND=K), ALLOCATABLE :: U(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: U
  COMPLEX(KIND=K), ALLOCATABLE :: V(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: V
  REAL(KIND=K), ALLOCATABLE :: W(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: W
  REAL(KIND=REAL128), ALLOCATABLE, TARGET :: SV(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: SV
  INTEGER, ALLOCATABLE :: O(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: O
#ifdef ANIMATE
  CHARACTER(LEN=CLAL) :: CN
  TYPE(c_ptr), TARGET :: CTX
  TYPE(c_ptr), POINTER :: CP
#endif

#define BRDG CBRDG
#define RDINP CRDINP
#define WROUT CWROUT
#define KSVD0 CKSVD0
#include "hksvd0x.F90"
9 FORMAT(3(ES16.9E2,A))
END PROGRAM CKSVD0X
