!>@brief \b CMKBPQX tests the CMKBPQ routine.
PROGRAM CMKBPQX
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  IMPLICIT NONE
#ifndef __GFORTRAN__
  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE BFOPEN(FN, ACT, U, INFO)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: FN
       CHARACTER(LEN=2), INTENT(IN) :: ACT
       INTEGER, INTENT(OUT) :: U, INFO
     END SUBROUTINE BFOPEN
  END INTERFACE
  INTERFACE
     SUBROUTINE SBRD2(U, M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U, M, N, LDG
       COMPLEX(KIND=REAL32), INTENT(OUT) :: G(LDG,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE SBRD2
  END INTERFACE
  INTERFACE
     SUBROUTINE SBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       COMPLEX(KIND=REAL32), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE CMKBPQ(N, G, LDG, B, W, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG, B
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: W(N/B,N/B)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: O(2,*), INFO
     END SUBROUTINE CMKBPQ
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DDEC(E, P, Q) BIND(C,NAME='pvn_djs_ddec_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       REAL(KIND=REAL64), INTENT(IN) :: E
       INTEGER, INTENT(OUT) :: P, Q
     END SUBROUTINE DDEC
  END INTERFACE
#endif
  INTEGER, PARAMETER :: K = REAL32, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER :: B, I, J, L, M, N, LDG, INFO
  COMPLEX(KIND=K), ALLOCATABLE :: G(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: G
  REAL(KIND=K), ALLOCATABLE :: W(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: W
  REAL(KIND=REAL64), ALLOCATABLE :: D(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: D
  INTEGER, ALLOCATABLE :: O(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: O
#ifdef __GFORTRAN__
  EXTERNAL :: NB2M, BFOPEN, CBRD2, CBRDG, CMKBPQ, PVN_DJS_DDEC
#define XDEC PVN_DJS_DDEC
#else
#define XDEC DDEC
#endif
#define BRD2 CBRD2
#define BRDG CBRDG
#define MKBPQ CMKBPQ
#include "gmkbpqx.F90"
9 FORMAT(ES16.9E2)
END PROGRAM CMKBPQX
