!>@brief CRAN generates a set of pseudorandom single precision complex 2x2 matrices.
PROGRAM CRAN
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     FUNCTION SRSAFE(U)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=REAL32) :: SRSAFE
     END FUNCTION SRSAFE
  END INTERFACE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N, U
  LOGICAL :: UPPER
#define RSAFE SRSAFE
#include "hran.F90"
1 FORMAT(A,ES16.9E2)
END PROGRAM CRAN
