!>@brief CRND2T tests a set of pseudorandom single precision complex 2x2 matrices.
PROGRAM CRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128, OUTPUT_UNIT, ERROR_UNIT
  USE, INTRINSIC :: ISO_C_BINDING
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE CKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE CKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CKSVD2
  END INTERFACE
#define KSVD2 CKSVD2
  INTERFACE
     PURE SUBROUTINE CKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(IN) :: S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CKERR2
  END INTERFACE
#define KERR2 CKERR2
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE YKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE YKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       COMPLEX(KIND=REAL128), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE YKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
  INTEGER, PARAMETER :: D = REAL32
  INTEGER, ALLOCATABLE :: ISEED(:)
  COMPLEX(KIND=REAL32), TARGET :: G(2,2)
  COMPLEX(KIND=REAL32) :: U(2,2), V(2,2)
  REAL(KIND=REAL32) :: S(2), T
  COMPLEX(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2)
  REAL(KIND=REAL128) :: QS(2), E(5), F(2,6), Q
  REAL(KIND=REAL32), POINTER, CONTIGUOUS :: P(:,:)
  INTEGER :: SSIZE, I, J, K, L, M, N, INFO
  CHARACTER(LEN=64) :: CLA
#include "hrnd2t.F90"
1 FORMAT(A,ES16.9E2)
END PROGRAM CRND2T
