!>@brief \b DKALT2X tests the DKALT2 routine.
PROGRAM DKALT2X
  IMPLICIT NONE
  CALL DTEST
CONTAINS
  !>@brief \b DTEST calls DKALT2.
  SUBROUTINE DTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL64, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
#ifdef NDEBUG
       PURE SUBROUTINE DKALT2(G, U, V, S, INFO)
#else
       SUBROUTINE DKALT2(G, U, V, S, INFO)
#endif
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
         IMPLICIT NONE
         REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
         REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE DKALT2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL64) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 DKALT2
#include "tksvd2.F90"
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,I5)
  END SUBROUTINE DTEST
END PROGRAM DKALT2X
