!>@brief \b DKSVD0X tests the DKSVD0 routine.
PROGRAM DKSVD0X
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE DBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE JSWEEP(J, N, S, P, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N
       INTEGER, INTENT(OUT) :: S, P, O(2,*), INFO
     END SUBROUTINE JSWEEP
  END INTERFACE
  INTERFACE
     SUBROUTINE DKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
#ifdef ANIMATE
       REAL(KIND=REAL128), INTENT(INOUT), TARGET :: SV(N)
#else
       REAL(KIND=REAL128), INTENT(OUT) :: SV(N)
#endif
       REAL(KIND=REAL64), INTENT(INOUT) :: W(MAX(N,3)*N)
       INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
       INTEGER, INTENT(OUT) :: R(2,*)
     END SUBROUTINE DKSVD0
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL64, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER :: JOB, M, N, LDG, LDU, LDV, INFO, I, J, L, S, P
  REAL(KIND=K), ALLOCATABLE :: G(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: G
  REAL(KIND=K), ALLOCATABLE :: U(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: U
  REAL(KIND=K), ALLOCATABLE :: V(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: V
  REAL(KIND=K), ALLOCATABLE :: W(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: W
#ifdef ANIMATE
  REAL(KIND=REAL128), ALLOCATABLE, TARGET :: SV(:)
#else
  REAL(KIND=REAL128), ALLOCATABLE :: SV(:)
#endif
  !DIR$ ATTRIBUTES ALIGN: 64:: SV
  INTEGER, ALLOCATABLE :: O(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: O
  INTEGER, ALLOCATABLE :: R(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: R
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  TYPE(c_ptr), EXTERNAL :: PVN_RVIS_START
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RVIS_STOP
#endif

#define BRDG DBRDG
#define RDINP DRDINP
#define WROUT DWROUT
#define KSVD0 DKSVD0
#include "gksvd0x.F90"
9 FORMAT(3(ES25.17E3,A))
CONTAINS
#include "drdinp.F90"
#include "dwrout.F90"
END PROGRAM DKSVD0X
