!>@brief \b DLWSV2X tests the DLWSV2 routine.
PROGRAM DLWSV2X
  IMPLICIT NONE
  EXTERNAL :: DLWSV2
  CALL DLTEST(DLWSV2)
CONTAINS
  !>@brief \b DLTEST calls LSVD2.
  !!
  !!@param LSVD2 is DLWSV2.
  SUBROUTINE DLTEST(LSVD2)
#ifdef __NVCOMPILER
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#else
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
#endif
    IMPLICIT NONE
#ifdef __NVCOMPILER
#ifdef CR_MATH
    INTERFACE
       ! TODO: cr_hypot might change errno but a copy can be made that does not
       PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
         USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
         REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
         REAL(KIND=c_double) :: CR_HYPOT
       END FUNCTION CR_HYPOT
    END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
    INTEGER, PARAMETER :: KX = REAL64
#else
#define CR_HYPOT HYPOT
    INTEGER, PARAMETER :: KX = REAL128
#endif
    INTEGER, PARAMETER :: IERR = -HUGE(0), CLAL = 64
    EXTERNAL :: LSVD2
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL64) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    G(2,1) = 0.0_REAL64
#include "tlasv2.F90"
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,I5)
  END SUBROUTINE DLTEST
END PROGRAM DLWSV2X
