!>@brief \b DLWSV2X tests the DLWSV2 routine.
PROGRAM DLWSV2X
  IMPLICIT NONE
  CALL DLTEST
CONTAINS
  !>@brief \b DLTEST calls DLWSV2.
  SUBROUTINE DLTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL64, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
       PURE SUBROUTINE DLWSV2(G, U, V, S, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
         IMPLICIT NONE
         REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
         REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(OUT) :: INFO
       END SUBROUTINE DLWSV2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL64) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    G(2,1) = 0.0_REAL64
#define LSVD2 DLWSV2
#include "tlasv2.F90"
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,I5)
  END SUBROUTINE DLTEST
END PROGRAM DLWSV2X
