!>@brief \b DMKBPQX tests the DMKBPQ routine.
PROGRAM DMKBPQX
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE BFOPEN(FN, ACT, U, INFO)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: FN
       CHARACTER(LEN=2), INTENT(IN) :: ACT
       INTEGER, INTENT(OUT) :: U, INFO
     END SUBROUTINE BFOPEN
  END INTERFACE
  INTERFACE
     SUBROUTINE DBRD2(U, M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U, M, N, LDG
       REAL(KIND=REAL64), INTENT(OUT) :: G(LDG,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DBRD2
  END INTERFACE
  INTERFACE
     SUBROUTINE DBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE DMKBPQ(M, G, LDG, B, W, D, O, OD, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, LDG, B, O(2,*)
       REAL(KIND=REAL64), INTENT(IN) :: G(LDG,M)
       REAL(KIND=REAL64), INTENT(OUT) :: W(M/B,M/B)
       REAL(KIND=REAL128), INTENT(OUT) :: D(*)
       INTEGER, INTENT(OUT) :: OD(2,*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DMKBPQ
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE PVN_DJS_QDEC(E, P, Q)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: E
       INTEGER, INTENT(OUT) :: P, Q
     END SUBROUTINE PVN_DJS_QDEC
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL64, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER :: B, I, J, L, M, N, LDG, INFO
  REAL(KIND=K), ALLOCATABLE :: G(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: G
  REAL(KIND=K), ALLOCATABLE :: W(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: W
  REAL(KIND=REAL128), ALLOCATABLE :: D(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: D
  INTEGER, ALLOCATABLE :: O(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: O
#define BRD2 DBRD2
#define BRDG DBRDG
#define MKBPQ DMKBPQ
#define XDEC PVN_DJS_QDEC
#include "gmkbpqx.F90"
9 FORMAT(ES25.17E3)
END PROGRAM DMKBPQX
