!>@brief DRAN2T tests a set of pseudorandom double precision real 2x2 matrices.
PROGRAM DRAN2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128, OUTPUT_UNIT, ERROR_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE DKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DKSVD2
  END INTERFACE
#define KSVD2 DKSVD2
#ifdef UPPER
  INTERFACE
     PURE SUBROUTINE DLWSV2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DLWSV2
  END INTERFACE
#define LWSV2 DLWSV2
#endif
  INTERFACE
     PURE SUBROUTINE DKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DKERR2
  END INTERFACE
#define KERR2 DKERR2
  INTERFACE
     SUBROUTINE QKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE QKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTERFACE
     FUNCTION DRSAFE(U)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=REAL64) :: DRSAFE
     END FUNCTION DRSAFE
  END INTERFACE
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
#ifdef UPPER
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
#endif
  REAL(KIND=REAL64) :: G(2,2), U(2,2), V(2,2), S(2), T
  REAL(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2), QS(2)
#ifdef UPPER
  REAL(KIND=REAL128) :: E(5,2), F(2,16), Q
#else
  REAL(KIND=REAL128) :: E(5,1), F(2,6), Q
#endif
  INTEGER :: I, J, K, L, M, N, INFO
  CHARACTER(LEN=64) :: CLA
#define RSAFE DRSAFE
#include "gran2t.F90"
1 FORMAT(A,ES25.17E3)
END PROGRAM DRAN2T
