!>@brief DRAN generates a set of pseudorandom double precision real 2x2 matrices.
PROGRAM DRAN
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     FUNCTION ORFILE()
       IMPLICIT NONE
       INTEGER :: ORFILE
     END FUNCTION ORFILE
  END INTERFACE
  INTERFACE
     FUNCTION DRSAFE(U)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=REAL64) :: DRSAFE
     END FUNCTION DRSAFE
  END INTERFACE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N, U
  LOGICAL :: UPPER
#define RSAFE DRSAFE
#include "gran.F90"
1 FORMAT(A,ES25.17E3)
END PROGRAM DRAN
