!>@brief DRND2T tests a set of pseudorandom double precision real 2x2 matrices.
PROGRAM DRND2T
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_long
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128, OUTPUT_UNIT, ERROR_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE DKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE DKSVD2
  END INTERFACE
#ifdef UPPER
  INTERFACE
     SUBROUTINE DLWSV2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DLWSV2
  END INTERFACE
#endif
  INTERFACE
     SUBROUTINE DKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(IN) :: INFO(3)
     END SUBROUTINE DKERR2
  END INTERFACE
  INTERFACE
     SUBROUTINE QKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE QKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE

  INTEGER, PARAMETER :: D = REAL64
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
#ifdef UPPER
  REAL(KIND=D), PARAMETER :: ZERO = 0.0_D
#endif
  REAL(KIND=D) :: G(2,2), U(2,2), V(2,2), S(2)
  REAL(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2), QS(2), Q, Q9
#ifdef UPPER
  REAL(KIND=REAL128) :: E(5,2), F(2,18)
  INTEGER(KIND=c_long_long) :: NS(2)
#else
  REAL(KIND=D) :: T
  REAL(KIND=REAL128) :: E(5,1), F(2,8)
  INTEGER(KIND=c_long_long) :: NS(1)
#endif
  INTEGER :: SSIZE, I, J, K, L, M, N, P, INFO(3)
  CHARACTER(LEN=64) :: CLA
  INTEGER, ALLOCATABLE :: ISEED(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: ISEED
  INTEGER(KIND=c_long_long), ALLOCATABLE :: NSTIME(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: NSTIME
  INTEGER(KIND=c_long_long), EXTERNAL :: PVN_TIME_MONO_NS, PVN_TIME_MONO_RES
#define KSVD2 DKSVD2
#define KERR2 DKERR2
#ifdef UPPER
#define LWSV2 DLWSV2
#endif
#include "grnd2t.F90"
1 FORMAT(A,ES26.17E4)
END PROGRAM DRND2T
