     ! for each matrix, harvest an additional random number to determine the signs of the elements
     CALL RANDOM_NUMBER(T)
     M = EXPONENT(T)
     IF (IAND(M, 1) .NE. 0) G(1,1) = -G(1,1)
     IF (IAND(M, 2) .NE. 0) G(2,1) = -G(2,1)
     IF (IAND(M, 4) .NE. 0) G(1,2) = -G(1,2)
     IF (IAND(M, 8) .NE. 0) G(2,2) = -G(2,2)
     INFO = 0
     QG(1,1) = G(1,1)
     QG(2,1) = G(2,1)
     QG(1,2) = G(1,2)
     QG(2,2) = G(2,2)
     CALL QKSVD2(QG, QU, QV, QS, INFO)
     IF (INFO(1) .LT. -HUGE(0)) CALL STHALT('QKSVD2')
     QS(1) = SCALE(QS(1), INFO(2) - INFO(1))
     QS(2) = SCALE(QS(2), INFO(3) - INFO(1))
     Q = QS(1) / QS(2)
     IF (Q .NE. Q) THEN
        Q = QZERO
        Q = QONE / Q
     END IF
     ! \kappa_2(G)
     F(1,1) = MAX(Q, F(1,1))
     F(2,1) = MAX(-Q, F(2,1))
     NS(1) = PVN_TIME_MONO_TICKS()
     INFO = 0
     CALL KSVD2(G, U, V, S, INFO)
     NS(1) = PVN_TIME_MONO_TICKS() - NS(1)
     IF (INFO(1) .LT. -HUGE(0)) CALL STHALT('KSVD2')
     NSTIME(1,P) = NSTIME(1,P) + NS(1)
     CALL KERR2(G, U, V, S, E(1,1), INFO)
     Q = S(1)
     Q = SCALE(Q, INFO(2) - INFO(1))
     E(4,1) = MAX(ABS(QS(1) - Q) / QS(1), QZERO)
     Q = S(2)
     Q = SCALE(Q, INFO(3) - INFO(1))
     E(5,1) = MAX(ABS(QS(2) - Q) / QS(2), QZERO)
     F(1,2) = MAX(E(1,1), F(1,2))
     F(2,2) = MAX(-E(1,1), F(2,2))
     F(1,3) = MAX(E(2,1), F(1,3))
     F(2,3) = MAX(-E(2,1), F(2,3))
     F(1,4) = MAX(E(3,1), F(1,4))
     F(2,4) = MAX(-E(3,1), F(2,4))
     F(1,5) = MAX(E(4,1), F(1,5))
     F(2,5) = MAX(-E(4,1), F(2,5))
     F(1,6) = MAX(E(5,1), F(1,6))
     F(2,6) = MAX(-E(5,1), F(2,6))
     F(1,7) = MAX((NS(1) / Q9), F(1,7))
     F(2,7) = MAX(QZERO, F(2,7))
