!>@brief \b IBDIMSX tests the IBDIMS routine.
PROGRAM IBDIMSX
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE IBDIMS(N, B, M, M_B, NW, ND, NO, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, M_B, NW, ND, NO
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE IBDIMS
  END INTERFACE

  INTEGER, PARAMETER :: CLAL = 256
  CHARACTER(LEN=CLAL) :: CLA
  INTEGER :: N, LDG, B, LDB, M, M_B, NW, ND, NO, INFO

  INFO = COMMAND_ARGUMENT_COUNT()
  IF (INFO .NE. 3) THEN
     CALL GET_COMMAND_ARGUMENT(0, CLA)
     WRITE (ERROR_UNIT,*) TRIM(CLA), ' N B S'
     ERROR STOP 'INVALID COMMAND LINE'
  END IF
  CALL GET_COMMAND_ARGUMENT(1, CLA, M_B, INFO)
  IF (INFO .NE. 0) ERROR STOP 'N'
  READ (CLA,*) N
  CALL GET_COMMAND_ARGUMENT(2, CLA, M_B, INFO)
  IF (INFO .NE. 0) ERROR STOP 'B'
  READ (CLA,*) B
  CALL GET_COMMAND_ARGUMENT(3, CLA, M_B, INFO)
  IF (INFO .NE. 0) ERROR STOP 'S'
  READ (CLA,*) INFO

  IF (INFO .EQ. REAL32) THEN
     WRITE (OUTPUT_UNIT,*) 'Assuming REAL32.'
  ELSE IF (INFO .EQ. REAL64) THEN
     WRITE (OUTPUT_UNIT,*) 'Assuming REAL64.'
  ELSE IF (INFO .EQ. REAL128) THEN
     WRITE (OUTPUT_UNIT,*) 'Assuming REAL128.'  
  ELSE IF (INFO .EQ. -REAL32) THEN
     WRITE (OUTPUT_UNIT,*) 'Assuming COMPLEX(REAL32).'
  ELSE IF (INFO .EQ. -REAL64) THEN
     WRITE (OUTPUT_UNIT,*) 'Assuming COMPLEX(REAL64).'
  ELSE IF (INFO .EQ. -REAL128) THEN
     WRITE (OUTPUT_UNIT,*) 'Assuming COMPLEX(REAL128).'
  ELSE ! error
     ERROR STOP 'S must be one of +/-REAL32, +/-REAL64, +/-REAL128'
  END IF

  WRITE (OUTPUT_UNIT,*) 'N [   initial order of G] =', N
  WRITE (OUTPUT_UNIT,*) 'B [block row/column size] =', B
  LDG = N
  LDB = B
  CALL IBDIMS(LDG, LDB, M, M_B, NW, ND, NO, INFO)
  WRITE (OUTPUT_UNIT,*) 'M [ order of G, bordered] =', M
  WRITE (OUTPUT_UNIT,*) 'LDG [  leading dim for M] =', LDG
  WRITE (OUTPUT_UNIT,*) 'LDB [leading dim for 2*B] =', LDB
  WRITE (OUTPUT_UNIT,*) 'M / B                     =', M_B
  WRITE (OUTPUT_UNIT,*) 'len(W)                    =', NW
  WRITE (OUTPUT_UNIT,*) 'len(D)                    =', ND
  WRITE (OUTPUT_UNIT,*) 'ncols(O) [        O(2,:)] =', NO
  WRITE (OUTPUT_UNIT,*) 'values in an L1 cache line=', INFO
END PROGRAM IBDIMSX
