..\bin\$(PLAT)\sksvd2.exe: test\sksvd2x.F90 test\tksvd2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesksvd2.exe ..\..\..\src\test\sksvd2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\cksvd2.exe: test\cksvd2x.F90 test\uksvd2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecksvd2.exe ..\..\..\src\test\cksvd2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dksvd2.exe: test\dksvd2x.F90 test\tksvd2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedksvd2.exe ..\..\..\src\test\dksvd2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zksvd2.exe: test\zksvd2x.F90 test\uksvd2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezksvd2.exe ..\..\..\src\test\zksvd2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\qksvd2.exe: test\qksvd2x.F90 test\tksvd2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Feqksvd2.exe ..\..\..\src\test\qksvd2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\yksvd2.exe: test\yksvd2x.F90 test\uksvd2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Feyksvd2.exe ..\..\..\src\test\yksvd2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\slwsv2.exe: test\slwsv2x.F90 test\tlasv2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Feslwsv2.exe ..\..\..\src\test\slwsv2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib $(LDFLAGS)

..\bin\$(PLAT)\dlwsv2.exe: test\dlwsv2x.F90 test\tlasv2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedlwsv2.exe ..\..\..\src\test\dlwsv2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib $(LDFLAGS)

..\bin\$(PLAT)\qlwsv2.exe: test\qlwsv2x.F90 test\tlasv2.F90 ..\lib\$(PLAT)\ksvd2.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Feqlwsv2.exe ..\..\..\src\test\qlwsv2x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib $(LDFLAGS)

..\bin\$(PLAT)\sran.exe: test\sran.F90 test\gran.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesran.exe ..\..\..\src\test\sran.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) faux.lib $(LDFLAGS)

..\bin\$(PLAT)\cran.exe: test\cran.F90 test\hran.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecran.exe ..\..\..\src\test\cran.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dran.exe: test\dran.F90 test\gran.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedran.exe ..\..\..\src\test\dran.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zran.exe: test\zran.F90 test\hran.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezran.exe ..\..\..\src\test\zran.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) faux.lib $(LDFLAGS)

..\bin\$(PLAT)\srnd.exe: test\srnd.F90 test\grnd.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesrnd.exe ..\..\..\src\test\srnd.F90 $(LDFLAGS)

..\bin\$(PLAT)\crnd.exe: test\crnd.F90 test\hrnd.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecrnd.exe ..\..\..\src\test\crnd.F90 $(LDFLAGS)

..\bin\$(PLAT)\drnd.exe: test\drnd.F90 test\grnd.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedrnd.exe ..\..\..\src\test\drnd.F90 $(LDFLAGS)

..\bin\$(PLAT)\zrnd.exe: test\zrnd.F90 test\hrnd.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezrnd.exe ..\..\..\src\test\zrnd.F90 $(LDFLAGS)

..\bin\$(PLAT)\sran2u.exe: test\sran2t.F90 test\gran2t.F90 test\gran2u.F90 test\gr2ud.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) -DUPPER /Fesran2u.exe ..\..\..\src\test\sran2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\sran2g.exe: test\sran2t.F90 test\gran2t.F90 test\gran2g.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesran2g.exe ..\..\..\src\test\sran2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\cran2g.exe: test\cran2t.F90 test\hran2t.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecran2g.exe ..\..\..\src\test\cran2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dran2u.exe: test\dran2t.F90 test\gran2t.F90 test\gran2u.F90 test\gr2ud.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) -DUPPER /Fedran2u.exe ..\..\..\src\test\dran2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dran2g.exe: test\dran2t.F90 test\gran2t.F90 test\gran2g.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedran2g.exe ..\..\..\src\test\dran2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zran2g.exe: test\zran2t.F90 test\hran2t.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezran2g.exe ..\..\..\src\test\zran2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\srnd2u.exe: test\srnd2t.F90 test\grnd2t.F90 test\grnd2u.F90 test\gr2ud.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) -DUPPER /Fesrnd2u.exe ..\..\..\src\test\srnd2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\srnd2g.exe: test\srnd2t.F90 test\grnd2t.F90 test\grnd2g.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesrnd2g.exe ..\..\..\src\test\srnd2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\crnd2g.exe: test\crnd2t.F90 test\hrnd2t.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecrnd2g.exe ..\..\..\src\test\crnd2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\drnd2u.exe: test\drnd2t.F90 test\grnd2t.F90 test\grnd2u.F90 test\gr2ud.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) -DUPPER /Fedrnd2u.exe ..\..\..\src\test\drnd2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\drnd2g.exe: test\drnd2t.F90 test\grnd2t.F90 test\grnd2g.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedrnd2g.exe ..\..\..\src\test\drnd2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zrnd2g.exe: test\zrnd2t.F90 test\hrnd2t.F90 ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezrnd2g.exe ..\..\..\src\test\zrnd2t.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) ksvd2.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\seedsz.exe: test\seedsz.F90 $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Feseedsz.exe ..\..\..\src\test\seedsz.F90 $(LDFLAGS)

..\bin\$(PLAT)\sthalt.exe: test\sthaltx.F90 ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Festhalt.exe ..\..\..\src\test\sthaltx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) faux.lib $(LDFLAGS)

..\bin\$(PLAT)\jsweep.exe: test\jsweepx.F90 ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fejsweep.exe ..\..\..\src\test\jsweepx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) faux.lib $(LDFLAGS)

..\bin\$(PLAT)\sksvd0.exe: test\sksvd0x.F90 test\gksvd0x.F90 test\srdinp.F90 test\swrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesksvd0.exe ..\..\..\src\test\sksvd0x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\cksvd0.exe: test\cksvd0x.F90 test\hksvd0x.F90 test\crdinp.F90 test\cwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecksvd0.exe ..\..\..\src\test\cksvd0x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dksvd0.exe: test\dksvd0x.F90 test\gksvd0x.F90 test\drdinp.F90 test\dwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedksvd0.exe ..\..\..\src\test\dksvd0x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zksvd0.exe: test\zksvd0x.F90 test\hksvd0x.F90 test\zrdinp.F90 test\zwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezksvd0.exe ..\..\..\src\test\zksvd0x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\sksvd1.exe: test\sksvd1x.F90 test\gksvd1x.F90 test\srdinp.F90 test\swrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesksvd1.exe ..\..\..\src\test\sksvd1x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\cksvd1.exe: test\cksvd1x.F90 test\hksvd1x.F90 test\crdinp.F90 test\cwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecksvd1.exe ..\..\..\src\test\cksvd1x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dksvd1.exe: test\dksvd1x.F90 test\gksvd1x.F90 test\drdinp.F90 test\dwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedksvd1.exe ..\..\..\src\test\dksvd1x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zksvd1.exe: test\zksvd1x.F90 test\hksvd1x.F90 test\zrdinp.F90 test\zwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezksvd1.exe ..\..\..\src\test\zksvd1x.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\sksvdd.exe: test\sksvddx.F90 test\gksvddx.F90 test\srdinp.F90 test\swrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesksvdd.exe ..\..\..\src\test\sksvddx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\dksvdd.exe: test\dksvddx.F90 test\gksvddx.F90 test\drdinp.F90 test\dwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedksvdd.exe ..\..\..\src\test\dksvddx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\cksvdd.exe: test\cksvddx.F90 test\hksvddx.F90 test\crdinp.F90 test\cwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecksvdd.exe ..\..\..\src\test\cksvddx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\zksvdd.exe: test\zksvddx.F90 test\hksvddx.F90 test\zrdinp.F90 test\zwrout.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\ksvd2.lib ..\lib\$(PLAT)\arrbio.lib ..\lib\$(PLAT)\faux.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezksvdd.exe ..\..\..\src\test\zksvddx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib ksvd2.lib arrbio.lib faux.lib $(LDFLAGS)

..\bin\$(PLAT)\smkbpq.exe: test\smkbpqx.F90 test\gmkbpqx.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\arrbio.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fesmkbpq.exe ..\..\..\src\test\smkbpqx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib arrbio.lib $(LDFLAGS)

..\bin\$(PLAT)\dmkbpq.exe: test\dmkbpqx.F90 test\gmkbpqx.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\arrbio.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fedmkbpq.exe ..\..\..\src\test\dmkbpqx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib arrbio.lib $(LDFLAGS)

..\bin\$(PLAT)\cmkbpq.exe: test\cmkbpqx.F90 test\gmkbpqx.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\arrbio.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fecmkbpq.exe ..\..\..\src\test\cmkbpqx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib arrbio.lib $(LDFLAGS)

..\bin\$(PLAT)\zmkbpq.exe: test\zmkbpqx.F90 test\gmkbpqx.F90 ..\lib\$(PLAT)\blksvd.lib ..\lib\$(PLAT)\dynord.lib ..\lib\$(PLAT)\arrbio.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Fezmkbpq.exe ..\..\..\src\test\zmkbpqx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib dynord.lib arrbio.lib $(LDFLAGS)

..\bin\$(PLAT)\ibdims.exe: test\ibdimsx.F90 ..\lib\$(PLAT)\blksvd.lib $(MKFS)
	cd ..\bin\$(PLAT) && $(FC) $(FCFLAGS) /Feibdims.exe ..\..\..\src\test\ibdimsx.F90 /link /RELEASE /LIBPATH:..\..\..\lib\$(PLAT) blksvd.lib $(LDFLAGS)
