PROGRAM MINMAX
  IMPLICIT NONE
  REAL, PARAMETER :: ZERO = 0.0, MZERO = -0.0
  PRINT *, 'MIN(+0.0,-0.0)=', MIN(ZERO, MZERO)
  PRINT *, 'MIN(-0.0,+0.0)=', MIN(MZERO, ZERO)
  PRINT *, 'MAX(+0.0,-0.0)=', MAX(ZERO, MZERO)
  PRINT *, 'MAX(-0.0,+0.0)=', MAX(MZERO, ZERO)
END PROGRAM MINMAX
