!>@brief \b QKALT2X tests the QKALT2 routine.
PROGRAM QKALT2X
  IMPLICIT NONE
  CALL QTEST
CONTAINS
  !>@brief \b QTEST calls QKALT2.
  SUBROUTINE QTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
#ifdef NDEBUG
       PURE SUBROUTINE QKALT2(G, U, V, S, INFO)
#else
       SUBROUTINE QKALT2(G, U, V, S, INFO)
#endif
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
         IMPLICIT NONE
         REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
         REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE QKALT2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL128) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 QKALT2
#include "tksvd2.F90"
1   FORMAT(A,ES45.36E4)
2   FORMAT(A,I6)
  END SUBROUTINE QTEST
END PROGRAM QKALT2X
