!>@brief \b QKSVD2X tests the QKSVD2 routine.
PROGRAM QKSVD2X
  IMPLICIT NONE
  CALL QTEST
CONTAINS
  !>@brief \b QTEST calls QKSVD2.
  SUBROUTINE QTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
    INTERFACE
       SUBROUTINE QKSVD2(G, U, V, S, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
         IMPLICIT NONE
         REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
         REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO(3)
       END SUBROUTINE QKSVD2
    END INTERFACE
    INTERFACE
       PURE SUBROUTINE QKERR2(G, U, V, S, E, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
         IMPLICIT NONE
         REAL(KIND=REAL128), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
         REAL(KIND=REAL128), INTENT(OUT) :: E(3)
         INTEGER, INTENT(IN) :: INFO(3)
       END SUBROUTINE QKERR2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0)-1, CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=KX) :: E(3)
    REAL(KIND=REAL128) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, J, INFO(3)
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 QKSVD2
#define KERR2 QKERR2
#include "tksvd2.F90"
1   FORMAT(A,ES45.36E4)
2   FORMAT(A,I6)
  END SUBROUTINE QTEST
END PROGRAM QKSVD2X
