!>@brief \b QLWSV2X tests the QLWSV2 routine.
PROGRAM QLWSV2X
  IMPLICIT NONE
  CALL QLTEST
CONTAINS
  !>@brief \b QLTEST calls QLWSV2.
  SUBROUTINE QLTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
    INTERFACE
       SUBROUTINE QLWSV2(G, U, V, S, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
         IMPLICIT NONE
         REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
         REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(OUT) :: INFO
       END SUBROUTINE QLWSV2
    END INTERFACE
    INTERFACE
       PURE SUBROUTINE QKERR2(G, U, V, S, E, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
         IMPLICIT NONE
         REAL(KIND=REAL128), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
         REAL(KIND=REAL128), INTENT(OUT) :: E(3)
         INTEGER, INTENT(IN) :: INFO(3)
       END SUBROUTINE QKERR2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0)-1, CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=KX) :: E(3)
    REAL(KIND=REAL128) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO, INFO3(3)
    LOGICAL :: ONCE
    G(2,1) = 0.0_REAL128
#define LSVD2 QLWSV2
#define KERR2 QKERR2
#include "tlasv2.F90"
1   FORMAT(A,ES45.36E4)
2   FORMAT(A,I6)
  END SUBROUTINE QLTEST
END PROGRAM QLWSV2X
