!>@brief QRAN generates a set of pseudorandom quadruple precision real 2x2 matrices.
PROGRAM QRAN
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTERFACE
     FUNCTION ORFILE()
       IMPLICIT NONE
       INTEGER :: ORFILE
     END FUNCTION ORFILE
  END INTERFACE
  INTERFACE
     FUNCTION QRSAFE(U)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=REAL128) :: QRSAFE
     END FUNCTION QRSAFE
  END INTERFACE
  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N, U
  LOGICAL :: UPPER
#define RSAFE QRSAFE
#include "gran.F90"
1 FORMAT(A,ES45.36E4)
END PROGRAM QRAN
