!>@brief QRND2T tests a set of pseudorandom quadruple precision real 2x2 matrices.
PROGRAM QRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128, ERROR_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE QKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE QKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE QKSVD2
  END INTERFACE
#define KSVD2 QKSVD2
  INTERFACE
     PURE SUBROUTINE QKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE QKERR2
  END INTERFACE
#define KERR2 QKERR2
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTEGER, ALLOCATABLE :: ISEED(:)
  REAL(KIND=REAL128), ALLOCATABLE :: G(:,:,:), U(:,:,:), V(:,:,:), S(:,:), E(:,:)
  INTEGER, ALLOCATABLE :: INFO(:)
  REAL(KIND=REAL128) :: F(6), T
  INTEGER :: SSIZE, I, J, K, L, M, N
  CHARACTER(LEN=64) :: CLA
#include "grnd2t.F90"
1 FORMAT(A,ES45.36E4)
END PROGRAM QRND2T
