PROGRAM S2G110
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_NEXT_UP
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
#ifdef NDEBUG
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
#else
     FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
#endif
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  REAL, PARAMETER :: ZERO = 0.0, ONE = 1.0
  REAL :: Y
  Y = SCALE(EPSILON(Y), -1)
  DO WHILE (CR_HYPOT(ONE, Y) .EQ. ONE)
     WRITE (*,1) ONE, ONE
     WRITE (*,1) ZERO, Y
     Y = IEEE_NEXT_UP(Y)
  END DO
1 FORMAT(2ES16.9E2)
END PROGRAM S2G110
