!>@brief \b SKSVD2X tests the SKSVD2 routine.
PROGRAM SKSVD2X
  IMPLICIT NONE
  CALL STEST
CONTAINS
  !>@brief \b STEST calls SKSVD2.
  SUBROUTINE STEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL32, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
#ifdef NDEBUG
       PURE SUBROUTINE SKSVD2(G, U, V, S, INFO)
#else
       SUBROUTINE SKSVD2(G, U, V, S, INFO)
#endif
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
         IMPLICIT NONE
         REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
         REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE SKSVD2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL32) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 SKSVD2
#include "tksvd2.F90"
1   FORMAT(A,ES16.9E2)
2   FORMAT(A,I4)
  END SUBROUTINE STEST
END PROGRAM SKSVD2X
