!>@brief \b SKSVD1X tests the SKSVD1 routine.
PROGRAM SKSVD1X
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE IBDIMS(N, B, M, M_B, NW, ND, NO, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(INOUT) :: N, B, M, INFO
       INTEGER, INTENT(OUT) :: M_B, NW, ND, NO
     END SUBROUTINE IBDIMS
  END INTERFACE
  INTERFACE
     SUBROUTINE SBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=REAL32), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SBRDG
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE INITRC(N, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       INTEGER, INTENT(OUT) :: O(2,*), INFO
     END SUBROUTINE INITRC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE INITCC(N, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       INTEGER, INTENT(OUT) :: O(2,*), INFO
     END SUBROUTINE INITCC
  END INTERFACE
  INTERFACE
     SUBROUTINE INITME(N, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       INTEGER, INTENT(OUT) :: O(2,*), INFO
     END SUBROUTINE INITME
  END INTERFACE
  INTERFACE
     SUBROUTINE INITMM(N, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       INTEGER, INTENT(OUT) :: O(2,*), INFO
     END SUBROUTINE INITMM
  END INTERFACE
  INTERFACE
     SUBROUTINE SKSVD1(JOB, M, B, G, LDG, U, LDU, V, LDV, SV, LDB, W, NW, D, ND, O, NO, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, M, B, LDG, LDU, LDV, LDB, NW, ND, NO
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,M), U(LDU,M), V(LDV,M)
#ifdef ANIMATE
       REAL(KIND=REAL32), INTENT(INOUT), TARGET :: SV(M)
#else
       REAL(KIND=REAL32), INTENT(OUT) :: SV(M)
#endif
       REAL(KIND=REAL32), INTENT(OUT) :: W(NW)
       REAL(KIND=REAL64), INTENT(OUT) :: D(ND)
       INTEGER, INTENT(INOUT) :: O(2,NO), INFO
     END SUBROUTINE SKSVD1
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL32, KK = REAL64, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER :: JOB, M, N, B, M_B, LDG, LDU, LDV, LDB, NW, ND, NO, INFO, I, J, L
  REAL(KIND=K), ALLOCATABLE :: G(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: G
  REAL(KIND=K), ALLOCATABLE :: U(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: U
  REAL(KIND=K), ALLOCATABLE :: V(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: V
#ifdef ANIMATE
  REAL(KIND=K), ALLOCATABLE, TARGET :: SV(:)
#else
  REAL(KIND=K), ALLOCATABLE :: SV(:)
#endif
  !DIR$ ATTRIBUTES ALIGN: 64:: SV
  REAL(KIND=K), ALLOCATABLE :: W(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: W
  REAL(KIND=KK), ALLOCATABLE :: D(:)
  !DIR$ ATTRIBUTES ALIGN: 64:: D
  INTEGER, ALLOCATABLE :: O(:,:)
  !DIR$ ATTRIBUTES ALIGN: 64:: O
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  TYPE(c_ptr), EXTERNAL :: PVN_RVIS_START_F
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RVIS_STOP_F
#define VIS_START PVN_RVIS_START_F
#define VIS_STOP PVN_RVIS_STOP_F
#endif
#define BRDG SBRDG
#define RDINP SRDINP
#define WROUT SWROUT
#define KSVD1 SKSVD1
#include "gksvd1x.F90"
9 FORMAT(3(ES16.9E2,A))
CONTAINS
#include "srdinp.F90"
#include "swrout.F90"
END PROGRAM SKSVD1X
