!>@brief \b SKSVDDX tests the SKSVDD routine.
PROGRAM SKSVDDX
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE SBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=REAL32), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE SKSVDD(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, D, O, OD, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(2,*)
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL32), INTENT(OUT) :: SV(N), W(*)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(OUT) :: OD(2,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SKSVDD
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL32, KK = REAL64
#define BRDG SBRDG
#define KSVDD SKSVDD
#define RDINP SRDINP
#define WROUT SWROUT
#include "gksvddx.F90"
9 FORMAT(3(ES16.9E2,A))
CONTAINS
#include "srdinp.F90"
#include "swrout.F90"
END PROGRAM SKSVDDX
