!>@brief \b SLWSV2X tests the SLWSV2 routine.
PROGRAM SLWSV2X
  IMPLICIT NONE
  EXTERNAL :: SLWSV2
  CALL SLTEST(SLWSV2)
CONTAINS
  !>@brief \b SLTEST calls LSVD2.
  !!
  !!@param LSVD2 is SLWSV2.
  SUBROUTINE SLTEST(LSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL32, REAL64, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    EXTERNAL :: LSVD2
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL32) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    G(2,1) = 0.0_REAL32
#include "tlasv2.F90"
1   FORMAT(A,ES16.9E2)
2   FORMAT(A,I4)
  END SUBROUTINE SLTEST
END PROGRAM SLWSV2X
