!>@brief SRAN2T tests a set of pseudorandom single precision real 2x2 matrices.
PROGRAM SRAN2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128, OUTPUT_UNIT, ERROR_UNIT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE SKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SKSVD2
  END INTERFACE
#define KSVD2 SKSVD2
#ifdef UPPER
  INTERFACE
     PURE SUBROUTINE SLWSV2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE SLWSV2
  END INTERFACE
#define LWSV2 SLWSV2
#endif
  INTERFACE
     PURE SUBROUTINE SKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SKERR2
  END INTERFACE
#define KERR2 SKERR2
  INTERFACE
     SUBROUTINE QKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE QKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
#ifdef UPPER
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
#endif
  REAL(KIND=REAL32) :: G(2,2), U(2,2), V(2,2), S(2), T
  REAL(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2), QS(2)
#ifdef UPPER
  REAL(KIND=REAL128) :: E(5,2), F(2,16), Q
#else
  REAL(KIND=REAL128) :: E(5,1), F(2,6), Q
#endif
  INTEGER :: I, J, K, L, M, N, INFO
  INTEGER(KIND=c_int) :: O
  CHARACTER(LEN=64) :: CLA
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RAN_OPEN, PVN_RAN_CLOSE
  REAL(KIND=REAL32), EXTERNAL :: PVN_RAN_SAFE_F
#define RAN_SAFE PVN_RAN_SAFE_F
#include "gran2t.F90"
1 FORMAT(A,ES16.9E2)
END PROGRAM SRAN2T
