!>@brief SRAN generates a set of pseudorandom single precision real 2x2 matrices.
PROGRAM SRAN
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N
  INTEGER(KIND=c_int) :: U
  LOGICAL :: UPPER
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RAN_OPEN, PVN_RAN_CLOSE
  REAL(KIND=REAL32), EXTERNAL :: PVN_RAN_SAFE_F
#define RAN_SAFE PVN_RAN_SAFE_F
#include "gran.F90"
1 FORMAT(A,ES16.9E2)
END PROGRAM SRAN
