!>@brief SRND generates a set of pseudorandom single precision real 2x2 matrices.
PROGRAM SRND
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, ERROR_UNIT
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  INTEGER, ALLOCATABLE :: ISEED(:)
  REAL(KIND=REAL32), ALLOCATABLE :: H(:)
  CHARACTER(LEN=64) :: CLA
  INTEGER :: SSIZE, N, I
  LOGICAL :: UPPER
  REAL(KIND=REAL32) :: T
#include "grnd.F90"
1 FORMAT(A,ES16.9E2)
END PROGRAM SRND
