!>@brief SRND2T tests a set of pseudorandom single precision real 2x2 matrices.
PROGRAM SRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128, ERROR_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE SKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE SKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SKSVD2
  END INTERFACE
#define KSVD2 SKSVD2
#ifdef UPPER
  INTERFACE
     PURE SUBROUTINE SLWSV2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE SLWSV2
  END INTERFACE
#define LWSV2 SLWSV2
#endif
  INTERFACE
     PURE SUBROUTINE SKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SKERR2
  END INTERFACE
#define KERR2 SKERR2
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
#ifdef UPPER
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
#endif
  INTEGER, ALLOCATABLE :: ISEED(:)
  REAL(KIND=REAL32), ALLOCATABLE :: G(:,:,:)
#ifdef UPPER
  REAL(KIND=REAL32), ALLOCATABLE :: U(:,:,:,:), V(:,:,:,:), S(:,:,:)
  REAL(KIND=REAL128), ALLOCATABLE :: E(:,:,:)
  INTEGER, ALLOCATABLE :: INFO(:,:)
  REAL(KIND=REAL128) :: F(18), Q
#else
  REAL(KIND=REAL32), ALLOCATABLE :: U(:,:,:), V(:,:,:), S(:,:)
  REAL(KIND=REAL128), ALLOCATABLE :: E(:,:)
  INTEGER, ALLOCATABLE :: INFO(:)
  REAL(KIND=REAL128) :: F(6)
  REAL(KIND=REAL32) :: T
#endif
  INTEGER :: SSIZE, I, J, K, L, M, N
  CHARACTER(LEN=64) :: CLA
#include "grnd2t.F90"
1 FORMAT(A,ES16.9E2)
END PROGRAM SRND2T
