!>@brief \b STHALTX tests the STHALT routine.
PROGRAM STHALTX
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: OUTPUT_UNIT
  IMPLICIT NONE
  CALL C
CONTAINS
  SUBROUTINE A
    IMPLICIT NONE
#ifndef __GFORTRAN__
    INTERFACE
       SUBROUTINE STHALT(MSG)
         IMPLICIT NONE
         CHARACTER(LEN=*), INTENT(IN) :: MSG
       END SUBROUTINE STHALT
    END INTERFACE
#else
    EXTERNAL :: STHALT
#endif
    WRITE (OUTPUT_UNIT,'(A)') 'Subroutine A'
    CALL STHALT('Called in A')
  END SUBROUTINE A
  SUBROUTINE B
    IMPLICIT NONE
    WRITE (OUTPUT_UNIT,'(A)') 'Subroutine B'
    CALL A
  END SUBROUTINE B
  SUBROUTINE C
    IMPLICIT NONE
    WRITE (OUTPUT_UNIT,'(A)') 'Subroutine C'
    CALL B
  END SUBROUTINE C
END PROGRAM STHALTX
