!>@brief \b WKSVD2X tests the WKSVD2 routine.
PROGRAM WKSVD2X
  IMPLICIT NONE
  CALL WTEST
CONTAINS
  !>@brief \b WTEST calls WKSVD2.
  SUBROUTINE WTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
       SUBROUTINE WKSVD2(G, U, V, S, INFO)
         IMPLICIT NONE
         COMPLEX(KIND=10), INTENT(IN) :: G(2,2)
         COMPLEX(KIND=10), INTENT(OUT) :: U(2,2), V(2,2)
         REAL(KIND=10), INTENT(OUT) :: S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE WKSVD2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 132
    CHARACTER(LEN=CLAL) :: CLA
    COMPLEX(KIND=10) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=10) :: S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    COMPLEX(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2)
    REAL(KIND=KX) :: SX(2,2)
#define KSVD2 WKSVD2
#include "uksvd2.F90"
1   FORMAT(A,ES30.21E4)
2   FORMAT(A,'(',ES30.21E4,',',ES30.21E4,')')
3   FORMAT(A,I6)
  END SUBROUTINE WTEST
END PROGRAM WKSVD2X
