!>@brief \b WKSVDDX tests the WKSVDD routine.
PROGRAM WKSVDDX
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE ZBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       COMPLEX(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE WKSVDD(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, D, O, OD, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(2,*)
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL64), INTENT(OUT) :: SV(N), W(*)
       REAL(KIND=c_long_double), INTENT(OUT) :: D(*)
       INTEGER, INTENT(OUT) :: OD(2,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WKSVDD
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL64, KK = c_long_double
#define BRDG ZBRDG
#define KSVDD WKSVDD
#define RDINP ZRDINP
#define WROUT ZWROUT
#include "hksvddx.F90"
9 FORMAT(3(ES25.17E3,A))
CONTAINS
#include "zrdinp.F90"
#include "zwrout.F90"
END PROGRAM WKSVDDX
