!>@brief \b WKSVD2X tests the WKSVD2 routine.
PROGRAM WKSVD2X
  IMPLICIT NONE
  EXTERNAL :: WKSVD2
  CALL WTEST(WKSVD2)
CONTAINS
  !>@brief \b WTEST calls KSVD2.
  !!
  !!@param KSVD2 is WKSVD2.
  SUBROUTINE WTEST(KSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 132
    EXTERNAL :: KSVD2
    CHARACTER(LEN=CLAL) :: CLA
    COMPLEX(KIND=10) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=10) :: S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    COMPLEX(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2)
    REAL(KIND=KX) :: SX(2,2)
#include "uksvd2.F90"
1   FORMAT(A,ES30.21E4)
2   FORMAT(A,'(',ES30.21E4,',',ES30.21E4,')')
3   FORMAT(A,I6)
  END SUBROUTINE WTEST
END PROGRAM WKSVD2X
