!>@brief WRAN2T tests a set of pseudorandom single precision complex 2x2 matrices.
PROGRAM WRAN2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128, OUTPUT_UNIT, ERROR_UNIT
  USE, INTRINSIC :: ISO_C_BINDING
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE WKSVD2(G, U, V, S, INFO)
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=10), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=10), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WKSVD2
  END INTERFACE
#define KSVD2 WKSVD2
  INTERFACE
     PURE SUBROUTINE WKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=10), INTENT(IN) :: S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WKERR2
  END INTERFACE
#define KERR2 WKERR2
  INTERFACE
     SUBROUTINE YKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       COMPLEX(KIND=REAL128), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE YKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTERFACE
     FUNCTION XRSAFE(U)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=10) :: XRSAFE
     END FUNCTION XRSAFE
  END INTERFACE
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
  INTEGER, PARAMETER :: D = 10
  COMPLEX(KIND=10) :: G(2,2), U(2,2), V(2,2)
  REAL(KIND=10) :: S(2)
  COMPLEX(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2)
  REAL(KIND=REAL128) :: QS(2), E(5), F(2,6), Q
  INTEGER :: I, J, K, L, M, N, INFO
  CHARACTER(LEN=64) :: CLA
#define RSAFE XRSAFE
#include "hran2t.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM WRAN2T
