!>@brief WRAN generates a set of pseudorandom extended precision complex 2x2 matrices.
PROGRAM WRAN
  IMPLICIT NONE
  INTERFACE
     FUNCTION ORFILE()
       IMPLICIT NONE
       INTEGER :: ORFILE
     END FUNCTION ORFILE
  END INTERFACE
  INTERFACE
     FUNCTION XRSAFE(U)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=10) :: XRSAFE
     END FUNCTION XRSAFE
  END INTERFACE
  REAL(KIND=10), PARAMETER :: ZERO = 0.0_10
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N, U
  LOGICAL :: UPPER
#define RSAFE XRSAFE
#include "hran.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM WRAN
