!>@brief WRND2T tests a set of pseudorandom single precision complex 2x2 matrices.
PROGRAM WRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128, ERROR_UNIT
  USE, INTRINSIC :: ISO_C_BINDING
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE WKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE WKSVD2(G, U, V, S, INFO)
#endif
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=10), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=10), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WKSVD2
  END INTERFACE
#define KSVD2 WKSVD2
  INTERFACE
     PURE SUBROUTINE WKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=10), INTENT(IN) :: S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WKERR2
  END INTERFACE
#define KERR2 WKERR2
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTEGER, PARAMETER :: D = 10
  INTEGER, ALLOCATABLE :: ISEED(:)
  COMPLEX(KIND=10), ALLOCATABLE, TARGET :: G(:,:,:)
  COMPLEX(KIND=10), ALLOCATABLE :: U(:,:,:), V(:,:,:)
  REAL(KIND=10), ALLOCATABLE :: S(:,:)
  REAL(KIND=REAL128), ALLOCATABLE :: E(:,:)
  INTEGER, ALLOCATABLE :: INFO(:)
  REAL(KIND=10), POINTER, CONTIGUOUS :: P(:,:,:)
  REAL(KIND=REAL128) :: F(6)
  REAL(KIND=10) :: T
  INTEGER :: SSIZE, I, J, K, L, M, N
  CHARACTER(LEN=64) :: CLA
#include "hrnd2t.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM WRND2T
