!>@brief \b XKSUM2X tests the XKSUM2 routine.
PROGRAM XKSUM2X
  IMPLICIT NONE
  CALL XTEST
CONTAINS
  !>@brief \b XTEST calls XKSUM2.
  SUBROUTINE XTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
#ifdef NDEBUG
       PURE SUBROUTINE XKSUM2(G, U, V, S, INFO)
#else
       SUBROUTINE XKSUM2(G, U, V, S, INFO)
#endif
         IMPLICIT NONE
         REAL(KIND=10), INTENT(IN) :: G(2,2)
         REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE XKSUM2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=10) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 XKSUM2
#include "tksvd2.F90"
1   FORMAT(A,ES30.21E4)
2   FORMAT(A,I6)
  END SUBROUTINE XTEST
END PROGRAM XKSUM2X
