!>@brief \b XKSVD0X tests the XKSVD0 routine.
PROGRAM XKSVD0X
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE XBRDG(M, N, G, LDG, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=10), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE XRDINP(BN, M, N, G, LDG, INFO)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: BN
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=10), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XRDINP
  END INTERFACE
  INTERFACE
     SUBROUTINE JSWEEP(J, N, S, P, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N
       INTEGER, INTENT(OUT) :: S, P, O(2,*), INFO
     END SUBROUTINE JSWEEP
  END INTERFACE
  INTERFACE
     SUBROUTINE XKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       REAL(KIND=10), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL128), INTENT(OUT), TARGET :: SV(N)
       REAL(KIND=10), INTENT(INOUT) :: W(MAX(N,3)*N)
       INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
     END SUBROUTINE XKSVD0
  END INTERFACE
  INTERFACE
     SUBROUTINE XWROUT(BN, J, N, U, LDU, V, LDV, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: BN
       INTEGER, INTENT(IN) :: J, N, LDU, LDV
       REAL(KIND=10), INTENT(IN) :: U(LDU,N), V(LDV,N)
       REAL(KIND=REAL128), INTENT(IN) :: S(N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XWROUT
  END INTERFACE

#ifdef ANIMATE
  INTERFACE
     FUNCTION PVN_RVIS_START(mA, nA, act, fname) BIND(C,name='pvn_rvis_start_l_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_ptr, c_char
       IMPLICIT NONE
       INTEGER(KIND=c_int), INTENT(IN), TARGET :: mA, nA, act
       CHARACTER(KIND=c_char), INTENT(IN), TARGET :: fname(*)
       TYPE(c_ptr) :: PVN_RVIS_START
     END FUNCTION PVN_RVIS_START
  END INTERFACE
  INTERFACE
     FUNCTION PVN_RVIS_STOP(ctx, sx, sy, bpp, cmap) BIND(C,name='pvn_rvis_stop_l_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_ptr, c_char
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), TARGET :: ctx
       INTEGER(KIND=c_int), INTENT(IN), TARGET :: sx, sy, bpp
       CHARACTER(KIND=c_char), INTENT(IN), TARGET :: cmap(*)
       INTEGER(KIND=c_int) :: PVN_RVIS_STOP
     END FUNCTION PVN_RVIS_STOP
  END INTERFACE
#endif

  INTEGER, PARAMETER :: K = 10, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER, TARGET :: JOB, M
  INTEGER :: N, LDG, LDU, LDV, INFO, I, J, L, S, P
  REAL(KIND=K), ALLOCATABLE, TARGET :: G(:,:)
  REAL(KIND=K), ALLOCATABLE :: U(:,:)
  REAL(KIND=K), ALLOCATABLE :: V(:,:)
  REAL(KIND=K), ALLOCATABLE :: W(:)
  REAL(KIND=REAL128), ALLOCATABLE, TARGET :: SV(:)
  INTEGER, ALLOCATABLE :: O(:)
#ifdef ANIMATE
  TYPE(c_ptr), TARGET :: CTX
  TYPE(c_ptr), POINTER :: CP
#endif

#define BRDG XBRDG
#define RDINP XRDINP
#define WROUT XWROUT
#define KSVD0 XKSVD0
#include "gksvd0x.F90"
9 FORMAT(3(ES30.21E4,A))
END PROGRAM XKSVD0X
