!>@brief \b XKSVDDX tests the XKSVDD routine.
PROGRAM XKSVDDX
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE DBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE XKSVDD(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, D, O, OD, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(2,*)
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL64), INTENT(OUT) :: SV(N), W(*)
       REAL(KIND=c_long_double), INTENT(OUT) :: D(*)
       INTEGER, INTENT(OUT) :: OD(2,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKSVDD
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL64, KK = c_long_double
#define BRDG DBRDG
#define KSVDD XKSVDD
#define RDINP DRDINP
#define WROUT DWROUT
#include "gksvddx.F90"
9 FORMAT(3(ES25.17E3,A))
CONTAINS
#include "drdinp.F90"
#include "dwrout.F90"
END PROGRAM XKSVDDX
