!>@brief \b XKSVD0X tests the XKSVD0 routine.
PROGRAM XKSVD0X
  USE, INTRINSIC :: ISO_C_BINDING
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE XBRDG(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=c_long_double), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE JSWEEP(J, N, S, P, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N
       INTEGER, INTENT(OUT) :: S, P, O(2,*), INFO
     END SUBROUTINE JSWEEP
  END INTERFACE
  INTERFACE
     SUBROUTINE XKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       REAL(KIND=c_long_double), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
#ifdef ANIMATE
       REAL(KIND=REAL128), INTENT(INOUT), TARGET :: SV(N)
#else
       REAL(KIND=REAL128), INTENT(OUT) :: SV(N)
#endif
       REAL(KIND=c_long_double), INTENT(OUT) :: W(*)
       INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
       INTEGER, INTENT(OUT) :: R(2,*)
     END SUBROUTINE XKSVD0
  END INTERFACE

  INTEGER, PARAMETER :: K = c_long_double, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER :: JOB, M, N, LDG, LDU, LDV, INFO, I, J, L, S, P
  REAL(KIND=K), ALLOCATABLE :: G(:,:)
  REAL(KIND=K), ALLOCATABLE :: U(:,:)
  REAL(KIND=K), ALLOCATABLE :: V(:,:)
  REAL(KIND=K), ALLOCATABLE :: W(:)
#ifdef ANIMATE
  REAL(KIND=REAL128), ALLOCATABLE, TARGET :: SV(:)
#else
  REAL(KIND=REAL128), ALLOCATABLE :: SV(:)
#endif
  INTEGER, ALLOCATABLE :: O(:)
  INTEGER, ALLOCATABLE :: R(:,:)
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  TYPE(c_ptr), EXTERNAL :: PVN_RVIS_START_L
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RVIS_STOP_L
#define PVN_RVIS_START PVN_RVIS_START_L
#define PVN_RVIS_STOP PVN_RVIS_STOP_L
#endif

#define BRDG XBRDG
#define RDINP XRDINP
#define WROUT XWROUT
#define KSVD0 XKSVD0
#include "gksvd0x.F90"
9 FORMAT(3(ES30.21E4,A))
CONTAINS
#include "xrdinp.F90"
#include "xwrout.F90"
END PROGRAM XKSVD0X
