!>@brief \b XKSVD0X tests the XKSVD0 routine.
PROGRAM XKSVD0X
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128, ERROR_UNIT, OUTPUT_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     PURE SUBROUTINE NB2M(N, B, M, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B
       INTEGER, INTENT(OUT) :: M, INFO
     END SUBROUTINE NB2M
  END INTERFACE
  INTERFACE
     SUBROUTINE XBRDG(M, N, G, LDG, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=10), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XBRDG
  END INTERFACE
  INTERFACE
     SUBROUTINE XRDINP(BN, M, N, G, LDG, INFO)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: BN
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=10), INTENT(OUT) :: G(LDG,M)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XRDINP
  END INTERFACE
  INTERFACE
     SUBROUTINE JSWEEP(J, N, S, P, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N
       INTEGER, INTENT(OUT) :: S, P, O(2,*), INFO
     END SUBROUTINE JSWEEP
  END INTERFACE
  INTERFACE
     SUBROUTINE XKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       REAL(KIND=10), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL128), INTENT(OUT), TARGET :: SV(N)
       REAL(KIND=10), INTENT(INOUT) :: W(MAX(N,3)*N)
       INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
     END SUBROUTINE XKSVD0
  END INTERFACE
  INTERFACE
     SUBROUTINE XWROUT(BN, J, N, U, LDU, V, LDV, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: BN
       INTEGER, INTENT(IN) :: J, N, LDU, LDV
       REAL(KIND=10), INTENT(IN) :: U(LDU,N), V(LDV,N)
       REAL(KIND=REAL128), INTENT(IN) :: S(N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XWROUT
  END INTERFACE

  INTEGER, PARAMETER :: K = 10, CLAL = 256
  CHARACTER(LEN=CLAL) :: BN
  INTEGER(KIND=INT64) :: C0, C1, CR
  REAL(KIND=REAL128) :: T
  INTEGER :: JOB, M, N, LDG, LDU, LDV, INFO, I, J, L, S, P
  REAL(KIND=K), ALLOCATABLE, TARGET :: G(:,:)
  REAL(KIND=K), ALLOCATABLE :: U(:,:), V(:,:), W(:)
  REAL(KIND=REAL128), ALLOCATABLE, TARGET :: SV(:)
  INTEGER, ALLOCATABLE :: O(:)

#define BRDG XBRDG
#define RDINP XRDINP
#define WROUT XWROUT
#define KSVD0 XKSVD0
#undef ANIMATE
#include "gksvd0x.F90"
9 FORMAT(3(ES30.21E4,A))
END PROGRAM XKSVD0X
