!>@brief \b XKSVD2X tests the XKSVD2 routine.
PROGRAM XKSVD2X
  IMPLICIT NONE
  CALL XTEST
CONTAINS
  !>@brief \b XTEST calls XKSVD2.
  SUBROUTINE XTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
#ifdef NDEBUG
       PURE SUBROUTINE XKSVD2(G, U, V, S, INFO)
#else
       SUBROUTINE XKSVD2(G, U, V, S, INFO)
#endif
         IMPLICIT NONE
         REAL(KIND=10), INTENT(IN) :: G(2,2)
         REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE XKSVD2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=10) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 XKSVD2
#include "tksvd2.F90"
1   FORMAT(A,ES30.21E4)
2   FORMAT(A,I6)
  END SUBROUTINE XTEST
END PROGRAM XKSVD2X
