!>@brief \b XKSVD2X tests the XKSVD2 routine.
PROGRAM XKSVD2X
  IMPLICIT NONE
  CALL XTEST
CONTAINS
  !>@brief \b XTEST calls XKSVD2.
  SUBROUTINE XTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
    INTERFACE
       SUBROUTINE XKSVD2(G, U, V, S, INFO)
         IMPLICIT NONE
         REAL(KIND=10), INTENT(IN) :: G(2,2)
         REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(INOUT) :: INFO(3)
       END SUBROUTINE XKSVD2
    END INTERFACE
    INTERFACE
       SUBROUTINE XKERR2(G, U, V, S, E, INFO)
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
         IMPLICIT NONE
         REAL(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
         REAL(KIND=REAL128), INTENT(OUT) :: E(3)
         INTEGER, INTENT(IN) :: INFO(3)
       END SUBROUTINE XKERR2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0)-1, CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=KX) :: E(3)
    REAL(KIND=10) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, J, INFO(3)
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
#define KSVD2 XKSVD2
#define KERR2 XKERR2
#include "tksvd2.F90"
1   FORMAT(A,ES30.21E4)
2   FORMAT(A,I6)
  END SUBROUTINE XTEST
END PROGRAM XKSVD2X
