!>@brief \b XLWSV2X tests the XLWSV2 routine.
PROGRAM XLWSV2X
  IMPLICIT NONE
  CALL XLTEST
CONTAINS
  !>@brief \b XLTEST calls XLWSV2.
  SUBROUTINE XLTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
       SUBROUTINE XLWSV2(G, U, V, S, INFO)
         IMPLICIT NONE
         REAL(KIND=10), INTENT(IN) :: G(2,2)
         REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
         INTEGER, INTENT(OUT) :: INFO
       END SUBROUTINE XLWSV2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0)-1, CLAL = 64
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=10) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    G(2,1) = 0.0_10
#define LSVD2 XLWSV2
#include "tlasv2.F90"
1   FORMAT(A,ES30.21E4)
2   FORMAT(A,I6)
  END SUBROUTINE XLTEST
END PROGRAM XLWSV2X
