!>@brief XRAN generates a set of pseudorandom extended precision real 2x2 matrices.
PROGRAM XRAN
  IMPLICIT NONE
  INTERFACE
     FUNCTION XRSAFE(U)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: U
       REAL(KIND=10) :: XRSAFE
     END FUNCTION XRSAFE
  END INTERFACE
  REAL(KIND=10), PARAMETER :: ZERO = 0.0_10
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N, U
  LOGICAL :: UPPER
#define RSAFE XRSAFE
#include "gran.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM XRAN
