!>@brief XRAN2T tests a set of pseudorandom extended precision real 2x2 matrices.
PROGRAM XRAN2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128, OUTPUT_UNIT, ERROR_UNIT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE XKSVD2(G, U, V, S, INFO)
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKSVD2
  END INTERFACE
#define KSVD2 XKSVD2
#ifdef UPPER
  INTERFACE
     PURE SUBROUTINE XLWSV2(G, U, V, S, INFO)
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XLWSV2
  END INTERFACE
#define LWSV2 XLWSV2
#endif
  INTERFACE
     PURE SUBROUTINE XKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKERR2
  END INTERFACE
#define KERR2 XKERR2
  INTERFACE
     SUBROUTINE QKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE QKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTEGER, PARAMETER :: D = 10
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
#ifdef UPPER
  REAL(KIND=D), PARAMETER :: ZERO = 0.0_D
#endif
  REAL(KIND=D) :: G(2,2), U(2,2), V(2,2), S(2)
#ifdef UPPER
  REAL(KIND=D) :: T
#endif
  REAL(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2), QS(2)
#ifdef UPPER
  REAL(KIND=REAL128) :: E(5,2), F(2,16), Q
#else
  REAL(KIND=REAL128) :: E(5,1), F(2,6), Q
#endif
  INTEGER :: I, J, K, L, M, N, INFO
  INTEGER(KIND=c_int) :: O
  CHARACTER(LEN=64) :: CLA
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RAN_OPEN, PVN_RAN_CLOSE
  REAL(KIND=D), EXTERNAL :: PVN_RAN_SAFE_L
#define RAN_SAFE PVN_RAN_SAFE_L
#include "gran2t.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM XRAN2T
