!>@brief XRND2T tests a set of pseudorandom extended precision real 2x2 matrices.
PROGRAM XRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128, ERROR_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE XKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE XKSVD2(G, U, V, S, INFO)
#endif
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKSVD2
  END INTERFACE
#define KSVD2 XKSVD2
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE XKALT2(G, U, V, S, INFO)
#else
     SUBROUTINE XKALT2(G, U, V, S, INFO)
#endif
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKALT2
  END INTERFACE
#define KALT2 XKALT2
  INTERFACE
     PURE SUBROUTINE XKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKERR2
  END INTERFACE
#define KERR2 XKERR2
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTEGER, ALLOCATABLE :: ISEED(:)
  REAL(KIND=10), ALLOCATABLE :: G(:,:,:), U(:,:,:,:), V(:,:,:,:), S(:,:,:)
  REAL(KIND=REAL128), ALLOCATABLE :: E(:,:,:)
  INTEGER, ALLOCATABLE :: INFO(:,:)
  REAL(KIND=REAL128) :: F(6)
  REAL(KIND=10) :: T
  INTEGER :: SSIZE, I, J, K, L, M, N
  CHARACTER(LEN=64) :: CLA
#include "grnd2t.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM XRND2T
