!>@brief XRND2T tests a set of pseudorandom extended precision real 2x2 matrices.
PROGRAM XRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128, OUTPUT_UNIT, ERROR_UNIT
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE XKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE XKSVD2(G, U, V, S, INFO)
#endif
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKSVD2
  END INTERFACE
#define KSVD2 XKSVD2
  INTERFACE
     SUBROUTINE XKALT2(G, U, V, S, INFO)
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKALT2
  END INTERFACE
#define KALT2 XKALT2
  INTERFACE
     PURE SUBROUTINE XKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XKERR2
  END INTERFACE
#define KERR2 XKERR2
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE QKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE QKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE QKSVD2
  END INTERFACE
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  REAL(KIND=REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
  INTEGER, ALLOCATABLE :: ISEED(:)
  REAL(KIND=10) :: G(2,2), U(2,2), V(2,2), S(2), T
  REAL(KIND=REAL128) :: QG(2,2), QU(2,2), QV(2,2), QS(2), E(5,2), F(2,16), Q
  INTEGER :: SSIZE, I, J, K, L, M, N, INFO
  CHARACTER(LEN=64) :: CLA
#include "grnd2t.F90"
1 FORMAT(A,ES30.21E4)
END PROGRAM XRND2T
