!>@brief \b YKSVD2X tests the YKSVD2 routine.
PROGRAM YKSVD2X
  IMPLICIT NONE
  EXTERNAL :: YKSVD2
  CALL YTEST(YKSVD2)
CONTAINS
  !>@brief \b YTEST calls KSVD2.
  !!
  !!@param KSVD2 is YKSVD2.
  SUBROUTINE YTEST(KSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 132
    EXTERNAL :: KSVD2
    CHARACTER(LEN=CLAL) :: CLA
    COMPLEX(KIND=REAL128) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=REAL128) :: S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    COMPLEX(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2)
    REAL(KIND=KX) :: SX(2,2)
#include "uksvd2.F90"
1   FORMAT(A,ES45.36E4)
2   FORMAT(A,'(',ES45.36E4,',',ES45.36E4,')')
3   FORMAT(A,I6)
  END SUBROUTINE YTEST
END PROGRAM YKSVD2X
