!>@brief YRAN generates a set of pseudorandom quadruple precision complex 2x2 matrices.
PROGRAM YRAN
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N
  INTEGER(KIND=c_int) :: U
  LOGICAL :: UPPER
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RAN_OPEN, PVN_RAN_CLOSE
  REAL(KIND=REAL128), EXTERNAL :: PVN_RAN_SAFE_Q
#define RAN_SAFE PVN_RAN_SAFE_Q
#include "hran.F90"
1 FORMAT(A,ES45.36E4)
END PROGRAM YRAN
