!>@brief \b ZKSVD2X tests the ZKSVD2 routine.
PROGRAM ZKSVD2X
  IMPLICIT NONE
  CALL ZTEST
CONTAINS
  !>@brief \b ZTEST calls ZKSVD2.
  SUBROUTINE ZTEST
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL64, REAL128
    IMPLICIT NONE
#define CR_HYPOT HYPOT
    INTERFACE
#ifdef NDEBUG
       PURE SUBROUTINE ZKSVD2(G, U, V, S, INFO)
#else
       SUBROUTINE ZKSVD2(G, U, V, S, INFO)
#endif
         USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
         IMPLICIT NONE
         COMPLEX(KIND=REAL64), INTENT(IN) :: G(2,2)
         COMPLEX(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2)
         REAL(KIND=REAL64), INTENT(OUT) :: S(2)
         INTEGER, INTENT(INOUT) :: INFO
       END SUBROUTINE ZKSVD2
    END INTERFACE
    INTEGER, PARAMETER :: KX = REAL128, IERR = -HUGE(0), CLAL = 132
    CHARACTER(LEN=CLAL) :: CLA
    COMPLEX(KIND=REAL64) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=REAL64) :: S(2)
    INTEGER :: I, INFO
    LOGICAL :: ONCE
    COMPLEX(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2)
    REAL(KIND=KX) :: SX(2,2)
#define KSVD2 ZKSVD2
#include "uksvd2.F90"
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,'(',ES25.17E3,',',ES25.17E3,')')
3   FORMAT(A,I5)
  END SUBROUTINE ZTEST
END PROGRAM ZKSVD2X
