!>@brief ZRAN generates a set of pseudorandom double precision complex 2x2 matrices.
PROGRAM ZRAN
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  CHARACTER(LEN=64) :: CLA
  INTEGER :: I, N
  INTEGER(KIND=c_int) :: U, P
  LOGICAL :: UPPER
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RAN_OPEN, PVN_RAN_CLOSE
  REAL(KIND=REAL64), EXTERNAL :: PVN_RAN_SAFE
#define RAN_SAFE PVN_RAN_SAFE
#include "hran.F90"
1 FORMAT(A,ES25.17E3)
END PROGRAM ZRAN
