!>@brief ZRND generates a set of pseudorandom double precision complex 2x2 matrices.
PROGRAM ZRND
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, ERROR_UNIT
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  INTEGER, ALLOCATABLE :: ISEED(:)
  REAL(KIND=REAL64), ALLOCATABLE :: H(:)
  CHARACTER(LEN=64) :: CLA
  INTEGER :: SSIZE, N, I
  LOGICAL :: UPPER
  REAL(KIND=REAL64) :: T
  INCLUDE 'hrnd.f90'
1 FORMAT(A,ES25.17E3)
END PROGRAM ZRND
