!>@brief ZRND2T tests a set of pseudorandom double precision complex 2x2 matrices.
PROGRAM ZRND2T
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128, ERROR_UNIT
  USE, INTRINSIC :: ISO_C_BINDING
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE ZKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE ZKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL64), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZKSVD2
  END INTERFACE
#define KSVD2 ZKSVD2
  INTERFACE
     PURE SUBROUTINE ZKERR2(G, U, V, S, E, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       IMPLICIT NONE
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL64), INTENT(IN) :: S(2)
       REAL(KIND=REAL128), INTENT(OUT) :: E(3)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZKERR2
  END INTERFACE
#define KERR2 ZKERR2
  INTERFACE
     SUBROUTINE STHALT(MSG)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: MSG
     END SUBROUTINE STHALT
  END INTERFACE
  INTEGER, PARAMETER :: D = REAL64
  INTEGER, ALLOCATABLE :: ISEED(:)
  COMPLEX(KIND=REAL64), ALLOCATABLE, TARGET :: G(:,:,:)
  COMPLEX(KIND=REAL64), ALLOCATABLE :: U(:,:,:), V(:,:,:)
  REAL(KIND=REAL64), ALLOCATABLE :: S(:,:)
  REAL(KIND=REAL128), ALLOCATABLE :: E(:,:)
  INTEGER, ALLOCATABLE :: INFO(:)
  REAL(KIND=REAL64), POINTER, CONTIGUOUS :: P(:,:,:)
  REAL(KIND=REAL128) :: F(6)
  REAL(KIND=REAL64) :: T
  INTEGER :: SSIZE, I, J, K, L, M, N
  CHARACTER(LEN=64) :: CLA
#include "hrnd2t.F90"
1 FORMAT(A,ES25.17E3)
END PROGRAM ZRND2T
