!>@brief \b CBROTR premultiplies the block-rows (P,Q) of G by R.
PURE SUBROUTINE CBROTR(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
#ifdef LAPACK
  INTERFACE
     PURE SUBROUTINE CGEMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: TRANSA, TRANSB
       INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
       COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: C(LDC,N)
     END SUBROUTINE CGEMM
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CLACPY(UPLO, M, N, A, LDA, B, LDB)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: UPLO
       INTEGER, INTENT(IN) :: M, N, LDA, LDB
       COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,N)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: B(LDB,N)
     END SUBROUTINE CLACPY
  END INTERFACE
#else
  INTERFACE
     PURE SUBROUTINE CMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: TRANSA, TRANSB
       INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
       COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: C(LDC,N)
     END SUBROUTINE CMM
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CCP(UPLO, M, N, A, LDA, B, LDB)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: UPLO
       INTEGER, INTENT(IN) :: M, N, LDA, LDB
       COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,N)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: B(LDB,N)
     END SUBROUTINE CCP
  END INTERFACE
#endif
  INTEGER, PARAMETER :: K = REAL32
  COMPLEX(KIND=K), PARAMETER :: ZERO = (0.0_K,0.0_K), ONE = (1.0_K,0.0_K)
  INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,M)
  COMPLEX(KIND=K), INTENT(IN) :: R(LDB,2*B)
  COMPLEX(KIND=K), INTENT(OUT) :: W(LDW,B)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, GI, GJ, RI, RJ
#ifdef LAPACK
#define GEMM CGEMM
#define LACPY CLACPY
#else
#define GEMM CMM
#define LACPY CCP
#endif
#include "gbrotr.F90"
END SUBROUTINE CBROTR
