!>@brief \b CCONJT sets G = G^H.
PURE SUBROUTINE CCONJT(N, G, LDG, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDG
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=K) :: T
  INTEGER :: I, J
#include "hconjt.F90"
END SUBROUTINE CCONJT
