!>@brief \b CCP copies A to B.
PURE SUBROUTINE CCP(UPLO, M, N, A, LDA, B, LDB)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  CHARACTER, INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: M, N, LDA, LDB
  COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,N)
  COMPLEX(KIND=REAL32), INTENT(OUT) :: B(LDB,N)

  INTEGER :: I, J
#include "gcp.F90"
END SUBROUTINE CCP
