PURE FUNCTION CFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_CFMA(DR, DI, AR, AI, BR, BI, CR, CI)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       IMPLICIT NONE
       REAL(KIND=c_float), INTENT(OUT) :: DR, DI
       REAL(KIND=c_float), INTENT(IN) :: AR, AI, BR, BI, CR, CI
     END SUBROUTINE PVN_CFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  COMPLEX(KIND=K), INTENT(IN) :: A, B, C
  COMPLEX(KIND=K) :: CFMA
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI, DR, DI
#define KFMA CFMA
#define PFMA PVN_CFMA
#include "hfma.F90"
END FUNCTION CFMA
