FUNCTION CFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  COMPLEX(KIND=K), INTENT(IN) :: A, B, C
  COMPLEX(KIND=K) :: CFMA
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI, DR, DI
  EXTERNAL :: PVN_CFMA
#define KMA CFMA
#define PMA PVN_CFMA
#include "hfma.F90"
END FUNCTION CFMA
