!>@brief \b CLANGO computes an approximation of the norm of G.
SUBROUTINE CLANGO(N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  INTEGER, INTENT(IN) :: N, LDG
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(N,LDG)
  REAL(KIND=REAL32), INTENT(OUT) :: S
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=REAL32) :: SC, SM
  INTEGER :: I, J
#include "hlango.F90"
END SUBROUTINE CLANGO
