!>@brief \b CMM computes C = ALPHA * A * B + BETA * C.
PURE SUBROUTINE CMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CMUL(A, B)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: A, B
       COMPLEX(KIND=REAL32) :: CMUL
     END FUNCTION CMUL
  END INTERFACE
  INTERFACE
     PURE FUNCTION CFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: A, B, C
       COMPLEX(KIND=REAL32) :: CFMA
     END FUNCTION CFMA
  END INTERFACE
  COMPLEX(KIND=REAL32), PARAMETER :: ZERO = (0.0_REAL32,0.0_REAL32), ONE = (1.0_REAL32,0.0_REAL32)
  CHARACTER, INTENT(IN) :: TRANSA, TRANSB
  INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
  COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
  COMPLEX(KIND=REAL32), INTENT(INOUT) :: C(LDC,N)

  INTEGER :: I, J, L
#define KMUL CMUL
#define KFMA CFMA
#include "hmm.F90"
END SUBROUTINE CMM
