PURE FUNCTION CMUL(A, B)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_CMUL(CR, CI, AR, AI, BR, BI)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       IMPLICIT NONE
       REAL(KIND=c_float), INTENT(OUT) :: CR, CI
       REAL(KIND=c_float), INTENT(IN) :: AR, AI, BR, BI
     END SUBROUTINE PVN_CMUL
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  COMPLEX(KIND=K), INTENT(IN) :: A, B
  COMPLEX(KIND=K) :: CMUL
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI
#define KMUL CMUL
#define PMUL PVN_CMUL
#include "hmul.F90"
END FUNCTION CMUL
