FUNCTION CMUL(A, B)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  COMPLEX(KIND=K), INTENT(IN) :: A, B
  COMPLEX(KIND=K) :: CMUL
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI
  EXTERNAL :: PVN_CMUL
#define KMUL CMUL
#define PMUL PVN_CMUL
#include "hmul.F90"
END FUNCTION CMUL
