!>@brief \b CROTCA postmultiplies the columns (p,q) of G by W using an imperfect emulation of an accurate a*b+c*d operation.
SUBROUTINE CROTCA(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32, L = REAL64
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
#define VL 8
  COMPLEX(KIND=K) :: X(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: X
  COMPLEX(KIND=K) :: Y(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: Y
  COMPLEX(KIND=L) :: XX(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: XX
  COMPLEX(KIND=L) :: YY(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: YY
  COMPLEX(KIND=L) :: WW(2,2)
  !DIR$ ATTRIBUTES ALIGN: 64:: WW
  INTEGER :: I, J
#define HL 4
#include "hrotca.F90"
END SUBROUTINE CROTCA
