!>@brief \b CROTCA postmultiplies the columns (p,q) of G by W using an imperfect emulation of an accurate a*b+c*d operation.
PURE SUBROUTINE CROTCA(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32, L = REAL64
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  IF (MOD(M, 8) .EQ. 0) THEN
     CALL CROTCA8(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(M, 4) .EQ. 0) THEN
     CALL CROTCA4(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(M, 2) .EQ. 0) THEN
     CALL CROTCA2(M, N, G, LDG, P, Q, W, INFO)
  ELSE ! error
     INFO = -1
  END IF
CONTAINS
  PURE SUBROUTINE CROTCA2(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
    COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 2
#undef HL
#define HL 1
#include "hrotca.F90"
  END SUBROUTINE CROTCA2
  PURE SUBROUTINE CROTCA4(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
    COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 4
#undef HL
#define HL 2
#include "hrotca.F90"
  END SUBROUTINE CROTCA4
  PURE SUBROUTINE CROTCA8(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
    COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 8
#undef HL
#define HL 4
#include "hrotca.F90"
  END SUBROUTINE CROTCA8
END SUBROUTINE CROTCA
