!>@brief \b CROTR premultiplies the rows (p,q) of G by W.
PURE SUBROUTINE CROTR(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=REAL32) :: X, Y
  INTEGER :: J
  INCLUDE 'grotr.f90'
END SUBROUTINE CROTR
