!>@brief \b CROTC postmultiplies the columns \f$(p,q)\f$ of \f$G\f$ by \f$W\f$.
PURE SUBROUTINE CROTC(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=REAL32) :: X, Y
  INTEGER :: I
  INCLUDE 'grotc.f90'
END SUBROUTINE CROTC
