!>@brief \b CSCALG scales \f$G\f$ by \f$2^S\f$.
SUBROUTINE CSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, N, LDG, S
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
  INCLUDE 'hscalg.f90'
END SUBROUTINE CSCALG
