!>@brief \b DBROTR premultiplies the block-rows (P,Q) of G by R.
PURE SUBROUTINE DBROTR(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE DMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: TRANSA, TRANSB
       INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
       REAL(KIND=REAL64), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
       REAL(KIND=REAL64), INTENT(INOUT) :: C(LDC,N)
     END SUBROUTINE DMM
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DCP(UPLO, M, N, A, LDA, B, LDB)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: UPLO
       INTEGER, INTENT(IN) :: M, N, LDA, LDB
       REAL(KIND=REAL64), INTENT(IN) :: A(LDA,N)
       REAL(KIND=REAL64), INTENT(OUT) :: B(LDB,N)
     END SUBROUTINE DCP
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,M)
  REAL(KIND=K), INTENT(IN) :: R(LDB,2*B)
  REAL(KIND=K), INTENT(OUT) :: W(LDW,B)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, GI, GJ, RI, RJ
!   EXTERNAL :: DGEMM, DLACPY
! #define GEMM DGEMM
! #define LACPY DLACPY
#define GEMM DMM
#define LACPY DCP
#include "gbrotr.F90"
END SUBROUTINE DBROTR
