!>@brief \b DCONJT sets G = G^T.
PURE SUBROUTINE DCONJT(N, G, LDG, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, LDG
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: T
  INTEGER :: I, J
#include "gconjt.F90"
END SUBROUTINE DCONJT
