!>@brief \b DCP copies A to B.
PURE SUBROUTINE DCP(UPLO, M, N, A, LDA, B, LDB)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  CHARACTER, INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: M, N, LDA, LDB
  REAL(KIND=REAL64), INTENT(IN) :: A(LDA,N)
  REAL(KIND=REAL64), INTENT(OUT) :: B(LDB,N)

  INTEGER :: I, J
#include "gcp.F90"
END SUBROUTINE DCP
