!>@brief \b DLANGO computes an approximation of the norm of G.
SUBROUTINE DLANGO(N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  INTEGER, INTENT(IN) :: N, LDG
  REAL(KIND=REAL64), INTENT(IN) :: G(N,LDG)
  REAL(KIND=REAL64), INTENT(OUT) :: S
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=REAL64) :: SC
  INTEGER :: I, J
#include "glango.F90"
END SUBROUTINE DLANGO
