!>@brief \b DMM computes C = ALPHA * A * B + BETA * C.
PURE SUBROUTINE DMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, ONE = 1.0_REAL64
  CHARACTER, INTENT(IN) :: TRANSA, TRANSB
  INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
  REAL(KIND=REAL64), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
  REAL(KIND=REAL64), INTENT(INOUT) :: C(LDC,N)

  INTEGER :: I, J, L
#include "gmm.F90"
END SUBROUTINE DMM
