!>@brief \b DOSUM4 sums four norms in double precision.
PURE SUBROUTINE DOSUM4(W1, W2, W3, W4, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE

#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif

  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  REAL(KIND=REAL64), INTENT(IN) :: W1, W2, W3, W4
  REAL(KIND=REAL64), INTENT(OUT) :: W
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL64) :: T(4)
  INTEGER :: I, J, K
#include "gosum4.F90"
END SUBROUTINE DOSUM4
