!>@brief \b DROTRA premultiplies the rows (p,q) of G by W using an emulation of an accurate a*b+c*d operation.
PURE SUBROUTINE DROTRA(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64, L = REAL128
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  IF (MOD(N, 8) .EQ. 0) THEN
     CALL DROTRA8(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 4) .EQ. 0) THEN
     CALL DROTRA4(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 2) .EQ. 0) THEN
     CALL DROTRA2(M, N, G, LDG, P, Q, W, INFO)
  ELSE ! error
     INFO = -2
  END IF
CONTAINS
  PURE SUBROUTINE DROTRA2(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL64, L = REAL128
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 2
#undef HL
#define HL 1
#include "grotra.F90"
  END SUBROUTINE DROTRA2
  PURE SUBROUTINE DROTRA4(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL64, L = REAL128
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 4
#undef HL
#define HL 2
#include "grotra.F90"
  END SUBROUTINE DROTRA4
  PURE SUBROUTINE DROTRA8(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL64, L = REAL128
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 8
#undef HL
#define HL 4
#include "grotra.F90"
  END SUBROUTINE DROTRA8
END SUBROUTINE DROTRA
