FUNCTION DRSAFE(U)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(REAL64) :: DRSAFE, RMIN, RMAX, R, A
  INCLUDE 'grsafe.f90'
  DRSAFE = R
END FUNCTION DRSAFE
