!>@brief \b DSCALG scales \f$G\f$ by \f$2^S\f$.
SUBROUTINE DSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, S
  REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
  INCLUDE 'gscalg.f90'
END SUBROUTINE DSCALG
