../lib/$(PLAT)/libfaux.a: $(OBJS_FAUX) $(MKFS) faux/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_FAUX)

../obj/$(PLAT)/sthalt.o: faux/sthalt.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/sthalt.F90

../obj/$(PLAT)/slango.o: faux/slango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/slango.f90

../obj/$(PLAT)/clango.o: faux/clango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/clango.f90

../obj/$(PLAT)/dlango.o: faux/dlango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/dlango.f90

../obj/$(PLAT)/zlango.o: faux/zlango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zlango.f90

../obj/$(PLAT)/qlango.o: faux/qlango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qlango.f90

../obj/$(PLAT)/ylango.o: faux/ylango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/ylango.f90

../obj/$(PLAT)/xlango.o: faux/xlango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xlango.f90

../obj/$(PLAT)/wlango.o: faux/wlango.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wlango.f90

../obj/$(PLAT)/srotc.o: faux/srotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/srotc.f90

../obj/$(PLAT)/crotc.o: faux/crotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/crotc.f90

../obj/$(PLAT)/drotc.o: faux/drotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/drotc.f90

../obj/$(PLAT)/zrotc.o: faux/zrotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zrotc.f90

../obj/$(PLAT)/qrotc.o: faux/qrotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qrotc.f90

../obj/$(PLAT)/yrotc.o: faux/yrotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/yrotc.f90

../obj/$(PLAT)/xrotc.o: faux/xrotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xrotc.f90

../obj/$(PLAT)/wrotc.o: faux/wrotc.f90 faux/grotc.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wrotc.f90

../obj/$(PLAT)/srotr.o: faux/srotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/srotr.f90

../obj/$(PLAT)/crotr.o: faux/crotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/crotr.f90

../obj/$(PLAT)/drotr.o: faux/drotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/drotr.f90

../obj/$(PLAT)/zrotr.o: faux/zrotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zrotr.f90

../obj/$(PLAT)/qrotr.o: faux/qrotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qrotr.f90

../obj/$(PLAT)/yrotr.o: faux/yrotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/yrotr.f90

../obj/$(PLAT)/xrotr.o: faux/xrotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xrotr.f90

../obj/$(PLAT)/wrotr.o: faux/wrotr.f90 faux/grotr.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wrotr.f90

../obj/$(PLAT)/jstep.o: faux/jstep.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/jstep.f90

../obj/$(PLAT)/jsweep.o: faux/jsweep.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/jsweep.f90
