../lib/$(PLAT)/libfaux.a: $(OBJS_FAUX) $(MKFS) faux/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_FAUX)

../obj/$(PLAT)/sthalt.$(OXT): faux/sthalt.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/sthalt.F90

../obj/$(PLAT)/cmul.$(OXT): faux/cmul.F90 faux/hmul.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/cmul.F90

../obj/$(PLAT)/zmul.$(OXT): faux/zmul.F90 faux/hmul.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zmul.F90

../obj/$(PLAT)/cfma.$(OXT): faux/cfma.F90 faux/hfma.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/cfma.F90

../obj/$(PLAT)/zfma.$(OXT): faux/zfma.F90 faux/hfma.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zfma.F90

../obj/$(PLAT)/slango.$(OXT): faux/slango.F90 faux/glango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/slango.F90

../obj/$(PLAT)/clango.$(OXT): faux/clango.F90 faux/hlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/clango.F90

../obj/$(PLAT)/dlango.$(OXT): faux/dlango.F90 faux/glango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/dlango.F90

../obj/$(PLAT)/zlango.$(OXT): faux/zlango.F90 faux/hlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zlango.F90

../obj/$(PLAT)/srotc.$(OXT): faux/srotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/srotc.F90

../obj/$(PLAT)/srotca.$(OXT): faux/srotca.F90 faux/grotca.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/srotca.F90

../obj/$(PLAT)/crotc.$(OXT): faux/crotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/crotc.F90

../obj/$(PLAT)/crotca.$(OXT): faux/crotca.F90 faux/hrotca.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/crotca.F90

../obj/$(PLAT)/drotc.$(OXT): faux/drotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/drotc.F90

../obj/$(PLAT)/drotca.$(OXT): faux/drotca.F90 $(MKFS) faux/grotca.F90 faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/drotca.F90

../obj/$(PLAT)/drotcx.$(OXT): faux/drotcx.F90 $(MKFS) faux/grotca.F90 faux/GNUmakefile
	cd ../obj/$(PLAT) && $(GFC) $(GFCFLAGS) $(CFLG) ../../../src/faux/drotcx.F90

../obj/$(PLAT)/zrotc.$(OXT): faux/zrotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zrotc.F90

../obj/$(PLAT)/zrotca.$(OXT): faux/zrotca.F90 $(MKFS) faux/hrotca.F90 faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zrotca.F90

../obj/$(PLAT)/zrotcx.$(OXT): faux/zrotcx.F90 $(MKFS) faux/hrotca.F90 faux/GNUmakefile
	cd ../obj/$(PLAT) && $(GFC) $(GFCFLAGS) $(CFLG) ../../../src/faux/zrotcx.F90

../obj/$(PLAT)/srotr.$(OXT): faux/srotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/srotr.F90

../obj/$(PLAT)/srotra.$(OXT): faux/srotra.F90 faux/grotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/srotra.F90

../obj/$(PLAT)/crotr.$(OXT): faux/crotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/crotr.F90

../obj/$(PLAT)/crotra.$(OXT): faux/crotra.F90 faux/hrotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/crotra.F90

../obj/$(PLAT)/drotr.$(OXT): faux/drotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/drotr.F90

../obj/$(PLAT)/drotra.$(OXT): faux/drotra.F90 faux/grotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/drotra.F90

../obj/$(PLAT)/drotrx.$(OXT): faux/drotrx.F90 faux/grotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(GFC) $(GFCFLAGS) $(CFLG) ../../../src/faux/drotrx.F90

../obj/$(PLAT)/zrotr.$(OXT): faux/zrotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zrotr.F90

../obj/$(PLAT)/zrotra.$(OXT): faux/zrotra.F90 faux/hrotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zrotra.F90

../obj/$(PLAT)/zrotrx.$(OXT): faux/zrotrx.F90 faux/hrotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(GFC) $(GFCFLAGS) $(CFLG) ../../../src/faux/zrotrx.F90

../obj/$(PLAT)/sscalg.$(OXT): faux/sscalg.F90 faux/gscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/sscalg.F90

../obj/$(PLAT)/cscalg.$(OXT): faux/cscalg.F90 faux/hscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/cscalg.F90

../obj/$(PLAT)/dscalg.$(OXT): faux/dscalg.F90 faux/gscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/dscalg.F90

../obj/$(PLAT)/zscalg.$(OXT): faux/zscalg.F90 faux/hscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/zscalg.F90

../obj/$(PLAT)/initrc.$(OXT): faux/initrc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/initrc.F90

../obj/$(PLAT)/jstep.$(OXT): faux/jstep.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/jstep.F90

../obj/$(PLAT)/jsweep.$(OXT): faux/jsweep.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/jsweep.F90
