../lib/$(PLAT)/libfaux.a: $(OBJS_FAUX) $(OBJS_CRF_MATH) $(OBJS_CRD_MATH) $(MKFS) faux/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_FAUX) $(OBJS_CRF_MATH) $(OBJS_CRD_MATH)

../obj/$(PLAT)/sthalt.o: faux/sthalt.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/sthalt.F90

../obj/$(PLAT)/slango.o: faux/slango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/slango.F90

../obj/$(PLAT)/clango.o: faux/clango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/clango.F90

../obj/$(PLAT)/dlango.o: faux/dlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/dlango.F90

../obj/$(PLAT)/zlango.o: faux/zlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zlango.F90

../obj/$(PLAT)/qlango.o: faux/qlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qlango.F90

../obj/$(PLAT)/ylango.o: faux/ylango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/ylango.F90

../obj/$(PLAT)/xlango.o: faux/xlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xlango.F90

../obj/$(PLAT)/wlango.o: faux/wlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wlango.F90

../obj/$(PLAT)/srotc.o: faux/srotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/srotc.F90

../obj/$(PLAT)/crotc.o: faux/crotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/crotc.F90

../obj/$(PLAT)/drotc.o: faux/drotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/drotc.F90

../obj/$(PLAT)/zrotc.o: faux/zrotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zrotc.F90

../obj/$(PLAT)/qrotc.o: faux/qrotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qrotc.F90

../obj/$(PLAT)/yrotc.o: faux/yrotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/yrotc.F90

../obj/$(PLAT)/xrotc.o: faux/xrotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xrotc.F90

../obj/$(PLAT)/wrotc.o: faux/wrotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wrotc.F90

../obj/$(PLAT)/srotr.o: faux/srotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/srotr.F90

../obj/$(PLAT)/crotr.o: faux/crotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/crotr.F90

../obj/$(PLAT)/drotr.o: faux/drotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/drotr.F90

../obj/$(PLAT)/zrotr.o: faux/zrotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zrotr.F90

../obj/$(PLAT)/qrotr.o: faux/qrotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qrotr.F90

../obj/$(PLAT)/yrotr.o: faux/yrotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/yrotr.F90

../obj/$(PLAT)/xrotr.o: faux/xrotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xrotr.F90

../obj/$(PLAT)/wrotr.o: faux/wrotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wrotr.F90

../obj/$(PLAT)/sscalg.o: faux/sscalg.f90 faux/gscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/sscalg.f90

../obj/$(PLAT)/cscalg.o: faux/cscalg.f90 faux/hscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/cscalg.f90

../obj/$(PLAT)/dscalg.o: faux/dscalg.f90 faux/gscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/dscalg.f90

../obj/$(PLAT)/zscalg.o: faux/zscalg.f90 faux/hscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/zscalg.f90

../obj/$(PLAT)/qscalg.o: faux/qscalg.f90 faux/gscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/qscalg.f90

../obj/$(PLAT)/yscalg.o: faux/yscalg.f90 faux/hscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/yscalg.f90

../obj/$(PLAT)/xscalg.o: faux/xscalg.f90 faux/gscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/xscalg.f90

../obj/$(PLAT)/wscalg.o: faux/wscalg.f90 faux/hscalg.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/wscalg.f90

../obj/$(PLAT)/jstep.o: faux/jstep.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/jstep.f90

../obj/$(PLAT)/jsweep.o: faux/jsweep.f90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/faux/jsweep.f90
