..\lib\$(PLAT)\faux.lib: $(OBJS_FAUX) $(MKFS) faux\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_FAUX)

..\obj\$(PLAT)\sthalt.obj: faux\sthalt.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\sthalt.F90

..\obj\$(PLAT)\slango.obj: faux\slango.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\slango.F90

..\obj\$(PLAT)\clango.obj: faux\clango.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\clango.F90

..\obj\$(PLAT)\dlango.obj: faux\dlango.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\dlango.F90

..\obj\$(PLAT)\zlango.obj: faux\zlango.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\zlango.F90

..\obj\$(PLAT)\qlango.obj: faux\qlango.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\qlango.F90

..\obj\$(PLAT)\ylango.obj: faux\ylango.F90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\ylango.F90

..\obj\$(PLAT)\srotc.obj: faux\srotc.f90 $(MKFS) faux\grotc.f90 faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\srotc.f90

..\obj\$(PLAT)\crotc.obj: faux\crotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\crotc.f90

..\obj\$(PLAT)\drotc.obj: faux\drotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\drotc.f90

..\obj\$(PLAT)\zrotc.obj: faux\zrotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\zrotc.f90

..\obj\$(PLAT)\qrotc.obj: faux\qrotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\qrotc.f90

..\obj\$(PLAT)\yrotc.obj: faux\yrotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\yrotc.f90

..\obj\$(PLAT)\srotr.obj: faux\srotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\srotr.f90

..\obj\$(PLAT)\crotr.obj: faux\crotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\crotr.f90

..\obj\$(PLAT)\drotr.obj: faux\drotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\drotr.f90

..\obj\$(PLAT)\zrotr.obj: faux\zrotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\zrotr.f90

..\obj\$(PLAT)\qrotr.obj: faux\qrotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\qrotr.f90

..\obj\$(PLAT)\yrotr.obj: faux\yrotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\yrotr.f90

..\obj\$(PLAT)\sscalg.obj: faux\sscalg.f90 faux\gscalg.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\sscalg.f90

..\obj\$(PLAT)\cscalg.obj: faux\cscalg.f90 faux\hscalg.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\cscalg.f90

..\obj\$(PLAT)\dscalg.obj: faux\dscalg.f90 faux\gscalg.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\dscalg.f90

..\obj\$(PLAT)\zscalg.obj: faux\zscalg.f90 faux\hscalg.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\zscalg.f90

..\obj\$(PLAT)\qscalg.obj: faux\qscalg.f90 faux\gscalg.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\qscalg.f90

..\obj\$(PLAT)\yscalg.obj: faux\yscalg.f90 faux\hscalg.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\yscalg.f90

..\obj\$(PLAT)\jstep.obj: faux\jstep.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\jstep.f90

..\obj\$(PLAT)\jsweep.obj: faux\jsweep.f90 $(MKFS) faux\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\jsweep.f90
