..\lib\$(PLAT)\faux.lib: $(OBJS_FAUX) $(MKFS) faux\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_FAUX)

..\obj\$(PLAT)\sthalt.obj: faux\sthalt.F90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\sthalt.F90 && popd

..\obj\$(PLAT)\slango.obj: faux\slango.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\slango.f90 && popd

..\obj\$(PLAT)\clango.obj: faux\clango.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\clango.f90 && popd

..\obj\$(PLAT)\dlango.obj: faux\dlango.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\dlango.f90 && popd

..\obj\$(PLAT)\zlango.obj: faux\zlango.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\zlango.f90 && popd

..\obj\$(PLAT)\qlango.obj: faux\qlango.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\qlango.f90 && popd

..\obj\$(PLAT)\ylango.obj: faux\ylango.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\ylango.f90 && popd

..\obj\$(PLAT)\sosum4.obj: faux\sosum4.F90 faux\gosum4.F90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\sosum4.F90 && popd

..\obj\$(PLAT)\dosum4.obj: faux\dosum4.F90 faux\gosum4.F90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\faux\dosum4.F90 && popd

..\obj\$(PLAT)\srotc.obj: faux\srotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\srotc.f90 && popd

..\obj\$(PLAT)\crotc.obj: faux\crotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\crotc.f90 && popd

..\obj\$(PLAT)\drotc.obj: faux\drotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\drotc.f90 && popd

..\obj\$(PLAT)\zrotc.obj: faux\zrotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\zrotc.f90 && popd

..\obj\$(PLAT)\qrotc.obj: faux\qrotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\qrotc.f90 && popd

..\obj\$(PLAT)\yrotc.obj: faux\yrotc.f90 faux\grotc.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\yrotc.f90 && popd

..\obj\$(PLAT)\srotr.obj: faux\srotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\srotr.f90 && popd

..\obj\$(PLAT)\crotr.obj: faux\crotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\crotr.f90 && popd

..\obj\$(PLAT)\drotr.obj: faux\drotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\drotr.f90 && popd

..\obj\$(PLAT)\zrotr.obj: faux\zrotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\zrotr.f90 && popd

..\obj\$(PLAT)\qrotr.obj: faux\qrotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\qrotr.f90 && popd

..\obj\$(PLAT)\yrotr.obj: faux\yrotr.f90 faux\grotr.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\yrotr.f90 && popd

..\obj\$(PLAT)\jstep.obj: faux\jstep.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\jstep.f90 && popd

..\obj\$(PLAT)\jsweep.obj: faux\jsweep.f90 $(MKFS) faux\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\faux\jsweep.f90 && popd
