!>@brief \b QPSUM4 sums four non-negative weights in quadruple precision.
PURE SUBROUTINE QPSUM4(W1, W2, W3, W4, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128
  REAL(KIND=REAL128), INTENT(IN) :: W1, W2, W3, W4
  REAL(KIND=REAL128), INTENT(OUT) :: W
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL128) :: T(4)
  INTEGER :: I, J, K
  INCLUDE 'gpsum4.f90'
END SUBROUTINE QPSUM4
