FUNCTION QRSAFE(U)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(REAL128) :: QRSAFE, RMIN, RMAX, R, A
  INCLUDE 'grsafe.f90'
  QRSAFE = R
END FUNCTION QRSAFE
