!>@brief \b QSCALG scales G by 2^S.
SUBROUTINE QSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, S
  REAL(KIND=REAL128), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
#include "gscalg.F90"
END SUBROUTINE QSCALG
