!>@brief \b QSCALG scales \f$G\f$ by \f$2^S\f$.
SUBROUTINE QSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, S
  REAL(KIND=REAL128), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
  INCLUDE 'gscalg.f90'
END SUBROUTINE QSCALG
