!>@brief \b SBROTR premultiplies the block-rows (P,Q) of G by R.
SUBROUTINE SBROTR(N, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: N, B, LDG, P, Q, LDB, LDW
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(IN) :: R(LDB,2*B)
  REAL(KIND=K), INTENT(OUT) :: W(LDW,B)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, GI, GJ, RI, RJ
  EXTERNAL :: SGEMM, SLACPY
#define GEMM SGEMM
#define LACPY SLACPY
#include "gbrotr.F90"
END SUBROUTINE SBROTR
