!>@brief \b SCONJT sets G = G^T.
PURE SUBROUTINE SCONJT(N, G, LDG, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDG
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: T
  INTEGER :: I, J
#include "gconjt.F90"
END SUBROUTINE SCONJT
