!>@brief \b SCP copies A to B.
PURE SUBROUTINE SCP(UPLO, M, N, A, LDA, B, LDB)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  CHARACTER, INTENT(IN) :: UPLO
  INTEGER, INTENT(IN) :: M, N, LDA, LDB
  REAL(KIND=REAL32), INTENT(IN) :: A(LDA,N)
  REAL(KIND=REAL32), INTENT(OUT) :: B(LDB,N)

  INTEGER :: I, J
#include "gcp.F90"
END SUBROUTINE SCP
