!>@brief \b SLANGO computes an approximation of the norm of G.
SUBROUTINE SLANGO(N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE

  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32, ONE = 1.0_REAL32
  INTEGER, INTENT(IN) :: N, LDG
  REAL(KIND=REAL32), INTENT(IN) :: G(N,LDG)
  REAL(KIND=REAL32), INTENT(OUT) :: S
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=REAL32) :: SC
  INTEGER :: I, J

  S = ZERO
  I = INFO
  INFO = 0
  IF (LDG .LT. N) INFO = -3
  IF (N .LT. 0) INFO = -1
  IF (INFO .NE. 0) RETURN

  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I,J,SC) SHARED(G,N) REDUCTION(MAX:S,INFO) IF(I .NE. 0)
  DO J = 1, N
     DO I = 1, N
        SC = ABS(G(I,J))
        IF (.NOT. (SC .LE. HUGE(SC))) THEN
           INFO = MAX(INFO, (J - 1) * N + I)
        ELSE ! SC finite
           INFO = MAX(INFO, 0)
        END IF
        S = MAX(S, SC)
     END DO
  END DO
  !$OMP END PARALLEL DO
END SUBROUTINE SLANGO
