!>@brief \b SMM computes C = ALPHA * A * B + BETA * C.
PURE SUBROUTINE SMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32, ONE = 1.0_REAL32
  CHARACTER, INTENT(IN) :: TRANSA, TRANSB
  INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
  REAL(KIND=REAL32), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
  REAL(KIND=REAL32), INTENT(INOUT) :: C(LDC,N)

  INTEGER :: I, J, L
#include "gmm.F90"
END SUBROUTINE SMM
