!>@brief \b SOSUM4 sums four norms in single precision.
PURE SUBROUTINE SOSUM4(W1, W2, W3, W4, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE

#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif

  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  REAL(KIND=REAL32), INTENT(IN) :: W1, W2, W3, W4
  REAL(KIND=REAL32), INTENT(OUT) :: W
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL32) :: T(4)
  INTEGER :: I, J, K
#include "gosum4.F90"
END SUBROUTINE SOSUM4
