!>@brief \b DROTR premultiplies the rows (p,q) of G by W.
PURE SUBROUTINE SROTR(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  IF (MOD(N, 16) .EQ. 0) THEN
     CALL SROTR16(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 8) .EQ. 0) THEN
     CALL SROTR8(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 4) .EQ. 0) THEN
     CALL SROTR4(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 2) .EQ. 0) THEN
     CALL SROTR2(M, N, G, LDG, P, Q, W, INFO)
  ELSE ! the general case
     CALL SROTR1(M, N, G, LDG, P, Q, W, INFO)
  END IF
CONTAINS
  PURE SUBROUTINE SROTR1(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 1
#include "grotr.F90"
  END SUBROUTINE SROTR1
  PURE SUBROUTINE SROTR2(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 2
#include "grotr.F90"
  END SUBROUTINE SROTR2
  PURE SUBROUTINE SROTR4(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 4
#include "grotr.F90"
  END SUBROUTINE SROTR4
  PURE SUBROUTINE SROTR8(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 8
#include "grotr.F90"
  END SUBROUTINE SROTR8
  PURE SUBROUTINE SROTR16(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 16
#include "grotr.F90"
  END SUBROUTINE SROTR16
END SUBROUTINE SROTR
