!>@brief \b SROTCA postmultiplies the columns (p,q) of G by W using an emulation of an accurate a*b+c*d operation.
PURE SUBROUTINE SROTCA(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32, L = REAL64
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  IF (MOD(M, 16) .EQ. 0) THEN
     CALL SROTCA16(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(M, 8) .EQ. 0) THEN
     CALL SROTCA8(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(M, 4) .EQ. 0) THEN
     CALL SROTCA4(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(M, 2) .EQ. 0) THEN
     CALL SROTCA2(M, N, G, LDG, P, Q, W, INFO)
  ELSE ! error
     INFO = -1
  END IF
CONTAINS
  PURE SUBROUTINE SROTCA2(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 2
#undef HL
#define HL 1
#include "grotca.F90"
  END SUBROUTINE SROTCA2
  PURE SUBROUTINE SROTCA4(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 4
#undef HL
#define HL 2
#include "grotca.F90"
  END SUBROUTINE SROTCA4
  PURE SUBROUTINE SROTCA8(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 8
#undef HL
#define HL 4
#include "grotca.F90"
  END SUBROUTINE SROTCA8
  PURE SUBROUTINE SROTCA16(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 16
#undef HL
#define HL 8
#include "grotca.F90"
  END SUBROUTINE SROTCA16
END SUBROUTINE SROTCA
