!>@brief \b SROTRA premultiplies the rows (p,q) of G by W using an emulation of an accurate a*b+c*d operation.
PURE SUBROUTINE SROTRA(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  IF (MOD(N, 16) .EQ. 0) THEN
     CALL SROTRA16(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 8) .EQ. 0) THEN
     CALL SROTRA8(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 4) .EQ. 0) THEN
     CALL SROTRA4(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(N, 2) .EQ. 0) THEN
     CALL SROTRA2(M, N, G, LDG, P, Q, W, INFO)
  ELSE ! error
     INFO = -2
  END IF
CONTAINS
  PURE SUBROUTINE SROTRA2(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 2
#undef HL
#define HL 1
#include "grotra.F90"
  END SUBROUTINE SROTRA2
  PURE SUBROUTINE SROTRA4(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 4
#undef HL
#define HL 2
#include "grotra.F90"
  END SUBROUTINE SROTRA4
  PURE SUBROUTINE SROTRA8(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 8
#undef HL
#define HL 4
#include "grotra.F90"
  END SUBROUTINE SROTRA8
  PURE SUBROUTINE SROTRA16(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL32, L = REAL64
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
    REAL(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 16
#undef HL
#define HL 8
#include "grotra.F90"
  END SUBROUTINE SROTRA16
END SUBROUTINE SROTRA
