!>@brief \b SROTC postmultiplies the columns (p,q) of G by W.
SUBROUTINE SROTC(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(OUT) :: INFO
#define VL 16
  REAL(KIND=K) :: X(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: X
  REAL(KIND=K) :: Y(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: Y
  REAL(KIND=K) :: Z(2,2)
  !DIR$ ATTRIBUTES ALIGN: 64:: Z
  INTEGER :: I, J
#include "grotc.F90"
END SUBROUTINE SROTC
