FUNCTION SRSAFE(U)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(REAL32) :: SRSAFE, RMIN, RMAX, R, A
  INCLUDE 'grsafe.f90'
  SRSAFE = R
END FUNCTION SRSAFE
