!>@brief \b STHALT writes MSG and the stack trace to ERROR_UNIT and stops the program.
SUBROUTINE STHALT(MSG)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
#else
#ifdef __INTEL_COMPILER
  USE IFCORE, ONLY: TRACEBACKQQ
#endif
#endif
#ifdef _OPENMP
  USE OMP_LIB, ONLY: OMP_GET_THREAD_NUM
#endif
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  CHARACTER(LEN=6) :: THR
#ifdef _OPENMP
  WRITE (THR,'(A,I3,A)') '[', OMP_GET_THREAD_NUM(), '] '
#else
  THR = '[!!!] '
#endif
#ifdef __GFORTRAN__
  WRITE (ERROR_UNIT,'(A)') NEW_LINE(MSG)//THR//TRIM(MSG)
  FLUSH(ERROR_UNIT)
  CALL BACKTRACE
#else
#ifdef __INTEL_COMPILER
  CALL TRACEBACKQQ(NEW_LINE(MSG)//THR//TRIM(MSG), -1_4)
#else
  CALL XL__TRBK
#endif
#endif
  STOP
END SUBROUTINE STHALT
