FUNCTION WMUL(A, B)
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = 10
  COMPLEX(KIND=K), INTENT(IN) :: A, B
  COMPLEX(KIND=K) :: WMUL
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI
  EXTERNAL :: PVN_WMUL
#define KMUL WMUL
#define PMUL PVN_WMUL
#include "hmul.F90"
END FUNCTION WMUL
