FUNCTION WMUL(A, B)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = c_long_double
  COMPLEX(KIND=K), INTENT(IN) :: A, B
  COMPLEX(KIND=K) :: WMUL
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI
  EXTERNAL :: PVN_WMUL
#define KMUL WMUL
#define PMUL PVN_WMUL
#include "hmul.F90"
END FUNCTION WMUL
