!>@brief \b WROTR premultiplies the rows (p,q) of G by W.
SUBROUTINE WROTR(M, N, G, LDG, P, Q, W, INFO)
  IMPLICIT NONE
#define CR_HYPOT HYPOT
  INTERFACE
     FUNCTION WMUL(A, B)
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: A, B
       COMPLEX(KIND=10) :: WMUL
     END FUNCTION WMUL
  END INTERFACE
  INTERFACE
     FUNCTION WFMA(A, B, C)
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: A, B, C
       COMPLEX(KIND=10) :: WFMA
     END FUNCTION WFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = 10
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: X, Y
  INTEGER :: I, J
#define MUL WMUL
#define FMA WFMA
#include "hrotr.F90"
END SUBROUTINE WROTR
