!>@brief \b WROTC postmultiplies the columns (p,q) of G by W.
SUBROUTINE WROTC(M, N, G, LDG, P, Q, W, INFO)
  IMPLICIT NONE
  INTERFACE
     FUNCTION WFMA(A, B, C)
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: A, B, C
       COMPLEX(KIND=10) :: WFMA
     END FUNCTION WFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = 10
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
#define VL 1
  COMPLEX(KIND=K) :: X(VL)
  COMPLEX(KIND=K) :: Y(VL)
  INTEGER :: I, J
#define FMA WFMA
#include "hrotc.F90"
END SUBROUTINE WROTC
