!>@brief \b WSCALG scales \f$G\f$ by \f$2^S\f$.
SUBROUTINE WSCALG(M, N, G, LDG, S, INFO)
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = 10
  INTEGER, INTENT(IN) :: M, N, LDG, S
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
  INCLUDE 'hscalg.f90'
END SUBROUTINE WSCALG
