!>@brief \b XROTR premultiplies the rows (p,q) of G by W.
PURE SUBROUTINE XROTR(M, N, G, LDG, P, Q, W, INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  REAL(KIND=10), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=10), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=10) :: X, Y
  INTEGER :: J
#include "grotr.F90"
END SUBROUTINE XROTR
