!>@brief \b XSCALG scales G by 2^S.
SUBROUTINE XSCALG(M, N, G, LDG, S, INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, S
  REAL(KIND=10), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
#include "gscalg.F90"
END SUBROUTINE XSCALG
