!>@brief \b XSCALG scales G by 2^S.
SUBROUTINE XSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, S
  REAL(KIND=c_long_double), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
#include "gscalg.F90"
END SUBROUTINE XSCALG
