!>@brief \b XSCALG scales \f$G\f$ by \f$2^S\f$.
SUBROUTINE XSCALG(M, N, G, LDG, S, INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, S
  REAL(KIND=10), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
  INCLUDE 'gscalg.f90'
END SUBROUTINE XSCALG
