FUNCTION YFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
  COMPLEX(KIND=K), INTENT(IN) :: A, B, C
  COMPLEX(KIND=K) :: YFMA
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI, DR, DI
  EXTERNAL :: PVN_YFMA
#define KFMA YFMA
#define PFMA PVN_YFMA
#include "hfma.F90"
END FUNCTION YFMA
