FUNCTION YMUL(A, B)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
  COMPLEX(KIND=K), INTENT(IN) :: A, B
  COMPLEX(KIND=K) :: YMUL
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI
  EXTERNAL :: PVN_YMUL
#define KMUL YMUL
#define PMUL PVN_YMUL
#include "hmul.F90"
END FUNCTION YMUL
