!>@brief \b YROTR premultiplies the rows (p,q) of G by W.
SUBROUTINE YROTR(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
#define CR_HYPOT HYPOT
  INTERFACE
     FUNCTION YMUL(A, B)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       COMPLEX(KIND=REAL128), INTENT(IN) :: A, B
       COMPLEX(KIND=REAL128) :: YMUL
     END FUNCTION YMUL
  END INTERFACE
  INTERFACE
     FUNCTION YFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       COMPLEX(KIND=REAL128), INTENT(IN) :: A, B, C
       COMPLEX(KIND=REAL128) :: YFMA
     END FUNCTION YFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
#define VL 1
  COMPLEX(KIND=K) :: X(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: X
  COMPLEX(KIND=K) :: Y(VL)
  !DIR$ ATTRIBUTES ALIGN: 64:: Y
  INTEGER :: I, J
#define MUL YMUL
#define FMA YFMA
#include "hrotr.F90"
END SUBROUTINE YROTR
