!>@brief \b YROTR premultiplies the rows (p,q) of G by W.
PURE SUBROUTINE YROTR(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=REAL128), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=REAL128), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=REAL128) :: X, Y
  INTEGER :: J
#include "hrotr.F90"
END SUBROUTINE YROTR
