!>@brief \b ZBROTC postmultiplies the block-columns (P,Q) of G by R.
SUBROUTINE ZBROTC(N, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  COMPLEX(KIND=K), PARAMETER :: ZERO = (0.0_K,0.0_K), ONE = (1.0_K,0.0_K)
  INTEGER, INTENT(IN) :: N, B, LDG, P, Q, LDB, LDW
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: R(LDB,2*B)
  COMPLEX(KIND=K), INTENT(OUT) :: W(LDW,2*B)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, GI, GJ, RI, RJ
  EXTERNAL :: ZGEMM, ZLACPY
#define GEMM ZGEMM
#define LACPY ZLACPY
#include "gbrotc.F90"
END SUBROUTINE ZBROTC
