!>@brief \b ZBROTC postmultiplies the block-columns (P,Q) of G by R.
PURE SUBROUTINE ZBROTC(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE ZMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: TRANSA, TRANSB
       INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
       COMPLEX(KIND=REAL64), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: C(LDC,N)
     END SUBROUTINE ZMM
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE ZCP(UPLO, M, N, A, LDA, B, LDB)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: UPLO
       INTEGER, INTENT(IN) :: M, N, LDA, LDB
       COMPLEX(KIND=REAL64), INTENT(IN) :: A(LDA,N)
       COMPLEX(KIND=REAL64), INTENT(OUT) :: B(LDB,N)
     END SUBROUTINE ZCP
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  COMPLEX(KIND=K), PARAMETER :: ZERO = (0.0_K,0.0_K), ONE = (1.0_K,0.0_K)
  INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,M)
  COMPLEX(KIND=K), INTENT(IN) :: R(LDB,2*B)
  COMPLEX(KIND=K), INTENT(OUT) :: W(LDW,2*B)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, GI, GJ, RI, RJ
!   EXTERNAL :: ZGEMM, ZLACPY
! #define GEMM ZGEMM
! #define LACPY ZLACPY
#define GEMM ZMM
#define LACPY ZCP
#include "gbrotc.F90"
END SUBROUTINE ZBROTC
