!>@brief \b ZCONJT sets G = G^H.
PURE SUBROUTINE ZCONJT(N, G, LDG, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, LDG
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=K) :: T
  INTEGER :: I, J
#include "hconjt.F90"
END SUBROUTINE ZCONJT
