PURE FUNCTION ZFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_ZFMA(DR, DI, AR, AI, BR, BI, CR, CI)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       IMPLICIT NONE
       REAL(KIND=c_double), INTENT(OUT) :: DR, DI
       REAL(KIND=c_double), INTENT(IN) :: AR, AI, BR, BI, CR, CI
     END SUBROUTINE PVN_ZFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  COMPLEX(KIND=K), INTENT(IN) :: A, B, C
  COMPLEX(KIND=K) :: ZFMA
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI, DR, DI
#define KFMA ZFMA
#define PFMA PVN_ZFMA
#include "hfma.F90"
END FUNCTION ZFMA
