FUNCTION ZFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  COMPLEX(KIND=K), INTENT(IN) :: A, B, C
  COMPLEX(KIND=K) :: ZFMA
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI, DR, DI
  EXTERNAL :: PVN_ZFMA
#define KMA ZFMA
#define PMA PVN_ZFMA
#include "hfma.F90"
END FUNCTION ZFMA
