!>@brief \b ZMM computes C = ALPHA * A * B + BETA * C.
PURE SUBROUTINE ZMM(TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  COMPLEX(KIND=REAL64), PARAMETER :: ZERO = (0.0_REAL64,0.0_REAL64), ONE = (1.0_REAL64,0.0_REAL64)
  CHARACTER, INTENT(IN) :: TRANSA, TRANSB
  INTEGER, INTENT(IN) :: M, N, K, LDA, LDB, LDC
  COMPLEX(KIND=REAL64), INTENT(IN) :: A(LDA,K), B(LDB,N), ALPHA, BETA
  COMPLEX(KIND=REAL64), INTENT(INOUT) :: C(LDC,N)

  INTEGER :: I, J, L
#include "gmm.F90"
END SUBROUTINE ZMM
