FUNCTION ZMUL(A, B)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  COMPLEX(KIND=K), INTENT(IN) :: A, B
  COMPLEX(KIND=K) :: ZMUL
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI
  EXTERNAL :: PVN_ZMUL
#define KMUL ZMUL
#define PMUL PVN_ZMUL
#include "hmul.F90"
END FUNCTION ZMUL
