!>@brief \b ZROTC postmultiplies the columns (p,q) of G by W.
PURE SUBROUTINE ZROTC(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=REAL64), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=REAL64) :: X, Y
  INTEGER :: I
  INCLUDE 'grotc.f90'
END SUBROUTINE ZROTC
