!>@brief \b ZROTCX postmultiplies the columns (p,q) of G by W using an imperfect emulation of an accurate a*b+c*d operation.
PURE SUBROUTINE ZROTCX(M, N, G, LDG, P, Q, W, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64, L = c_long_double
  INTEGER, INTENT(IN) :: M, N, LDG, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
  INTEGER, INTENT(INOUT) :: INFO
  IF (MOD(M, 4) .EQ. 0) THEN
     CALL ZROTCX4(M, N, G, LDG, P, Q, W, INFO)
  ELSE IF (MOD(M, 2) .EQ. 0) THEN
     CALL ZROTCX2(M, N, G, LDG, P, Q, W, INFO)
  ELSE ! error
     INFO = -1
  END IF
CONTAINS
  PURE SUBROUTINE ZROTCX2(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL64, L = c_long_double
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
    COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 2
#undef HL
#define HL 1
#include "hrotca.F90"
  END SUBROUTINE ZROTCX2
  PURE SUBROUTINE ZROTCX4(M, N, G, LDG, P, Q, W, INFO)
    USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
    IMPLICIT NONE
    INTEGER, PARAMETER :: K = REAL64, L = c_long_double
    INTEGER, INTENT(IN) :: M, N, LDG, P, Q
    COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
    COMPLEX(KIND=K), INTENT(IN) :: W(2,2)
    INTEGER, INTENT(INOUT) :: INFO
#undef VL
#define VL 4
#undef HL
#define HL 2
#include "hrotca.F90"
  END SUBROUTINE ZROTCX4
END SUBROUTINE ZROTCX
