!>@brief \b ZSCALG scales G by 2^S.
SUBROUTINE ZSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M, N, LDG, S
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
#include "hscalg.F90"
END SUBROUTINE ZSCALG
