../obj/$(PLAT)/wmul.$(OXT): faux/wmul.F90 faux/hmul.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wmul.F90

../obj/$(PLAT)/ymul.$(OXT): faux/ymul.F90 faux/hmul.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/ymul.F90

../obj/$(PLAT)/wfma.$(OXT): faux/wfma.F90 faux/hfma.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wfma.F90

../obj/$(PLAT)/yfma.$(OXT): faux/yfma.F90 faux/hfma.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/yfma.F90

../obj/$(PLAT)/qlango.$(OXT): faux/qlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/qlango.F90

../obj/$(PLAT)/ylango.$(OXT): faux/ylango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/ylango.F90

../obj/$(PLAT)/xlango.$(OXT): faux/xlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/xlango.F90

../obj/$(PLAT)/wlango.$(OXT): faux/wlango.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wlango.F90

../obj/$(PLAT)/qrotc.$(OXT): faux/qrotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/qrotc.F90

../obj/$(PLAT)/yrotc.$(OXT): faux/yrotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/yrotc.F90

../obj/$(PLAT)/xrotc.$(OXT): faux/xrotc.F90 faux/grotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/xrotc.F90

../obj/$(PLAT)/xrotca.$(OXT): faux/xrotca.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/xrotca.F90

../obj/$(PLAT)/wrotc.$(OXT): faux/wrotc.F90 faux/hrotc.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wrotc.F90

../obj/$(PLAT)/wrotca.$(OXT): faux/wrotca.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wrotca.F90

../obj/$(PLAT)/qrotr.$(OXT): faux/qrotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/qrotr.F90

../obj/$(PLAT)/yrotr.$(OXT): faux/yrotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/yrotr.F90

../obj/$(PLAT)/xrotr.$(OXT): faux/xrotr.F90 faux/grotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/xrotr.F90

../obj/$(PLAT)/xrotra.$(OXT): faux/xrotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/xrotra.F90

../obj/$(PLAT)/wrotr.$(OXT): faux/wrotr.F90 faux/hrotr.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wrotr.F90

../obj/$(PLAT)/wrotra.$(OXT): faux/wrotra.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wrotra.F90

../obj/$(PLAT)/qscalg.$(OXT): faux/qscalg.F90 faux/gscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/qscalg.F90

../obj/$(PLAT)/yscalg.$(OXT): faux/yscalg.F90 faux/hscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/yscalg.F90

../obj/$(PLAT)/xscalg.$(OXT): faux/xscalg.F90 faux/gscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/xscalg.F90

../obj/$(PLAT)/wscalg.$(OXT): faux/wscalg.F90 faux/hscalg.F90 $(MKFS) faux/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/faux/wscalg.F90
