FUNCTION WFMA(A, B, C)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = c_long_double
  COMPLEX(KIND=K), INTENT(IN) :: A, B, C
  COMPLEX(KIND=K) :: WFMA
  REAL(KIND=K) :: AR, AI, BR, BI, CR, CI, DR, DI
  EXTERNAL :: PVN_WFMA
#define KFMA WFMA
#define PFMA PVN_WFMA
#include "hfma.F90"
END FUNCTION WFMA
