!>@brief \b YSCALG scales G by 2^S.
SUBROUTINE YSCALG(M, N, G, LDG, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
  INTEGER, INTENT(IN) :: M, N, LDG, S
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
#include "hscalg.F90"
END SUBROUTINE YSCALG
