../obj/$(PLAT)/qabsg.$(OXT): dynord/qabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qabsg.F90

../obj/$(PLAT)/yabsg.$(OXT): dynord/yabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/yabsg.F90

../obj/$(PLAT)/xabsg.$(OXT): dynord/xabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xabsg.F90

../obj/$(PLAT)/wabsg.$(OXT): dynord/wabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wabsg.F90

../obj/$(PLAT)/qmkwpq.$(OXT): dynord/qmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qmkwpq.F90

../obj/$(PLAT)/ymkwpq.$(OXT): dynord/ymkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/ymkwpq.F90

../obj/$(PLAT)/xmkwpq.$(OXT): dynord/xmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xmkwpq.F90

../obj/$(PLAT)/wmkwpq.$(OXT): dynord/wmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wmkwpq.F90

../obj/$(PLAT)/qmk3pq.$(OXT): dynord/qmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qmk3pq.F90

../obj/$(PLAT)/ymk3pq.$(OXT): dynord/ymk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/ymk3pq.F90

../obj/$(PLAT)/xmk3pq.$(OXT): dynord/xmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xmk3pq.F90

../obj/$(PLAT)/wmk3pq.$(OXT): dynord/wmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wmk3pq.F90

../obj/$(PLAT)/xmkdpq.$(OXT): dynord/xmkdpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xmkdpq.F90

../obj/$(PLAT)/wmkdpq.$(OXT): dynord/wmkdpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wmkdpq.F90

../obj/$(PLAT)/qpqcmp.$(OXT): dynord/qpqcmp.F90 dynord/gpqcmp.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qpqcmp.F90

../obj/$(PLAT)/xpqcmp.$(OXT): dynord/xpqcmp.F90 dynord/gpqcmp.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xpqcmp.F90

../obj/$(PLAT)/qpqmrg.$(OXT): dynord/qpqmrg.F90 dynord/gpqmrg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qpqmrg.F90

../obj/$(PLAT)/xpqmrg.$(OXT): dynord/xpqmrg.F90 dynord/gpqmrg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xpqmrg.F90

../obj/$(PLAT)/qpqsrt.$(OXT): dynord/qpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qpqsrt.F90

../obj/$(PLAT)/xpqsrt.$(OXT): dynord/xpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xpqsrt.F90
