PROGRAM MINMAX
  IMPLICIT NONE
  REAL, PARAMETER :: ZERO = 0.0, MZERO = -0.0
  PRINT *, MIN(ZERO, MZERO)
  PRINT *, MIN(MZERO, ZERO)
  PRINT *, MAX(ZERO, MZERO)
  PRINT *, MAX(MZERO, ZERO)
END PROGRAM MINMAX
