../lib/$(PLAT)/libarrbio.a: $(OBJS_ARRBIO) $(MKFS)
	$(AR) $(ARFLAGS) $@ $(OBJS_ARRBIO)

../obj/$(PLAT)/bfopen.$(OXT): arrbio/bfopen.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/bfopen.F90

../obj/$(PLAT)/ibrd1.$(OXT): arrbio/ibrd1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibrd1.F90

../obj/$(PLAT)/jbrd1.$(OXT): arrbio/jbrd1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbrd1.F90

../obj/$(PLAT)/sbrd1.$(OXT): arrbio/sbrd1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbrd1.F90

../obj/$(PLAT)/cbrd1.$(OXT): arrbio/cbrd1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbrd1.F90

../obj/$(PLAT)/dbrd1.$(OXT): arrbio/dbrd1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbrd1.F90

../obj/$(PLAT)/zbrd1.$(OXT): arrbio/zbrd1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbrd1.F90

../obj/$(PLAT)/ibwr1.$(OXT): arrbio/ibwr1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibwr1.F90

../obj/$(PLAT)/jbwr1.$(OXT): arrbio/jbwr1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbwr1.F90

../obj/$(PLAT)/sbwr1.$(OXT): arrbio/sbwr1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbwr1.F90

../obj/$(PLAT)/cbwr1.$(OXT): arrbio/cbwr1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbwr1.F90

../obj/$(PLAT)/dbwr1.$(OXT): arrbio/dbwr1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbwr1.F90

../obj/$(PLAT)/zbwr1.$(OXT): arrbio/zbwr1.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbwr1.F90

../obj/$(PLAT)/ibrd2.$(OXT): arrbio/ibrd2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibrd2.F90

../obj/$(PLAT)/jbrd2.$(OXT): arrbio/jbrd2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbrd2.F90

../obj/$(PLAT)/sbrd2.$(OXT): arrbio/sbrd2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbrd2.F90

../obj/$(PLAT)/cbrd2.$(OXT): arrbio/cbrd2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbrd2.F90

../obj/$(PLAT)/dbrd2.$(OXT): arrbio/dbrd2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbrd2.F90

../obj/$(PLAT)/zbrd2.$(OXT): arrbio/zbrd2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbrd2.F90

../obj/$(PLAT)/ibwr2.$(OXT): arrbio/ibwr2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibwr2.F90

../obj/$(PLAT)/jbwr2.$(OXT): arrbio/jbwr2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbwr2.F90

../obj/$(PLAT)/sbwr2.$(OXT): arrbio/sbwr2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbwr2.F90

../obj/$(PLAT)/cbwr2.$(OXT): arrbio/cbwr2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbwr2.F90

../obj/$(PLAT)/dbwr2.$(OXT): arrbio/dbwr2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbwr2.F90

../obj/$(PLAT)/zbwr2.$(OXT): arrbio/zbwr2.F90 $(MKFS)
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbwr2.F90
