../lib/$(PLAT)/libarrbio.a: $(OBJS_ARRBIO) $(MKFS) arrbio/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_ARRBIO)

../obj/$(PLAT)/bfopen.o: arrbio/bfopen.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/bfopen.f90

../obj/$(PLAT)/ibrd1.o: arrbio/ibrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ibrd1.f90

../obj/$(PLAT)/jbrd1.o: arrbio/jbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/jbrd1.f90

../obj/$(PLAT)/sbrd1.o: arrbio/sbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/sbrd1.f90

../obj/$(PLAT)/cbrd1.o: arrbio/cbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/cbrd1.f90

../obj/$(PLAT)/dbrd1.o: arrbio/dbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/dbrd1.f90

../obj/$(PLAT)/zbrd1.o: arrbio/zbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/zbrd1.f90

../obj/$(PLAT)/qbrd1.o: arrbio/qbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/qbrd1.f90

../obj/$(PLAT)/ybrd1.o: arrbio/ybrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ybrd1.f90

../obj/$(PLAT)/xbrd1.o: arrbio/xbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/xbrd1.f90

../obj/$(PLAT)/wbrd1.o: arrbio/wbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/wbrd1.f90

../obj/$(PLAT)/ibwr1.o: arrbio/ibwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ibwr1.f90

../obj/$(PLAT)/jbwr1.o: arrbio/jbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/jbwr1.f90

../obj/$(PLAT)/sbwr1.o: arrbio/sbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/sbwr1.f90

../obj/$(PLAT)/cbwr1.o: arrbio/cbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/cbwr1.f90

../obj/$(PLAT)/dbwr1.o: arrbio/dbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/dbwr1.f90

../obj/$(PLAT)/zbwr1.o: arrbio/zbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/zbwr1.f90

../obj/$(PLAT)/qbwr1.o: arrbio/qbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/qbwr1.f90

../obj/$(PLAT)/ybwr1.o: arrbio/ybwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ybwr1.f90

../obj/$(PLAT)/xbwr1.o: arrbio/xbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/xbwr1.f90

../obj/$(PLAT)/wbwr1.o: arrbio/wbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/wbwr1.f90

../obj/$(PLAT)/ibrd2.o: arrbio/ibrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ibrd2.f90

../obj/$(PLAT)/jbrd2.o: arrbio/jbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/jbrd2.f90

../obj/$(PLAT)/sbrd2.o: arrbio/sbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/sbrd2.f90

../obj/$(PLAT)/cbrd2.o: arrbio/cbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/cbrd2.f90

../obj/$(PLAT)/dbrd2.o: arrbio/dbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/dbrd2.f90

../obj/$(PLAT)/zbrd2.o: arrbio/zbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/zbrd2.f90

../obj/$(PLAT)/qbrd2.o: arrbio/qbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/qbrd2.f90

../obj/$(PLAT)/ybrd2.o: arrbio/ybrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ybrd2.f90

../obj/$(PLAT)/xbrd2.o: arrbio/xbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/xbrd2.f90

../obj/$(PLAT)/wbrd2.o: arrbio/wbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/wbrd2.f90

../obj/$(PLAT)/ibwr2.o: arrbio/ibwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ibwr2.f90

../obj/$(PLAT)/jbwr2.o: arrbio/jbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/jbwr2.f90

../obj/$(PLAT)/sbwr2.o: arrbio/sbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/sbwr2.f90

../obj/$(PLAT)/cbwr2.o: arrbio/cbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/cbwr2.f90

../obj/$(PLAT)/dbwr2.o: arrbio/dbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/dbwr2.f90

../obj/$(PLAT)/zbwr2.o: arrbio/zbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/zbwr2.f90

../obj/$(PLAT)/qbwr2.o: arrbio/qbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/qbwr2.f90

../obj/$(PLAT)/ybwr2.o: arrbio/ybwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/ybwr2.f90

../obj/$(PLAT)/xbwr2.o: arrbio/xbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/xbwr2.f90

../obj/$(PLAT)/wbwr2.o: arrbio/wbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/arrbio/wbwr2.f90
