../lib/$(PLAT)/libarrbio.a: $(OBJS_ARRBIO) $(MKFS) arrbio/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_ARRBIO)

../obj/$(PLAT)/bfopen.$(OXT): arrbio/bfopen.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/bfopen.f90

../obj/$(PLAT)/ibrd1.$(OXT): arrbio/ibrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibrd1.f90

../obj/$(PLAT)/jbrd1.$(OXT): arrbio/jbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbrd1.f90

../obj/$(PLAT)/sbrd1.$(OXT): arrbio/sbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbrd1.f90

../obj/$(PLAT)/cbrd1.$(OXT): arrbio/cbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbrd1.f90

../obj/$(PLAT)/dbrd1.$(OXT): arrbio/dbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbrd1.f90

../obj/$(PLAT)/zbrd1.$(OXT): arrbio/zbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbrd1.f90

../obj/$(PLAT)/qbrd1.$(OXT): arrbio/qbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbrd1.f90

../obj/$(PLAT)/ybrd1.$(OXT): arrbio/ybrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybrd1.f90

../obj/$(PLAT)/xbrd1.$(OXT): arrbio/xbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbrd1.f90

../obj/$(PLAT)/wbrd1.$(OXT): arrbio/wbrd1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbrd1.f90

../obj/$(PLAT)/ibwr1.$(OXT): arrbio/ibwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibwr1.f90

../obj/$(PLAT)/jbwr1.$(OXT): arrbio/jbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbwr1.f90

../obj/$(PLAT)/sbwr1.$(OXT): arrbio/sbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbwr1.f90

../obj/$(PLAT)/cbwr1.$(OXT): arrbio/cbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbwr1.f90

../obj/$(PLAT)/dbwr1.$(OXT): arrbio/dbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbwr1.f90

../obj/$(PLAT)/zbwr1.$(OXT): arrbio/zbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbwr1.f90

../obj/$(PLAT)/qbwr1.$(OXT): arrbio/qbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbwr1.f90

../obj/$(PLAT)/ybwr1.$(OXT): arrbio/ybwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybwr1.f90

../obj/$(PLAT)/xbwr1.$(OXT): arrbio/xbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbwr1.f90

../obj/$(PLAT)/wbwr1.$(OXT): arrbio/wbwr1.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbwr1.f90

../obj/$(PLAT)/ibrd2.$(OXT): arrbio/ibrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibrd2.f90

../obj/$(PLAT)/jbrd2.$(OXT): arrbio/jbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbrd2.f90

../obj/$(PLAT)/sbrd2.$(OXT): arrbio/sbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbrd2.f90

../obj/$(PLAT)/cbrd2.$(OXT): arrbio/cbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbrd2.f90

../obj/$(PLAT)/dbrd2.$(OXT): arrbio/dbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbrd2.f90

../obj/$(PLAT)/zbrd2.$(OXT): arrbio/zbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbrd2.f90

../obj/$(PLAT)/qbrd2.$(OXT): arrbio/qbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbrd2.f90

../obj/$(PLAT)/ybrd2.$(OXT): arrbio/ybrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybrd2.f90

../obj/$(PLAT)/xbrd2.$(OXT): arrbio/xbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbrd2.f90

../obj/$(PLAT)/wbrd2.$(OXT): arrbio/wbrd2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbrd2.f90

../obj/$(PLAT)/ibwr2.$(OXT): arrbio/ibwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ibwr2.f90

../obj/$(PLAT)/jbwr2.$(OXT): arrbio/jbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/jbwr2.f90

../obj/$(PLAT)/sbwr2.$(OXT): arrbio/sbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/sbwr2.f90

../obj/$(PLAT)/cbwr2.$(OXT): arrbio/cbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cbwr2.f90

../obj/$(PLAT)/dbwr2.$(OXT): arrbio/dbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dbwr2.f90

../obj/$(PLAT)/zbwr2.$(OXT): arrbio/zbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zbwr2.f90

../obj/$(PLAT)/qbwr2.$(OXT): arrbio/qbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbwr2.f90

../obj/$(PLAT)/ybwr2.$(OXT): arrbio/ybwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybwr2.f90

../obj/$(PLAT)/xbwr2.$(OXT): arrbio/xbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbwr2.f90

../obj/$(PLAT)/wbwr2.$(OXT): arrbio/wbwr2.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbwr2.f90

../obj/$(PLAT)/swrout.$(OXT): arrbio/swrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/swrout.f90

../obj/$(PLAT)/cwrout.$(OXT): arrbio/cwrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/cwrout.f90

../obj/$(PLAT)/dwrout.$(OXT): arrbio/dwrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/dwrout.f90

../obj/$(PLAT)/zwrout.$(OXT): arrbio/zwrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zwrout.f90

../obj/$(PLAT)/qwrout.$(OXT): arrbio/qwrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qwrout.f90

../obj/$(PLAT)/ywrout.$(OXT): arrbio/ywrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ywrout.f90

../obj/$(PLAT)/xwrout.$(OXT): arrbio/xwrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xwrout.f90

../obj/$(PLAT)/wwrout.$(OXT): arrbio/wwrout.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wwrout.f90

../obj/$(PLAT)/srdinp.$(OXT): arrbio/srdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/srdinp.f90

../obj/$(PLAT)/crdinp.$(OXT): arrbio/crdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/crdinp.f90

../obj/$(PLAT)/drdinp.$(OXT): arrbio/drdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/drdinp.f90

../obj/$(PLAT)/zrdinp.$(OXT): arrbio/zrdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/zrdinp.f90

../obj/$(PLAT)/qrdinp.$(OXT): arrbio/qrdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qrdinp.f90

../obj/$(PLAT)/yrdinp.$(OXT): arrbio/yrdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/yrdinp.f90

../obj/$(PLAT)/xrdinp.$(OXT): arrbio/xrdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xrdinp.f90

../obj/$(PLAT)/wrdinp.$(OXT): arrbio/wrdinp.f90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wrdinp.f90
