..\lib\$(PLAT)\arrbio.lib: $(OBJS_ARRBIO) $(MKFS) arrbio\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_ARRBIO)

..\obj\$(PLAT)\bfopen.obj: arrbio\bfopen.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\bfopen.f90

..\obj\$(PLAT)\ibrd1.obj: arrbio\ibrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibrd1.f90

..\obj\$(PLAT)\jbrd1.obj: arrbio\jbrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbrd1.f90

..\obj\$(PLAT)\sbrd1.obj: arrbio\sbrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbrd1.f90

..\obj\$(PLAT)\cbrd1.obj: arrbio\cbrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbrd1.f90

..\obj\$(PLAT)\dbrd1.obj: arrbio\dbrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbrd1.f90

..\obj\$(PLAT)\zbrd1.obj: arrbio\zbrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbrd1.f90

..\obj\$(PLAT)\qbrd1.obj: arrbio\qbrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\qbrd1.f90

..\obj\$(PLAT)\ybrd1.obj: arrbio\ybrd1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ybrd1.f90

..\obj\$(PLAT)\ibwr1.obj: arrbio\ibwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibwr1.f90

..\obj\$(PLAT)\jbwr1.obj: arrbio\jbwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbwr1.f90

..\obj\$(PLAT)\sbwr1.obj: arrbio\sbwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbwr1.f90

..\obj\$(PLAT)\cbwr1.obj: arrbio\cbwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbwr1.f90

..\obj\$(PLAT)\dbwr1.obj: arrbio\dbwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbwr1.f90

..\obj\$(PLAT)\zbwr1.obj: arrbio\zbwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbwr1.f90

..\obj\$(PLAT)\qbwr1.obj: arrbio\qbwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\qbwr1.f90

..\obj\$(PLAT)\ybwr1.obj: arrbio\ybwr1.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ybwr1.f90

..\obj\$(PLAT)\ibrd2.obj: arrbio\ibrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibrd2.f90

..\obj\$(PLAT)\jbrd2.obj: arrbio\jbrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbrd2.f90

..\obj\$(PLAT)\sbrd2.obj: arrbio\sbrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbrd2.f90

..\obj\$(PLAT)\cbrd2.obj: arrbio\cbrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbrd2.f90

..\obj\$(PLAT)\dbrd2.obj: arrbio\dbrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbrd2.f90

..\obj\$(PLAT)\zbrd2.obj: arrbio\zbrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbrd2.f90

..\obj\$(PLAT)\qbrd2.obj: arrbio\qbrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\qbrd2.f90

..\obj\$(PLAT)\ybrd2.obj: arrbio\ybrd2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ybrd2.f90

..\obj\$(PLAT)\ibwr2.obj: arrbio\ibwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibwr2.f90

..\obj\$(PLAT)\jbwr2.obj: arrbio\jbwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbwr2.f90

..\obj\$(PLAT)\sbwr2.obj: arrbio\sbwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbwr2.f90

..\obj\$(PLAT)\cbwr2.obj: arrbio\cbwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbwr2.f90

..\obj\$(PLAT)\dbwr2.obj: arrbio\dbwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbwr2.f90

..\obj\$(PLAT)\zbwr2.obj: arrbio\zbwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbwr2.f90

..\obj\$(PLAT)\qbwr2.obj: arrbio\qbwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\qbwr2.f90

..\obj\$(PLAT)\ybwr2.obj: arrbio\ybwr2.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ybwr2.f90

..\obj\$(PLAT)\swrout.obj: arrbio\swrout.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\swrout.f90

..\obj\$(PLAT)\cwrout.obj: arrbio\cwrout.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cwrout.f90

..\obj\$(PLAT)\dwrout.obj: arrbio\dwrout.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dwrout.f90

..\obj\$(PLAT)\zwrout.obj: arrbio\zwrout.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zwrout.f90

..\obj\$(PLAT)\qwrout.obj: arrbio\qwrout.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\qwrout.f90

..\obj\$(PLAT)\ywrout.obj: arrbio\ywrout.f90 $(MKFS) arrbio\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ywrout.f90
