..\lib\$(PLAT)\arrbio.lib: $(OBJS_ARRBIO) $(MKFS) arrbio\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_ARRBIO)

..\obj\$(PLAT)\bfopen.obj: arrbio\bfopen.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\bfopen.f90 /Fo$@

..\obj\$(PLAT)\ibrd1.obj: arrbio\ibrd1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\ibrd1.f90 /Fo$@

..\obj\$(PLAT)\sbrd1.obj: arrbio\sbrd1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\sbrd1.f90 /Fo$@

..\obj\$(PLAT)\cbrd1.obj: arrbio\cbrd1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\cbrd1.f90 /Fo$@

..\obj\$(PLAT)\dbrd1.obj: arrbio\dbrd1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\dbrd1.f90 /Fo$@

..\obj\$(PLAT)\zbrd1.obj: arrbio\zbrd1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\zbrd1.f90 /Fo$@

..\obj\$(PLAT)\qbrd1.obj: arrbio\qbrd1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\qbrd1.f90 /Fo$@

..\obj\$(PLAT)\ibwr1.obj: arrbio\ibwr1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\ibwr1.f90 /Fo$@

..\obj\$(PLAT)\sbwr1.obj: arrbio\sbwr1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\sbwr1.f90 /Fo$@

..\obj\$(PLAT)\cbwr1.obj: arrbio\cbwr1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\cbwr1.f90 /Fo$@

..\obj\$(PLAT)\dbwr1.obj: arrbio\dbwr1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\dbwr1.f90 /Fo$@

..\obj\$(PLAT)\zbwr1.obj: arrbio\zbwr1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\zbwr1.f90 /Fo$@

..\obj\$(PLAT)\qbwr1.obj: arrbio\qbwr1.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\qbwr1.f90 /Fo$@

..\obj\$(PLAT)\ibrd2.obj: arrbio\ibrd2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\ibrd2.f90 /Fo$@

..\obj\$(PLAT)\sbrd2.obj: arrbio\sbrd2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\sbrd2.f90 /Fo$@

..\obj\$(PLAT)\cbrd2.obj: arrbio\cbrd2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\cbrd2.f90 /Fo$@

..\obj\$(PLAT)\dbrd2.obj: arrbio\dbrd2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\dbrd2.f90 /Fo$@

..\obj\$(PLAT)\zbrd2.obj: arrbio\zbrd2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\zbrd2.f90 /Fo$@

..\obj\$(PLAT)\qbrd2.obj: arrbio\qbrd2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\qbrd2.f90 /Fo$@

..\obj\$(PLAT)\ibwr2.obj: arrbio\ibwr2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\ibwr2.f90 /Fo$@

..\obj\$(PLAT)\sbwr2.obj: arrbio\sbwr2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\sbwr2.f90 /Fo$@

..\obj\$(PLAT)\cbwr2.obj: arrbio\cbwr2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\cbwr2.f90 /Fo$@

..\obj\$(PLAT)\dbwr2.obj: arrbio\dbwr2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\dbwr2.f90 /Fo$@

..\obj\$(PLAT)\zbwr2.obj: arrbio\zbwr2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\zbwr2.f90 /Fo$@

..\obj\$(PLAT)\qbwr2.obj: arrbio\qbwr2.f90 $(MKFS) arrbio\Makefile
	$(FC) $(FCFLAGS) /c arrbio\qbwr2.f90 /Fo$@
