..\lib\$(PLAT)\arrbio.lib: $(OBJS_ARRBIO) $(MKFS)
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_ARRBIO)

..\obj\$(PLAT)\bfopen.obj: arrbio\bfopen.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\bfopen.F90

..\obj\$(PLAT)\ibrd1.obj: arrbio\ibrd1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibrd1.F90

..\obj\$(PLAT)\jbrd1.obj: arrbio\jbrd1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbrd1.F90

..\obj\$(PLAT)\sbrd1.obj: arrbio\sbrd1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbrd1.F90

..\obj\$(PLAT)\cbrd1.obj: arrbio\cbrd1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbrd1.F90

..\obj\$(PLAT)\dbrd1.obj: arrbio\dbrd1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbrd1.F90

..\obj\$(PLAT)\zbrd1.obj: arrbio\zbrd1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbrd1.F90

..\obj\$(PLAT)\ibwr1.obj: arrbio\ibwr1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibwr1.F90

..\obj\$(PLAT)\jbwr1.obj: arrbio\jbwr1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbwr1.F90

..\obj\$(PLAT)\sbwr1.obj: arrbio\sbwr1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbwr1.F90

..\obj\$(PLAT)\cbwr1.obj: arrbio\cbwr1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbwr1.F90

..\obj\$(PLAT)\dbwr1.obj: arrbio\dbwr1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbwr1.F90

..\obj\$(PLAT)\zbwr1.obj: arrbio\zbwr1.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbwr1.F90

..\obj\$(PLAT)\ibrd2.obj: arrbio\ibrd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibrd2.F90

..\obj\$(PLAT)\jbrd2.obj: arrbio\jbrd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbrd2.F90

..\obj\$(PLAT)\sbrd2.obj: arrbio\sbrd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbrd2.F90

..\obj\$(PLAT)\cbrd2.obj: arrbio\cbrd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbrd2.F90

..\obj\$(PLAT)\dbrd2.obj: arrbio\dbrd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbrd2.F90

..\obj\$(PLAT)\zbrd2.obj: arrbio\zbrd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbrd2.F90

..\obj\$(PLAT)\ibwr2.obj: arrbio\ibwr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\ibwr2.F90

..\obj\$(PLAT)\jbwr2.obj: arrbio\jbwr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\jbwr2.F90

..\obj\$(PLAT)\sbwr2.obj: arrbio\sbwr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\sbwr2.F90

..\obj\$(PLAT)\cbwr2.obj: arrbio\cbwr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\cbwr2.F90

..\obj\$(PLAT)\dbwr2.obj: arrbio\dbwr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\dbwr2.F90

..\obj\$(PLAT)\zbwr2.obj: arrbio\zbwr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\arrbio\zbwr2.F90
