!>@brief \b SABSG computes W=|G|.
SUBROUTINE SABSG(M, N, G, LDG, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL32), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=REAL32) :: H
  INTEGER :: I, J
#include "gabsg.F90"
END SUBROUTINE SABSG
