!>@brief \b DCVGPP postprocess the arguments of DKSVD2 and DLWSV2.
PURE SUBROUTINE DCVGPP(G, U, V, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, ONE = 1.0_REAL64
  REAL(KIND=REAL64), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
  REAL(KIND=REAL64), INTENT(INOUT) :: S(2)
  INTEGER, INTENT(INOUT) :: INFO(3)
  REAL(KIND=REAL64) :: T
  LOGICAL :: LND, LNU, LNV
  INCLUDE 'gcvgpp.f90'
END SUBROUTINE DCVGPP
