../lib/$(PLAT)/libksvd2.a: $(OBJS_KSVD2) $(MKFS) ksvd2/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_KSVD2)

../obj/$(PLAT)/sksvd2.$(OXT): ksvd2/sksvd2.F90 ksvd2/gksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/sksvd2.F90

../obj/$(PLAT)/cksvd2.$(OXT): ksvd2/cksvd2.F90 ksvd2/hksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/cksvd2.F90

../obj/$(PLAT)/dksvd2.$(OXT): ksvd2/dksvd2.F90 ksvd2/gksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/dksvd2.F90

../obj/$(PLAT)/zksvd2.$(OXT): ksvd2/zksvd2.F90 ksvd2/hksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/zksvd2.F90

../obj/$(PLAT)/qksvd2.$(OXT): ksvd2/qksvd2.F90 ksvd2/gksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/qksvd2.F90

../obj/$(PLAT)/yksvd2.$(OXT): ksvd2/yksvd2.F90 ksvd2/hksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/yksvd2.F90

../obj/$(PLAT)/xksvd2.$(OXT): ksvd2/xksvd2.F90 ksvd2/gksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xksvd2.F90

../obj/$(PLAT)/wksvd2.$(OXT): ksvd2/wksvd2.F90 ksvd2/hksvd2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/wksvd2.F90

../obj/$(PLAT)/scvgpp.$(OXT): ksvd2/scvgpp.F90 ksvd2/gcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/scvgpp.F90

../obj/$(PLAT)/ccvgpp.$(OXT): ksvd2/ccvgpp.F90 ksvd2/hcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/ccvgpp.F90

../obj/$(PLAT)/dcvgpp.$(OXT): ksvd2/dcvgpp.F90 ksvd2/gcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/dcvgpp.F90

../obj/$(PLAT)/zcvgpp.$(OXT): ksvd2/zcvgpp.F90 ksvd2/hcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/zcvgpp.F90

../obj/$(PLAT)/qcvgpp.$(OXT): ksvd2/qcvgpp.F90 ksvd2/gcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/qcvgpp.F90

../obj/$(PLAT)/ycvgpp.$(OXT): ksvd2/ycvgpp.F90 ksvd2/hcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/ycvgpp.F90

../obj/$(PLAT)/xcvgpp.$(OXT): ksvd2/xcvgpp.F90 ksvd2/gcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xcvgpp.F90

../obj/$(PLAT)/wcvgpp.$(OXT): ksvd2/wcvgpp.F90 ksvd2/hcvgpp.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/wcvgpp.F90

../obj/$(PLAT)/slmsv2.$(OXT): ksvd2/slmsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/slmsv2.F90

../obj/$(PLAT)/dlmsv2.$(OXT): ksvd2/dlmsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/dlmsv2.F90

../obj/$(PLAT)/qlmsv2.$(OXT): ksvd2/qlmsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/qlmsv2.F90

../obj/$(PLAT)/xlmsv2.$(OXT): ksvd2/xlmsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xlmsv2.F90

../obj/$(PLAT)/slwsv2.$(OXT): ksvd2/slwsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/slwsv2.F90

../obj/$(PLAT)/dlwsv2.$(OXT): ksvd2/dlwsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/dlwsv2.F90

../obj/$(PLAT)/qlwsv2.$(OXT): ksvd2/qlwsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/qlwsv2.F90

../obj/$(PLAT)/xlwsv2.$(OXT): ksvd2/xlwsv2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xlwsv2.F90

../obj/$(PLAT)/skerr2.$(OXT): ksvd2/skerr2.F90 ksvd2/gkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/skerr2.F90

../obj/$(PLAT)/ckerr2.$(OXT): ksvd2/ckerr2.F90 ksvd2/hkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/ckerr2.F90

../obj/$(PLAT)/dkerr2.$(OXT): ksvd2/dkerr2.F90 ksvd2/gkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/dkerr2.F90

../obj/$(PLAT)/zkerr2.$(OXT): ksvd2/zkerr2.F90 ksvd2/hkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/zkerr2.F90

../obj/$(PLAT)/qkerr2.$(OXT): ksvd2/qkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/qkerr2.F90

../obj/$(PLAT)/ykerr2.$(OXT): ksvd2/ykerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/ykerr2.F90

../obj/$(PLAT)/xkerr2.$(OXT): ksvd2/xkerr2.F90 ksvd2/gkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/xkerr2.F90

../obj/$(PLAT)/wkerr2.$(OXT): ksvd2/wkerr2.F90 ksvd2/hkerr2.F90 $(MKFS) ksvd2/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/ksvd2/wkerr2.F90
