..\lib\$(PLAT)\libksvd2.a: $(OBJS_KSVD2) $(MKFS)
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_KSVD2)

..\obj\$(PLAT)\sksvd2.obj: ksvd2\sksvd2.F90 ksvd2\gksvd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\sksvd2.F90

..\obj\$(PLAT)\cksvd2.obj: ksvd2\cksvd2.F90 ksvd2\hksvd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\cksvd2.F90

..\obj\$(PLAT)\dksvd2.obj: ksvd2\dksvd2.F90 ksvd2\gksvd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dksvd2.F90

..\obj\$(PLAT)\zksvd2.obj: ksvd2\zksvd2.F90 ksvd2\hksvd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\zksvd2.F90

..\obj\$(PLAT)\qksvd2.obj: ksvd2\qksvd2.F90 ksvd2\gksvd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\qksvd2.F90

..\obj\$(PLAT)\yksvd2.obj: ksvd2\yksvd2.F90 ksvd2\hksvd2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\yksvd2.F90

..\obj\$(PLAT)\scvgpp.obj: ksvd2\scvgpp.F90 ksvd2\gcvgpp.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\scvgpp.F90

..\obj\$(PLAT)\ccvgpp.obj: ksvd2\ccvgpp.F90 ksvd2\hcvgpp.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ccvgpp.F90

..\obj\$(PLAT)\dcvgpp.obj: ksvd2\dcvgpp.F90 ksvd2\gcvgpp.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dcvgpp.F90

..\obj\$(PLAT)\zcvgpp.obj: ksvd2\zcvgpp.F90 ksvd2\hcvgpp.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\zcvgpp.F90

..\obj\$(PLAT)\slmsv2.obj: ksvd2\slmsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\slmsv2.F90

..\obj\$(PLAT)\dlmsv2.obj: ksvd2\dlmsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dlmsv2.F90

..\obj\$(PLAT)\qlmsv2.obj: ksvd2\qlmsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\qlmsv2.F90

..\obj\$(PLAT)\xlmsv2.obj: ksvd2\xlmsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\xlmsv2.F90

..\obj\$(PLAT)\slwsv2.obj: ksvd2\slwsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\slwsv2.F90

..\obj\$(PLAT)\dlwsv2.obj: ksvd2\dlwsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dlwsv2.F90

..\obj\$(PLAT)\qlwsv2.obj: ksvd2\qlwsv2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\qlwsv2.F90

..\obj\$(PLAT)\skerr2.obj: ksvd2\skerr2.F90 ksvd2\gkerr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\skerr2.F90

..\obj\$(PLAT)\ckerr2.obj: ksvd2\ckerr2.F90 ksvd2\hkerr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ckerr2.F90

..\obj\$(PLAT)\dkerr2.obj: ksvd2\dkerr2.F90 ksvd2\gkerr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dkerr2.F90

..\obj\$(PLAT)\zkerr2.obj: ksvd2\zkerr2.F90 ksvd2\hkerr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\zkerr2.F90

..\obj\$(PLAT)\qkerr2.obj: ksvd2\qkerr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\qkerr2.F90

..\obj\$(PLAT)\ykerr2.obj: ksvd2\ykerr2.F90 $(MKFS)
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ykerr2.F90
