..\lib\$(PLAT)\ksvd2.lib: $(OBJS_KSVD2) $(MKFS) ksvd2\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_KSVD2)

..\obj\$(PLAT)\sksvd2.obj: ksvd2\sksvd2.F90 ksvd2\gksvd2.F90 ksvd2\gksvdu.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\sksvd2.F90

..\obj\$(PLAT)\cksvd2.obj: ksvd2\cksvd2.F90 ksvd2\hksvd2.F90 ksvd2\gksvdu.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\cksvd2.F90

..\obj\$(PLAT)\dksvd2.obj: ksvd2\dksvd2.F90 ksvd2\gksvd2.F90 ksvd2\gksvdu.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\dksvd2.F90

..\obj\$(PLAT)\zksvd2.obj: ksvd2\zksvd2.F90 ksvd2\hksvd2.F90 ksvd2\gksvdu.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\zksvd2.F90

..\obj\$(PLAT)\qksvd2.obj: ksvd2\qksvd2.F90 ksvd2\gksvd2.F90 ksvd2\gksvdu.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\qksvd2.F90

..\obj\$(PLAT)\yksvd2.obj: ksvd2\yksvd2.F90 ksvd2\hksvd2.F90 ksvd2\gksvdu.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\yksvd2.F90

..\obj\$(PLAT)\skalt2.obj: ksvd2\skalt2.F90 ksvd2\gkalt2.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\skalt2.F90

..\obj\$(PLAT)\dkalt2.obj: ksvd2\dkalt2.F90 ksvd2\gkalt2.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\dkalt2.F90

..\obj\$(PLAT)\qkalt2.obj: ksvd2\qkalt2.F90 ksvd2\gkalt2.F90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\ksvd2\qkalt2.F90

..\obj\$(PLAT)\scvgpp.obj: ksvd2\scvgpp.f90 ksvd2\gcvgpp.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\scvgpp.f90

..\obj\$(PLAT)\ccvgpp.obj: ksvd2\ccvgpp.f90 ksvd2\gcvgpp.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ccvgpp.f90

..\obj\$(PLAT)\dcvgpp.obj: ksvd2\dcvgpp.f90 ksvd2\gcvgpp.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dcvgpp.f90

..\obj\$(PLAT)\zcvgpp.obj: ksvd2\zcvgpp.f90 ksvd2\gcvgpp.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\zcvgpp.f90

..\obj\$(PLAT)\qcvgpp.obj: ksvd2\qcvgpp.f90 ksvd2\gcvgpp.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\qcvgpp.f90

..\obj\$(PLAT)\ycvgpp.obj: ksvd2\ycvgpp.f90 ksvd2\gcvgpp.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ycvgpp.f90

..\obj\$(PLAT)\slwsv2.obj: ksvd2\slwsv2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\slwsv2.f90

..\obj\$(PLAT)\dlwsv2.obj: ksvd2\dlwsv2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dlwsv2.f90

..\obj\$(PLAT)\skerr2.obj: ksvd2\skerr2.f90 ksvd2\gkerr2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\skerr2.f90

..\obj\$(PLAT)\ckerr2.obj: ksvd2\ckerr2.f90 ksvd2\hkerr2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ckerr2.f90

..\obj\$(PLAT)\dkerr2.obj: ksvd2\dkerr2.f90 ksvd2\gkerr2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\dkerr2.f90

..\obj\$(PLAT)\zkerr2.obj: ksvd2\zkerr2.f90 ksvd2\hkerr2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\zkerr2.f90

..\obj\$(PLAT)\qkerr2.obj: ksvd2\qkerr2.f90 ksvd2\gkerr2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\qkerr2.f90

..\obj\$(PLAT)\ykerr2.obj: ksvd2\ykerr2.f90 ksvd2\hkerr2.f90 $(MKFS) ksvd2\Makefile
	cd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\ksvd2\ykerr2.f90
