!>@brief \b SKERR2 computes the errors in the SVD of G.
SUBROUTINE SKERR2(G, U, V, S, E, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
#ifndef NDEBUG
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
#endif
  REAL(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2), S(2)
  REAL(KIND=K), INTENT(OUT) :: E(3)
  INTEGER, INTENT(IN) :: INFO(3)
  REAL(KIND=K) :: EX(4)
  EXTERNAL :: PVN_SQLJR2
#define QLJR2 PVN_SQLJR2
#include "gkerr2.F90"
END SUBROUTINE SKERR2
