!>@brief \b WCVGPP postprocess the arguments of WKSVD2.
PURE SUBROUTINE WCVGPP(G, U, V, S, INFO)
  IMPLICIT NONE
  COMPLEX(KIND=10), PARAMETER :: ZERO = (0.0_10,0.0_10), ONE = (1.0_10,0.0_10)
  COMPLEX(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
  REAL(KIND=10), INTENT(INOUT) :: S(2)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=10) :: T
  LOGICAL :: LND, LNU, LNV
  INCLUDE 'gcvgpp.f90'
END SUBROUTINE WCVGPP
