!>@brief \b XCVGPP postprocess the arguments of XKSVD2.
PURE SUBROUTINE XCVGPP(G, U, V, S, INFO)
  IMPLICIT NONE
  REAL(KIND=10), PARAMETER :: ZERO = 0.0_10, ONE = 1.0_10
  REAL(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
  REAL(KIND=10), INTENT(INOUT) :: S(2)
  INTEGER, INTENT(INOUT) :: INFO(3)
  REAL(KIND=10) :: T
  LOGICAL :: LND, LNU, LNV
  INCLUDE 'gcvgpp.f90'
END SUBROUTINE XCVGPP
