!>@brief \b YCVGPP postprocess the arguments of YKSVD2.
PURE SUBROUTINE YCVGPP(G, U, V, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  COMPLEX(KIND=REAL128), PARAMETER :: ZERO = (0.0_REAL128,0.0_REAL128), ONE = (1.0_REAL128,0.0_REAL128)
  COMPLEX(KIND=REAL128), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
  REAL(KIND=REAL128), INTENT(INOUT) :: S(2)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=REAL128) :: T
  LOGICAL :: LND, LNU, LNV
  INCLUDE 'gcvgpp.f90'
END SUBROUTINE YCVGPP
