!>@brief \b ZKERR2 computes the errors in the SVD of G.
SUBROUTINE ZKERR2(G, U, V, S, E, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
#ifndef NDEBUG
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
#endif
  COMPLEX(KIND=REAL64), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
  REAL(KIND=REAL64), INTENT(IN) :: S(2)
  REAL(KIND=K), INTENT(OUT) :: E(3)
  INTEGER, INTENT(IN) :: INFO(3)
  REAL(KIND=K) :: EX(4)
  EXTERNAL :: PVN_ZYLJR2
#define YLJR2 PVN_ZYLJR2
#include "hkerr2.F90"
END SUBROUTINE ZKERR2
