!>@brief \b CBKSVD0 calls CKSVD0 for all blocks.
SUBROUTINE CBKSVD0(JS, B2, NB, GB, UB, VB, LDB, SB, WB, LW, OD, OB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE CKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL32), INTENT(OUT) :: SV(N), W(*)
       INTEGER, INTENT(IN) :: O(2,*)
       INTEGER, INTENT(OUT) :: R(2,*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CKSVD0
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32, JOB = 963
  INTEGER, INTENT(IN) :: JS, B2, NB, LDB, LW, OB(2,*)
  COMPLEX(KIND=K), INTENT(INOUT) :: GB(LDB,LDB,NB) ! TODO: LDB x B2 x NB
  COMPLEX(KIND=K), INTENT(OUT) :: UB(LDB,B2,NB), VB(LDB,B2,NB)
  REAL(KIND=K), INTENT(OUT) :: SB(B2,NB), WB(LW,NB)
  INTEGER, INTENT(OUT) :: OD(2,B2,NB)
  INTEGER, INTENT(INOUT) :: O(2,NB), INFO
  INTEGER :: I, J, L
#define KSVD0 CKSVD0
#include "gbksvd0.F90"
END SUBROUTINE CBKSVD0
