!>@brief \b CBPACK packs G into GB.
SUBROUTINE CBPACK(N, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  COMPLEX(KIND=REAL32), PARAMETER :: ZERO = (0.0_REAL32,0.0_REAL32)
  INTEGER, INTENT(IN) :: N, LDG, B, LDB, NB, O(2,NB)
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  COMPLEX(KIND=REAL32), INTENT(OUT) :: GB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, M, P, Q
#include "gbpack.F90"
END SUBROUTINE CBPACK
