!>@brief \b CBUNPACK unpacks G from GB.
SUBROUTINE CBUNPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,2*NB)
  COMPLEX(KIND=REAL32), INTENT(OUT) :: G(LDG,M)
  COMPLEX(KIND=REAL32), INTENT(IN) :: GB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, N, P, Q
#include "gbunpack.F90"
END SUBROUTINE CBUNPACK
