!>@brief \b CBUPDATE updates G, U, and V.
SUBROUTINE CBUPDATE(M, B, G, LDG, U, LDU, V, LDV, GB, UB, VB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE CBROTC(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,M)
       COMPLEX(KIND=REAL32), INTENT(IN) :: R(LDB,2*B)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: W(LDW,2*B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CBROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CBROTR(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,M)
       COMPLEX(KIND=REAL32), INTENT(IN) :: R(LDB,2*B)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: W(LDW,B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CBROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CCONJT(N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE CCONJT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, B, LDG, LDU, LDV, LDB, NB, O(2,2*NB)
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,M), U(LDU,M), V(LDV,M), GB(LDB,LDB,NB), UB(LDB,2*B,NB) ! TODO: GB is LDB x 2*B x NB
  COMPLEX(KIND=K), INTENT(IN) :: VB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, L
#define BROTC CBROTC
#define BROTR CBROTR
#define CONJT CCONJT
#include "gbupdate.F90"
END SUBROUTINE CBUPDATE
