!>@brief \b CBUPDATE updates G, U, and V.
SUBROUTINE CBUPDATE(N, B, G, LDG, U, LDU, V, LDV, GB, UB, VB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE CBROTC(N, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B, LDG, P, Q, LDB, LDW
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: R(LDB,2*B)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: W(LDW,2*B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CBROTC
  END INTERFACE
  INTERFACE
     SUBROUTINE CBROTR(N, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, B, LDG, P, Q, LDB, LDW
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: R(LDB,2*B)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: W(LDW,B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CBROTR
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, B, LDG, LDU, LDV, LDB, NB, O(2,NB)
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N), GB(LDB,2*B,NB)
  COMPLEX(KIND=K), INTENT(IN) :: UB(LDB,2*B,NB), VB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, L
#define BROTC CBROTC
#define BROTR CBROTR
#include "gbupdate.F90"
END SUBROUTINE CBUPDATE
