!>@brief \b CKSVD0 computes the SVD of G as U S V^H, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE CKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
#ifdef PRINT0UT
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, PRINT0UT
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     SUBROUTINE CLANGO(N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL32), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE CSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE CKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE CKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE CCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CROTC(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CROTR(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL32, USID = 64, UACC = 128, VSID = 256, VACC = 512
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  COMPLEX(KIND=K), PARAMETER :: CZERO = (ZERO,ZERO), CONE = (ONE,ZERO)
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(*)
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
#ifdef ANIMATE
  REAL(KIND=K), INTENT(INOUT), TARGET :: SV(N)
#else
  REAL(KIND=K), INTENT(OUT) :: SV(N)
#endif
  REAL(KIND=K), INTENT(OUT) :: W(*)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER, INTENT(OUT) :: R(2,*)

  COMPLEX(KIND=K) :: G2(2,2), U2(2,2), V2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TM, TT
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP, ES(3)
  LOGICAL :: LOMP, LACC, LUSID, LUACC, LVSID, LVACC
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  INTEGER(KIND=c_size_t) :: LDF
  INTEGER(KIND=c_int), EXTERNAL :: PVN_CVIS_FRAME_F
#define PVN_CVIS_FRAME PVN_CVIS_FRAME_F
#endif

#define LANGO CLANGO
#define SCALG CSCALG
#define KSVD2 CKSVD2
#define CVGPP CCVGPP
#define ROTC CROTC
#define ROTR CROTR
#include "hksvd0.F90"
#ifdef PRINT0UT
9 FORMAT(A,ES16.9E2)
#endif
END SUBROUTINE CKSVD0
