!>@brief \b CKSVDD computes the SVD of G as U S V^H, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE CKSVDD(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, D, O, OD, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  !$ USE OMP_LIB
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     SUBROUTINE CLANGO(N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL32), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE CSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE CMKD(N, G, LDG, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG, O(2,*)
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CMKD
  END INTERFACE
  INTERFACE
     SUBROUTINE SMKDPQ(N, M, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, M
       REAL(KIND=REAL64), INTENT(INOUT) :: D(M+1)
       INTEGER, INTENT(OUT) :: O(2,N/2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SMKDPQ
  END INTERFACE
  INTERFACE
     SUBROUTINE CKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE CKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE CCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CROTCA(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CROTCA
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CROTRA(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CROTRA
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL32, KK = REAL64, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  COMPLEX(KIND=K), PARAMETER :: CZERO = (ZERO,ZERO), CONE = (ONE,ZERO)
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(2,*)
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
  REAL(KIND=K), INTENT(OUT) :: SV(N), W(*)
  REAL(KIND=KK), INTENT(OUT) :: D(*)
  INTEGER, INTENT(OUT) :: OD(2,N)
  INTEGER, INTENT(INOUT) :: INFO

  COMPLEX(KIND=K) :: G2(2,2), U2(2,2), V2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER :: MRQSTP, I, J, L, M, P, Q, T, GS, US, VS, WV, WS, STP, ES(3)
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC

#define LANGO CLANGO
#define SCALG CSCALG
#define MKD CMKD
#define MKDPQ SMKDPQ
#define KSVD2 CKSVD2
#define CVGPP CCVGPP
#define ROTCA CROTCA
#define ROTRA CROTRA
#include "hksvdd.F90"
END SUBROUTINE CKSVDD
