!>@brief \b CKSVD0 computes the SVD of G as U S V^H, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE CKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, INFO)
  USE, INTRINSIC :: ISO_C_BINDING
#ifdef NDEBUG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL128
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL128, OUTPUT_UNIT
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE

#ifdef CR_MATH
  INTERFACE
#ifdef NDEBUG
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
#else
     FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
#endif
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     SUBROUTINE CLANGO(O, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: O
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL32), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE CSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE CMK3PQ(K, N, G, LDG, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: K, N, LDG
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: W(N*N)
       INTEGER, INTENT(OUT) :: O(2*N*(N-1))
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CMK3PQ
  END INTERFACE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE CKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE CKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CROTC(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE CROTR(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE
#ifdef ANIMATE
  INTERFACE
     FUNCTION PVN_CVIS_FRAME(ctx, A, ldA) BIND(C,name='pvn_cvis_frame_f_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_size_t, c_ptr, c_float
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), TARGET :: ctx
       INTEGER(KIND=c_size_t), INTENT(IN), TARGET :: ldA
       COMPLEX(KIND=c_float), INTENT(IN), TARGET :: A(ldA,*)
       INTEGER(KIND=c_int) :: PVN_CVIS_FRAME
     END FUNCTION PVN_CVIS_FRAME
  END INTERFACE
#endif

  INTEGER, PARAMETER :: K = REAL32, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  COMPLEX(KIND=K), PARAMETER :: CZERO = (ZERO,ZERO), CONE = (ONE,ZERO)
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
  COMPLEX(KIND=K), INTENT(INOUT), TARGET :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(INOUT) :: U(LDU,N), V(LDV,N)
  REAL(KIND=REAL128), INTENT(INOUT), TARGET :: SV(N)
  REAL(KIND=K), INTENT(INOUT) :: W(MAX(N,5)*N)
  INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO

  INTEGER, POINTER, CONTIGUOUS :: R(:,:)
  COMPLEX(KIND=K) :: G2(2,2), U2(2,2), V2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TT, TM, SM
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP, XSG, XSU, XSV
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC
#ifdef ANIMATE
  TYPE(c_ptr), TARGET :: CTX
  TYPE(c_ptr), POINTER :: CP
  INTEGER(KIND=c_size_t), TARGET :: LDF
#endif

#define LANGO CLANGO
#define SCALG CSCALG
#define MK3PQ CMK3PQ
#define KSVD2 CKSVD2
#define CVGPP CCVGPP
#define ROTC CROTC
#define ROTR CROTR
#include "hksvd0.F90"
#ifndef NDEBUG
9 FORMAT(A,ES16.9E2)
#endif
END SUBROUTINE CKSVD0
