!>@brief \b DBKSVD0 calls DKSVD0 for all blocks.
SUBROUTINE DBKSVD0(JS, B2, NB, GB, UB, VB, LDB, SB, WB, LW, OD, OB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE DKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL64), INTENT(OUT) :: SV(N), W(*)
       INTEGER, INTENT(IN) :: O(2,*)
       INTEGER, INTENT(OUT) :: R(2,*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DKSVD0
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64, JOB = 960
  INTEGER, INTENT(IN) :: JS, B2, NB, LDB, LW, OB(2,*)
  REAL(KIND=K), INTENT(INOUT) :: GB(LDB,B2,NB)
  REAL(KIND=K), INTENT(OUT) :: UB(LDB,B2,NB), VB(LDB,B2,NB), SB(B2,NB), WB(LW,NB)
  INTEGER, INTENT(OUT) :: OD(2,B2,NB)
  INTEGER, INTENT(INOUT) :: O(2,NB), INFO
  INTEGER :: I, J
#ifdef ANIMATE
  INTEGER :: L
#endif
#define KSVD0 DKSVD0
#include "gbksvd0.F90"
END SUBROUTINE DBKSVD0
