!>@brief \b DBPACK packs G into GB.
SUBROUTINE DBPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,NB)
  REAL(KIND=REAL64), INTENT(IN) :: G(LDG,M)
  REAL(KIND=REAL64), INTENT(OUT) :: GB(LDB,LDB,NB) ! TODO: LDB x 2*B x NB
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, N, P, Q
#include "gbpack.F90"
END SUBROUTINE DBPACK
