!>@brief \b DBUNPACK unpacks G from GB.
SUBROUTINE DBUNPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,NB)
  REAL(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
  REAL(KIND=REAL64), INTENT(IN) :: GB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, N, P, Q
#include "gbunpack.F90"
END SUBROUTINE DBUNPACK
