!>@brief \b DBUPDATE updates G, U, and V.
SUBROUTINE DBUPDATE(M, B, G, LDG, U, LDU, V, LDV, GB, UB, VB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE DBROTC(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,M)
       REAL(KIND=REAL64), INTENT(IN) :: R(LDB,2*B)
       REAL(KIND=REAL64), INTENT(OUT) :: W(LDW,2*B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DBROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DBROTR(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,M)
       REAL(KIND=REAL64), INTENT(IN) :: R(LDB,2*B)
       REAL(KIND=REAL64), INTENT(OUT) :: W(LDW,B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DBROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DCONJT(N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DCONJT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M, B, LDG, LDU, LDV, LDB, NB, O(2,2*NB)
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,M), U(LDU,M), V(LDV,M), GB(LDB,2*B,NB), UB(LDB,2*B,NB)
  REAL(KIND=K), INTENT(IN) :: VB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, L
#define BROTC DBROTC
#define BROTR DBROTR
#define CONJT DCONJT
#include "gbupdate.F90"
END SUBROUTINE DBUPDATE
