!>@brief \b DKSVD0 computes the SVD of G as U S V^T, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE DKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
#ifdef NDEBUG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL64, REAL128
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL64, REAL128, OUTPUT_UNIT
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     SUBROUTINE DLANGO(O, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: O
       INTEGER, INTENT(IN) :: N, LDG
       REAL(KIND=REAL64), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL64), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE DSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE DMK3PQ(K, N, G, LDG, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: K, N, LDG
       REAL(KIND=REAL64), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(OUT) :: W(N*N)
       INTEGER, INTENT(OUT) :: O(2*N*(N-1))
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DMK3PQ
  END INTERFACE
  INTERFACE
     SUBROUTINE DKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL64), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE DKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL64), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE DCVGPP
  END INTERFACE
  INTERFACE
     SUBROUTINE DROTC(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DROTC
  END INTERFACE
  INTERFACE
     SUBROUTINE DROTR(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL64, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
#ifdef ANIMATE
  REAL(KIND=REAL128), INTENT(INOUT), TARGET :: SV(N)
#else
  REAL(KIND=REAL128), INTENT(OUT) :: SV(N)
#endif
  REAL(KIND=K), INTENT(INOUT) :: W(MAX(N,3)*N)
  INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
  INTEGER, INTENT(OUT) :: R(2,*)

  REAL(KIND=K) :: G2(2,2), U2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TT, TM, SM
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP, XSG, XSU, XSV, ES(3)
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  INTEGER(KIND=c_size_t) :: LDF
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RVIS_FRAME
#endif

#define LANGO DLANGO
#define SCALG DSCALG
#define MK3PQ DMK3PQ
#define KSVD2 DKSVD2
#define CVGPP DCVGPP
#define ROTC DROTC
#define ROTR DROTR
#include "gksvd0.F90"
#ifndef NDEBUG
9 FORMAT(A,ES25.17E3)
#endif
END SUBROUTINE DKSVD0
