!>@brief \b SBPACK packs G into GB.
SUBROUTINE SBPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,NB)
  REAL(KIND=REAL32), INTENT(IN) :: G(LDG,M)
  REAL(KIND=REAL32), INTENT(OUT) :: GB(LDB,LDB,NB) ! TODO: LDB x 2*B x NB
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, N, P, Q
#include "gbpack.F90"
END SUBROUTINE SBPACK
