!>@brief \b SKSVD0 computes the SVD of G as U S V^T, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE SKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, INFO)
  USE, INTRINSIC :: ISO_C_BINDING
#ifdef NDEBUG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL128
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL128, OUTPUT_UNIT
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     SUBROUTINE SLANGO(O, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: O
       INTEGER, INTENT(IN) :: N, LDG
       REAL(KIND=REAL32), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL32), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE SSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE SMK3PQ(K, N, G, LDG, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: K, N, LDG
       REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: W(N*N)
       INTEGER, INTENT(OUT) :: O(2*N*(N-1))
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SMK3PQ
  END INTERFACE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE SKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE SKSVD2(G, U, V, S, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SROTC(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SROTR(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL32, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
  REAL(KIND=REAL128), INTENT(OUT), TARGET :: SV(N)
  REAL(KIND=K), INTENT(INOUT) :: W(MAX(N,3)*N)
  INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO

  INTEGER, POINTER, CONTIGUOUS :: R(:,:)
  REAL(KIND=K) :: G2(2,2), U2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TT, TM, SM
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP, XSG, XSU, XSV
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC

#define LANGO SLANGO
#define SCALG SSCALG
#define MK3PQ SMK3PQ
#define KSVD2 SKSVD2
#define CVGPP SCVGPP
#define ROTC SROTC
#define ROTR SROTR
#include "gksvd0.F90"
#ifndef NDEBUG
9 FORMAT(A,ES16.9E2)
#endif
END SUBROUTINE SKSVD0
