!>@brief \b SKSVDD computes the SVD of G as U S V^T, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE SKSVDD(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, D, O, OD, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE SLANGO(N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       REAL(KIND=REAL32), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL32), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE SSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE SMKD(N, G, LDG, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG, O(2,*)
       REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SMKD
  END INTERFACE
  INTERFACE
     SUBROUTINE SMKDPQ(N, M, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, M
       REAL(KIND=REAL64), INTENT(INOUT) :: D(M+1)
       INTEGER, INTENT(OUT) :: O(2,N/2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SMKDPQ
  END INTERFACE
  INTERFACE
     SUBROUTINE SKSVD2(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2)
       REAL(KIND=REAL32), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE SKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SCVGPP(G, U, V, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=REAL32), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE SCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SROTCA(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SROTCA
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SROTRA(M, N, G, LDG, P, Q, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SROTRA
  END INTERFACE

  INTEGER, PARAMETER :: K = REAL32, KK = REAL64, USID = 64, UACC = 128, VSID = 256, VACC = 512
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(2,*)
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
  REAL(KIND=K), INTENT(OUT) :: SV(N), W(*)
  REAL(KIND=KK), INTENT(OUT) :: D(*)
  INTEGER, INTENT(OUT) :: OD(2,N)
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=K) :: G2(2,2), U2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER :: MRQSTP, I, J, L, M, P, Q, T, GS, US, VS, WV, WS, STP, ES(3)
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC
#define LANGO SLANGO
#define SCALG SSCALG
#define MKD SMKD
#define MKDPQ SMKDPQ
#define KSVD2 SKSVD2
#define CVGPP SCVGPP
#define ROTCA SROTCA
#define ROTRA SROTRA
#include "gksvdd.F90"
END SUBROUTINE SKSVDD
