!>@brief \b WKSVD0 computes the SVD of G as U S V^H, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE WKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, INFO)
  USE, INTRINSIC :: ISO_C_BINDING
#ifdef NDEBUG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128, OUTPUT_UNIT
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE

#define CR_HYPOT HYPOT
  INTERFACE
     SUBROUTINE WLANGO(O, N, G, LDG, S, INFO)
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: O
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=10), INTENT(IN) :: G(N,LDG)
       REAL(KIND=10), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE WSCALG(M, N, G, LDG, S, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       COMPLEX(KIND=10), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE WMK3PQ(K, N, G, LDG, W, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: K, N, LDG
       COMPLEX(KIND=10), INTENT(IN) :: G(LDG,N)
       REAL(KIND=10), INTENT(OUT) :: W(N*N)
       INTEGER, INTENT(OUT) :: O(2*N*(N-1))
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WMK3PQ
  END INTERFACE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE WKSVD2(G, U, V, S, INFO)
#else
     SUBROUTINE WKSVD2(G, U, V, S, INFO)
#endif
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: G(2,2)
       COMPLEX(KIND=10), INTENT(OUT) :: U(2,2), V(2,2)
       REAL(KIND=10), INTENT(OUT) :: S(2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE WKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE WCVGPP(G, U, V, S, INFO)
       IMPLICIT NONE
       COMPLEX(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=10), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE WROTC(M, N, G, LDG, P, Q, W, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=10), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=10), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE WROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE WROTR(M, N, G, LDG, P, Q, W, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       COMPLEX(KIND=10), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=10), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE WROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE

  INTEGER, PARAMETER :: K = 10, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  COMPLEX(KIND=K), PARAMETER :: CZERO = (ZERO,ZERO), CONE = (ONE,ZERO)
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
  REAL(KIND=REAL128), INTENT(OUT), TARGET :: SV(N)
  REAL(KIND=K), INTENT(OUT) :: W(MAX(N,5)*N)
  INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO

  INTEGER, POINTER, CONTIGUOUS :: R(:,:)
  COMPLEX(KIND=K) :: G2(2,2), U2(2,2), V2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TT, TM, SM
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC

#define LANGO WLANGO
#define SCALG WSCALG
#define MK3PQ WMK3PQ
#define KSVD2 WKSVD2
#define CVGPP WCVGPP
#define ROTC WROTC
#define ROTR WROTR
#include "hksvd0.F90"
#ifndef NDEBUG
9 FORMAT(A,ES30.21E4)
#endif
END SUBROUTINE WKSVD0
