!>@brief \b XKSVD0 computes the SVD of G as U S V^T, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE XKSVD0(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, O, R, INFO)
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
#ifdef NDEBUG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL128, OUTPUT_UNIT
#endif
  !$ USE OMP_LIB
  IMPLICIT NONE

  INTERFACE
     SUBROUTINE XLANGO(O, N, G, LDG, S, INFO)
       IMPLICIT NONE
       CHARACTER, INTENT(IN) :: O
       INTEGER, INTENT(IN) :: N, LDG
       REAL(KIND=10), INTENT(IN) :: G(N,LDG)
       REAL(KIND=10), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE XSCALG(M, N, G, LDG, S, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       REAL(KIND=10), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE XMK3PQ(K, N, G, LDG, W, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: K, N, LDG
       REAL(KIND=10), INTENT(IN) :: G(LDG,N)
       REAL(KIND=10), INTENT(OUT) :: W(N*N)
       INTEGER, INTENT(OUT) :: O(2*N*(N-1))
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XMK3PQ
  END INTERFACE
  INTERFACE
     SUBROUTINE XKSVD2(G, U, V, S, INFO)
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2)
       REAL(KIND=10), INTENT(OUT) :: U(2,2), V(2,2), S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE XKSVD2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XCVGPP(G, U, V, S, INFO)
       IMPLICIT NONE
       REAL(KIND=10), INTENT(IN) :: G(2,2), U(2,2), V(2,2)
       REAL(KIND=10), INTENT(INOUT) :: S(2)
       INTEGER, INTENT(INOUT) :: INFO(3)
     END SUBROUTINE XCVGPP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XROTC(M, N, G, LDG, P, Q, W, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=10), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=10), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XROTR(M, N, G, LDG, P, Q, W, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, P, Q
       REAL(KIND=10), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=10), INTENT(IN) :: W(2,2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE XROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE

  INTEGER, PARAMETER :: K = 10, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
#ifdef ANIMATE
  REAL(KIND=REAL128), INTENT(INOUT), TARGET :: SV(N)
#else
  REAL(KIND=REAL128), INTENT(OUT) :: SV(N)
#endif
  REAL(KIND=K), INTENT(INOUT) :: W(MAX(N,3)*N)
  INTEGER, INTENT(INOUT) :: O(2*N*(N-1)), INFO
  INTEGER, INTENT(OUT) :: R(2,*)

  REAL(KIND=K) :: G2(2,2), U2(2,2)
  REAL(KIND=K) :: GN, UN, VN
  INTEGER(KIND=INT64) :: TT, TM, SM
  INTEGER :: MRQSTP, I, J, L, M, M_2, NP, NS, P, Q, T, JS, GS, US, VS, WV, WS, STP, XSG, XSU, XSV, ES(3)
  LOGICAL :: LOMP, LUSID, LUACC, LVSID, LVACC
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  INTEGER(KIND=c_size_t) :: LDF
  INTEGER(KIND=c_int), EXTERNAL :: PVN_RVIS_FRAME_L
#define PVN_RVIS_FRAME PVN_RVIS_FRAME_L
#endif

#define LANGO XLANGO
#define SCALG XSCALG
#define MK3PQ XMK3PQ
#define KSVD2 XKSVD2
#define CVGPP XCVGPP
#define ROTC XROTC
#define ROTR XROTR
#include "gksvd0.F90"
#ifndef NDEBUG
9 FORMAT(A,ES30.21E4)
#endif
END SUBROUTINE XKSVD0
