!>@brief \b ZBKSVDD calls WKSVDD for all blocks.
SUBROUTINE ZBKSVDD(B2, NB, GB, UB, VB, LDB, SB, WB, LW, DB, LD, OD, OB, O, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE WKSVDD(JOB, N, G, LDG, U, LDU, V, LDV, SV, W, D, O, OD, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JOB, N, LDG, LDU, LDV, O(2,*)
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,N), U(LDU,N), V(LDV,N)
       REAL(KIND=REAL64), INTENT(OUT) :: SV(N), W(*)
       REAL(KIND=c_long_double), INTENT(OUT) :: D(*)
       INTEGER, INTENT(OUT) :: OD(2,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE WKSVDD
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64, KK = c_long_double, JOB = 123
#ifndef NDEBUG
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
#endif
  INTEGER, INTENT(IN) :: B2, NB, LDB, LW, LD, OB(2,*)
  COMPLEX(KIND=K), INTENT(INOUT) :: GB(LDB,B2,NB)
  COMPLEX(KIND=K), INTENT(OUT) :: UB(LDB,B2,NB), VB(LDB,B2,NB)
  REAL(KIND=K), INTENT(OUT) :: SB(B2,NB), WB(LW,NB)
  REAL(KIND=KK), INTENT(OUT) :: DB(LD,NB)
  INTEGER, INTENT(OUT) :: OD(2,B2,NB)
  INTEGER, INTENT(INOUT) :: O(2,NB), INFO
  INTEGER :: I, J
#define KSVDD WKSVDD
#include "gbksvdd.F90"
END SUBROUTINE ZBKSVDD
