!>@brief \b ZBUNPACK unpacks G from GB.
SUBROUTINE ZBUNPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,NB)
  COMPLEX(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
  COMPLEX(KIND=REAL64), INTENT(IN) :: GB(LDB,LDB,NB) ! TODO: LDB x 2*B x NB
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, N, P, Q
#include "gbunpack.F90"
END SUBROUTINE ZBUNPACK
