!>@brief \b ZBUNPACK unpacks G from GB.
SUBROUTINE ZBUNPACK(N, G, LDG, B, GB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N, LDG, B, LDB, NB, O(2,NB)
  COMPLEX(KIND=REAL64), INTENT(OUT) :: G(LDG,N)
  COMPLEX(KIND=REAL64), INTENT(IN) :: GB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, M, P, Q
#include "gbunpack.F90"
END SUBROUTINE ZBUNPACK
