!>@brief \b ZBUPDATE updates G, U, and V.
SUBROUTINE ZBUPDATE(M, B, G, LDG, U, LDU, V, LDV, GB, UB, VB, LDB, NB, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE ZBROTC(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,M)
       COMPLEX(KIND=REAL64), INTENT(IN) :: R(LDB,2*B)
       COMPLEX(KIND=REAL64), INTENT(OUT) :: W(LDW,2*B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZBROTC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE ZBROTR(M, B, G, LDG, P, Q, R, LDB, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, B, LDG, P, Q, LDB, LDW
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,M)
       COMPLEX(KIND=REAL64), INTENT(IN) :: R(LDB,2*B)
       COMPLEX(KIND=REAL64), INTENT(OUT) :: W(LDW,B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZBROTR
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE ZCONJT(N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ZCONJT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M, B, LDG, LDU, LDV, LDB, NB, O(2,2*NB)
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,M), U(LDU,M), V(LDV,M), GB(LDB,LDB,NB), UB(LDB,2*B,NB) ! TODO: GB is LDB x 2*B x NB
  COMPLEX(KIND=K), INTENT(IN) :: VB(LDB,2*B,NB)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, L
#define BROTC ZBROTC
#define BROTR ZBROTR
#define CONJT ZCONJT
#include "gbupdate.F90"
END SUBROUTINE ZBUPDATE
