!>@brief \b ZKSVD1 computes the SVD of G as U S V^T, with S returned in SV and U and V optionally accumulated on either identity for the SVD, or on preset input matrices.
SUBROUTINE ZKSVD1(JOB, M, B, G, LDG, U, LDU, V, LDV, SV, LDB, W, NW, D, ND, O, NO, INFO)
#ifdef ANIMATE
  USE, INTRINSIC :: ISO_C_BINDING
#endif
!#ifdef NDEBUG
!  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
!#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128, ERROR_UNIT
!#endif
  !$ USE OMP_LIB
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE IBDIMS(N, B, M, M_B, NW, ND, NO, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(INOUT) :: N, B, M, INFO
       INTEGER, INTENT(OUT) :: M_B, NW, ND, NO
     END SUBROUTINE IBDIMS
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE
  INTERFACE
     SUBROUTINE ZLANGO(N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(N,LDG)
       REAL(KIND=REAL64), INTENT(OUT) :: S
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZLANGO
  END INTERFACE
  INTERFACE
     SUBROUTINE ZSCALG(M, N, G, LDG, S, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, S
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZSCALG
  END INTERFACE
  INTERFACE
     SUBROUTINE ZMKBPQ(M, G, LDG, B, W, D, O, OD, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, LDG, B, O(2,*)
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,M)
       REAL(KIND=REAL64), INTENT(OUT) :: W(M/B,M/B)
       REAL(KIND=REAL128), INTENT(OUT) :: D(*)
       INTEGER, INTENT(OUT) :: OD(2,*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZMKBPQ
  END INTERFACE
  ! INTERFACE
  !    SUBROUTINE ZBPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  !      USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  !      IMPLICIT NONE
  !      INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,NB)
  !      COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,M)
  !      COMPLEX(KIND=REAL64), INTENT(OUT) :: GB(LDB,2*B,NB)
  !      INTEGER, INTENT(INOUT) :: INFO
  !    END SUBROUTINE ZBPACK
  ! END INTERFACE
  ! INTERFACE
  !    SUBROUTINE ZBUNPACK(M, G, LDG, B, GB, LDB, NB, O, INFO)
  !      USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  !      IMPLICIT NONE
  !      INTEGER, INTENT(IN) :: M, LDG, B, LDB, NB, O(2,NB)
  !      COMPLEX(KIND=REAL64), INTENT(OUT) :: G(LDG,M)
  !      COMPLEX(KIND=REAL64), INTENT(IN) :: GB(LDB,2*B,NB)
  !      INTEGER, INTENT(INOUT) :: INFO
  !    END SUBROUTINE ZBUNPACK
  ! END INTERFACE
  ! INTERFACE
  !    SUBROUTINE ZBKSVDD(B2, NB, GB, UB, VB, LDB, SB, WB, LW, DB, LD, OD, OB, O, INFO)
  !      USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
  !      IMPLICIT NONE
  !      INTEGER, INTENT(IN) :: B2, NB, LDB, LW, LD, OB(2,*)
  !      COMPLEX(KIND=REAL64), INTENT(INOUT) :: GB(LDB,B2,NB)
  !      COMPLEX(KIND=REAL64), INTENT(OUT) :: UB(LDB,B2,NB), VB(LDB,B2,NB)
  !      REAL(KIND=REAL64), INTENT(INOUT) :: SB(B2,NB), WB(LW,NB)
  !      REAL(KIND=REAL128), INTENT(OUT) :: DB(LD,NB)
  !      INTEGER, INTENT(OUT) :: OD(2,B2,NB)
  !      INTEGER, INTENT(INOUT) :: O(2,NB), INFO
  !    END SUBROUTINE ZBKSVDD
  ! END INTERFACE
  ! INTERFACE
  !    SUBROUTINE ZBUPDATE(M, B, G, LDG, U, LDU, V, LDV, GB, UB, VB, LDB, NB, O, INFO)
  !      USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  !      IMPLICIT NONE
  !      INTEGER, INTENT(IN) :: M, B, LDG, LDU, LDV, LDB, NB, O(2,2*NB)
  !      COMPLEX(KIND=REAL64), INTENT(INOUT) :: G(LDG,M), U(LDU,M), V(LDV,M), GB(LDB,2*B,NB), UB(LDB,2*B,NB)
  !      COMPLEX(KIND=REAL64), INTENT(IN) :: VB(LDB,2*B,NB)
  !      INTEGER, INTENT(INOUT) :: INFO
  !    END SUBROUTINE ZBUPDATE
  ! END INTERFACE
  INTEGER, PARAMETER :: K = REAL64, KK = REAL128, USID = 8, UACC = 16, VSID = 32, VACC = 64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: JOB, M, B, LDG, LDU, LDV, LDB, NW, ND, NO
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,M), U(LDU,M), V(LDV,M)
#ifdef ANIMATE
  REAL(KIND=K), INTENT(INOUT), TARGET :: SV(M)
#else
  REAL(KIND=K), INTENT(OUT) :: SV(M)
#endif
  REAL(KIND=K), INTENT(OUT) :: W(2*NW)
  REAL(KIND=KK), INTENT(OUT) :: D(ND)
  INTEGER, INTENT(INOUT) :: O(2,NO), INFO

  REAL(KIND=K) :: GN, VN, UN
  INTEGER :: I, J, L, N, P, Q, R, S, T, JS, BS, M_B, M_P, B_P, LB, LW, LD, NB, GS, US, VS
  INTEGER :: IGB, IUB, IVB, IWB, IO1, IO0, IOB, IOD
  LOGICAL :: LOMP, LX, LUSID, LUACC, LVSID, LVACC
  EXTERNAL :: ZBPACK, ZBKSVDD, ZBUNPACK, ZBUPDATE
#ifdef ANIMATE
  TYPE(c_ptr) :: CTX
  TYPE(c_ptr), POINTER :: CP
  INTEGER(KIND=c_size_t) :: LDF
  INTEGER(KIND=c_int), EXTERNAL :: PVN_CVIS_FRAME
#define VIS_FRAME PVN_CVIS_FRAME
#endif
#define LANGO ZLANGO
#define SCALG ZSCALG
#define MKBPQ ZMKBPQ
#define BPACK ZBPACK
#define BKSVDD ZBKSVDD
#define BUNPACK ZBUNPACK
#define BUPDATE ZBUPDATE
#include "hksvd1.F90"
END SUBROUTINE ZKSVD1
