SUBROUTINE BFOPEN(FN, ACT, U, INFO)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: FN, ACT
  INTEGER, INTENT(OUT) :: U, INFO

  CHARACTER(LEN=9) :: FACT
  CHARACTER(LEN=7) :: STAT
  LOGICAL :: L

  U = -1
  IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = -1
  ELSE IF (LEN_TRIM(ACT) .NE. 2) THEN
     INFO = -2
  ELSE
     INFO = 0
  END IF
  IF (INFO .NE. 0) RETURN

  SELECT CASE (ACT(1:1))
  CASE ('R', 'r')
     STAT = 'OLD'
     SELECT CASE (ACT(2:2))
     CASE ('O', 'o')
        FACT = 'READ'
     CASE ('W', 'w')
        FACT = 'READWRITE'
     CASE DEFAULT
        INFO = -2
     END SELECT
  CASE ('W', 'w')
     STAT = 'REPLACE'
     SELECT CASE (ACT(2:2))
     CASE ('O', 'o')
        FACT = 'WRITE'
     CASE ('R', 'r')
        FACT = 'READWRITE'
     CASE DEFAULT
        INFO = -2
     END SELECT
  CASE DEFAULT
     INFO = -2
  END SELECT
  IF (INFO .NE. 0) RETURN

  OPEN(NEWUNIT=U, IOSTAT=INFO, FILE=TRIM(FN), STATUS=TRIM(STAT), ACTION=TRIM(FACT), ACCESS='STREAM', FORM='UNFORMATTED')
END SUBROUTINE BFOPEN
