!>@brief \b CKSVD2X tests the CKSVD2 routine.
PROGRAM CKSVD2X
  IMPLICIT NONE
  EXTERNAL :: CKSVD2
  CALL CTEST(CKSVD2)
CONTAINS
  !>@brief \b CTEST calls KSVD2.
  !!
  !!@param KSVD2 is CKSVD2.
  SUBROUTINE CTEST(KSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64, REAL128
    IMPLICIT NONE

#ifdef CR_MATH
    INTERFACE
       FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
         USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
         REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
         REAL(KIND=c_float) :: CR_HYPOT
       END FUNCTION CR_HYPOT
    END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif

    INTEGER, PARAMETER :: IERR = -HUGE(0), KX = MAX(REAL64, REAL128), CLAL = 132
    EXTERNAL :: KSVD2
    CHARACTER(LEN=CLAL) :: CLA
    COMPLEX(KIND=REAL32) :: G(2,2), U(2,2), V(2,2)
    REAL(KIND=REAL32) :: S(2)
    INTEGER :: INFO
    LOGICAL :: ONCE
    COMPLEX(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2)
    REAL(KIND=KX) :: SX(2,2)
#include "uksvd2.f90"
1   FORMAT(A,ES16.9E2)
2   FORMAT(A,'(',ES16.9E2,',',ES16.9E2,')')
3   FORMAT(A,I4)
  END SUBROUTINE CTEST
END PROGRAM CKSVD2X
