ifdef NDEBUG
DEBUG=
FCFLAGS += -DNDEBUG=$(NDEBUG) -DCR_MATH=bundled_noerrno
else # !NDEBUG
DEBUG=g
FCFLAGS += -DCR_MATH=bundled
endif # ?NDEBUG
ifdef PRINTOUT
FCFLAGS += -DPRINTOUT=$(PRINTOUT)
endif # PRINTOUT
ifdef PRINT0UT
FCFLAGS += -DPRINT0UT=$(PRINT0UT)
endif # PRINT0UT
ifdef ANIMATE
FCFLAGS += -DANIMATE=$(ANIMATE)
endif # ANIMATE
ifdef PROFILE
FCFLAGS += -DPVN_PROFILE=$(PROFILE)u -fno-inline -finstrument-functions
endif # PROFILE
