ifeq ($(findstring -DNDEBUG,$(PVN_CPPFLAGS)),-DNDEBUG)
DEBUG=
CPPFLAGS=-DCR_MATH=bundled_noerrno
else # !NDEBUG
DEBUG=g
CPPFLAGS=-DCR_MATH=bundled
endif # ?NDEBUG
ifdef PRINTOUT
CPPFLAGS += -DPRINTOUT=$(PRINTOUT)
endif # PRINTOUT
ifdef PRINT0UT
CPPFLAGS += -DPRINT0UT=$(PRINT0UT)
endif # PRINT0UT
ifdef ANIMATE
CPPFLAGS += -DANIMATE=$(ANIMATE)
endif # ANIMATE
