SUBROUTINE DKSVD2(G, U, V, S, INFO)
  IMPLICIT NONE

  INTEGER, PARAMETER :: IERR = -HUGE(0)
  DOUBLE PRECISION, PARAMETER :: ZERO = 0D0, ONE = 1D0

  DOUBLE PRECISION, INTENT(IN) :: G(2,2)
  DOUBLE PRECISION, INTENT(OUT) :: U(2,2), V(2,2), S(2)
  INTEGER, INTENT(OUT) :: INFO

  INFO = 0
END SUBROUTINE DKSVD2
