!>@brief \b DKSVD2X tests the DKSVD2 routine.
PROGRAM DKSVD2X
  IMPLICIT NONE
  EXTERNAL :: DKSVD2
  CALL TEST(DKSVD2)
CONTAINS
  SUBROUTINE TEST(KSVD2)
    IMPLICIT NONE
    INTEGER, PARAMETER :: IERR = -HUGE(0)
    EXTERNAL :: KSVD2
    DOUBLE PRECISION :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: INFO
    INCLUDE 'tksvd2.f90'
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,I5)
  END SUBROUTINE TEST
END PROGRAM DKSVD2X
