!>@brief \b DKSVD2X tests the DKSVD2 routine.
PROGRAM DKSVD2X
  IMPLICIT NONE
  EXTERNAL :: DKSVD2
  CALL DTEST(DKSVD2)
CONTAINS
  !>@brief \b DTEST calls KSVD2.
  !!
  !!@param KSVD2 is DKSVD2.
  SUBROUTINE DTEST(KSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
    IMPLICIT NONE
    INTEGER, PARAMETER :: IERR = -HUGE(0), KX = MAX(REAL64, REAL128), CLAL = 64
    EXTERNAL :: KSVD2
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL64) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: INFO
    LOGICAL :: ONCE
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    INCLUDE 'tksvd2.f90'
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,I5)
  END SUBROUTINE DTEST
END PROGRAM DKSVD2X
