!>@brief \b DLWSV2X tests the DLWSV2 routine.
PROGRAM DLWSV2X
  IMPLICIT NONE
  EXTERNAL :: DLWSV2
  CALL DLTEST(DLWSV2)
CONTAINS
  !>@brief \b DLTEST calls LSVD2.
  !!
  !!@param LSVD2 is DLWSV2.
  SUBROUTINE DLTEST(LSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
    IMPLICIT NONE
    INTEGER, PARAMETER :: IERR = -HUGE(0), KX = MAX(REAL64, REAL128), CLAL = 64
    EXTERNAL :: LSVD2
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL64) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: INFO
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    G(2,1) = 0.0_REAL64
    INCLUDE 'tlasv2.f90'
1   FORMAT(A,ES25.17E3)
2   FORMAT(A,I5)
  END SUBROUTINE DLTEST
END PROGRAM DLWSV2X
