!>@brief \b DPSUM4 sums four non-negative weights in double precision.
PURE SUBROUTINE DPSUM4(W1, W2, W3, W4, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64
  REAL(KIND=REAL64), INTENT(IN) :: W1, W2, W3, W4
  REAL(KIND=REAL64), INTENT(OUT) :: W
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL64) :: T(4)
  INTEGER :: I, J, K
  INCLUDE 'gpsum4.f90'
END SUBROUTINE DPSUM4
