OBJS_ARRBIO=\
../obj/$(PLAT)/bfopen.$(OXT)\
../obj/$(PLAT)/ibrd1.$(OXT)\
../obj/$(PLAT)/jbrd1.$(OXT)\
../obj/$(PLAT)/sbrd1.$(OXT)\
../obj/$(PLAT)/cbrd1.$(OXT)\
../obj/$(PLAT)/dbrd1.$(OXT)\
../obj/$(PLAT)/zbrd1.$(OXT)\
../obj/$(PLAT)/ibwr1.$(OXT)\
../obj/$(PLAT)/jbwr1.$(OXT)\
../obj/$(PLAT)/sbwr1.$(OXT)\
../obj/$(PLAT)/cbwr1.$(OXT)\
../obj/$(PLAT)/dbwr1.$(OXT)\
../obj/$(PLAT)/zbwr1.$(OXT)\
../obj/$(PLAT)/ibrd2.$(OXT)\
../obj/$(PLAT)/jbrd2.$(OXT)\
../obj/$(PLAT)/sbrd2.$(OXT)\
../obj/$(PLAT)/cbrd2.$(OXT)\
../obj/$(PLAT)/dbrd2.$(OXT)\
../obj/$(PLAT)/zbrd2.$(OXT)\
../obj/$(PLAT)/ibwr2.$(OXT)\
../obj/$(PLAT)/jbwr2.$(OXT)\
../obj/$(PLAT)/sbwr2.$(OXT)\
../obj/$(PLAT)/cbwr2.$(OXT)\
../obj/$(PLAT)/dbwr2.$(OXT)\
../obj/$(PLAT)/zbwr2.$(OXT)

OBJS_BLKSVD=\
../obj/$(PLAT)/nb2m.$(OXT)\
../obj/$(PLAT)/sbrdg.$(OXT)\
../obj/$(PLAT)/cbrdg.$(OXT)\
../obj/$(PLAT)/dbrdg.$(OXT)\
../obj/$(PLAT)/zbrdg.$(OXT)\
../obj/$(PLAT)/sbpack.$(OXT)\
../obj/$(PLAT)/cbpack.$(OXT)\
../obj/$(PLAT)/dbpack.$(OXT)\
../obj/$(PLAT)/zbpack.$(OXT)\
../obj/$(PLAT)/sbunpack.$(OXT)\
../obj/$(PLAT)/cbunpack.$(OXT)\
../obj/$(PLAT)/dbunpack.$(OXT)\
../obj/$(PLAT)/zbunpack.$(OXT)\
../obj/$(PLAT)/sbupdate.$(OXT)\
../obj/$(PLAT)/cbupdate.$(OXT)\
../obj/$(PLAT)/dbupdate.$(OXT)\
../obj/$(PLAT)/zbupdate.$(OXT)\
../obj/$(PLAT)/sksvd0.$(OXT)\
../obj/$(PLAT)/cksvd0.$(OXT)\
../obj/$(PLAT)/dksvd0.$(OXT)\
../obj/$(PLAT)/zksvd0.$(OXT)\
../obj/$(PLAT)/sksvd1.$(OXT)\
../obj/$(PLAT)/cksvd1.$(OXT)\
../obj/$(PLAT)/dksvd1.$(OXT)\
../obj/$(PLAT)/zksvd1.$(OXT)\
../obj/$(PLAT)/sksvdd.$(OXT)\
../obj/$(PLAT)/dksvdd.$(OXT)\
../obj/$(PLAT)/xksvdd.$(OXT)\
../obj/$(PLAT)/cksvdd.$(OXT)\
../obj/$(PLAT)/zksvdd.$(OXT)\
../obj/$(PLAT)/wksvdd.$(OXT)\
../obj/$(PLAT)/sbksvdd.$(OXT)\
../obj/$(PLAT)/cbksvdd.$(OXT)\
../obj/$(PLAT)/dbksvdd.$(OXT)\
../obj/$(PLAT)/zbksvdd.$(OXT)\
../obj/$(PLAT)/ibdims.$(OXT)

OBJS_DYNORD=\
../obj/$(PLAT)/sabsg.$(OXT)\
../obj/$(PLAT)/cabsg.$(OXT)\
../obj/$(PLAT)/dabsg.$(OXT)\
../obj/$(PLAT)/zabsg.$(OXT)\
../obj/$(PLAT)/snrm2o.$(OXT)\
../obj/$(PLAT)/cnrm2o.$(OXT)\
../obj/$(PLAT)/dnrm2o.$(OXT)\
../obj/$(PLAT)/znrm2o.$(OXT)\
../obj/$(PLAT)/snrm2b.$(OXT)\
../obj/$(PLAT)/cnrm2b.$(OXT)\
../obj/$(PLAT)/dnrm2b.$(OXT)\
../obj/$(PLAT)/znrm2b.$(OXT)\
../obj/$(PLAT)/sb2enc.$(OXT)\
../obj/$(PLAT)/db2enc.$(OXT)\
../obj/$(PLAT)/smkwpq.$(OXT)\
../obj/$(PLAT)/cmkwpq.$(OXT)\
../obj/$(PLAT)/dmkwpq.$(OXT)\
../obj/$(PLAT)/zmkwpq.$(OXT)\
../obj/$(PLAT)/smk3pq.$(OXT)\
../obj/$(PLAT)/cmk3pq.$(OXT)\
../obj/$(PLAT)/dmk3pq.$(OXT)\
../obj/$(PLAT)/zmk3pq.$(OXT)\
../obj/$(PLAT)/smkd.$(OXT)\
../obj/$(PLAT)/dmkd.$(OXT)\
../obj/$(PLAT)/xmkd.$(OXT)\
../obj/$(PLAT)/cmkd.$(OXT)\
../obj/$(PLAT)/zmkd.$(OXT)\
../obj/$(PLAT)/wmkd.$(OXT)\
../obj/$(PLAT)/smkdpq.$(OXT)\
../obj/$(PLAT)/dmkdpq.$(OXT)\
../obj/$(PLAT)/xmkdpq.$(OXT)\
../obj/$(PLAT)/smkbpq.$(OXT)\
../obj/$(PLAT)/dmkbpq.$(OXT)\
../obj/$(PLAT)/cmkbpq.$(OXT)\
../obj/$(PLAT)/zmkbpq.$(OXT)\
../obj/$(PLAT)/spqcmp.$(OXT)\
../obj/$(PLAT)/dpqcmp.$(OXT)\
../obj/$(PLAT)/spqmrg.$(OXT)\
../obj/$(PLAT)/dpqmrg.$(OXT)\
../obj/$(PLAT)/spqsrt.$(OXT)\
../obj/$(PLAT)/dpqsrt.$(OXT)

OBJS_KSVD2=\
../obj/$(PLAT)/sksvd2.$(OXT)\
../obj/$(PLAT)/cksvd2.$(OXT)\
../obj/$(PLAT)/dksvd2.$(OXT)\
../obj/$(PLAT)/zksvd2.$(OXT)\
../obj/$(PLAT)/qksvd2.$(OXT)\
../obj/$(PLAT)/yksvd2.$(OXT)\
../obj/$(PLAT)/scvgpp.$(OXT)\
../obj/$(PLAT)/ccvgpp.$(OXT)\
../obj/$(PLAT)/dcvgpp.$(OXT)\
../obj/$(PLAT)/zcvgpp.$(OXT)\
../obj/$(PLAT)/slmsv2.$(OXT)\
../obj/$(PLAT)/dlmsv2.$(OXT)\
../obj/$(PLAT)/qlmsv2.$(OXT)\
../obj/$(PLAT)/slwsv2.$(OXT)\
../obj/$(PLAT)/dlwsv2.$(OXT)\
../obj/$(PLAT)/qlwsv2.$(OXT)\
../obj/$(PLAT)/skerr2.$(OXT)\
../obj/$(PLAT)/ckerr2.$(OXT)\
../obj/$(PLAT)/dkerr2.$(OXT)\
../obj/$(PLAT)/zkerr2.$(OXT)\
../obj/$(PLAT)/qkerr2.$(OXT)\
../obj/$(PLAT)/ykerr2.$(OXT)

OBJS_FAUX=\
../obj/$(PLAT)/sthalt.$(OXT)\
../obj/$(PLAT)/cmul.$(OXT)\
../obj/$(PLAT)/zmul.$(OXT)\
../obj/$(PLAT)/cfma.$(OXT)\
../obj/$(PLAT)/zfma.$(OXT)\
../obj/$(PLAT)/sconjt.$(OXT)\
../obj/$(PLAT)/cconjt.$(OXT)\
../obj/$(PLAT)/dconjt.$(OXT)\
../obj/$(PLAT)/zconjt.$(OXT)\
../obj/$(PLAT)/slango.$(OXT)\
../obj/$(PLAT)/clango.$(OXT)\
../obj/$(PLAT)/dlango.$(OXT)\
../obj/$(PLAT)/zlango.$(OXT)\
../obj/$(PLAT)/srotc.$(OXT)\
../obj/$(PLAT)/srotca.$(OXT)\
../obj/$(PLAT)/crotc.$(OXT)\
../obj/$(PLAT)/crotca.$(OXT)\
../obj/$(PLAT)/drotc.$(OXT)\
../obj/$(PLAT)/drotca.$(OXT)\
../obj/$(PLAT)/drotcx.$(OXT)\
../obj/$(PLAT)/zrotc.$(OXT)\
../obj/$(PLAT)/zrotca.$(OXT)\
../obj/$(PLAT)/zrotcx.$(OXT)\
../obj/$(PLAT)/sbrotc.$(OXT)\
../obj/$(PLAT)/cbrotc.$(OXT)\
../obj/$(PLAT)/dbrotc.$(OXT)\
../obj/$(PLAT)/zbrotc.$(OXT)\
../obj/$(PLAT)/srotr.$(OXT)\
../obj/$(PLAT)/srotra.$(OXT)\
../obj/$(PLAT)/crotr.$(OXT)\
../obj/$(PLAT)/crotra.$(OXT)\
../obj/$(PLAT)/drotr.$(OXT)\
../obj/$(PLAT)/drotra.$(OXT)\
../obj/$(PLAT)/drotrx.$(OXT)\
../obj/$(PLAT)/zrotr.$(OXT)\
../obj/$(PLAT)/zrotra.$(OXT)\
../obj/$(PLAT)/zrotrx.$(OXT)\
../obj/$(PLAT)/sbrotr.$(OXT)\
../obj/$(PLAT)/cbrotr.$(OXT)\
../obj/$(PLAT)/dbrotr.$(OXT)\
../obj/$(PLAT)/zbrotr.$(OXT)\
../obj/$(PLAT)/sscalg.$(OXT)\
../obj/$(PLAT)/cscalg.$(OXT)\
../obj/$(PLAT)/dscalg.$(OXT)\
../obj/$(PLAT)/zscalg.$(OXT)\
../obj/$(PLAT)/initrc.$(OXT)\
../obj/$(PLAT)/initcc.$(OXT)\
../obj/$(PLAT)/initme.$(OXT)\
../obj/$(PLAT)/initmm.$(OXT)\
../obj/$(PLAT)/jstep.$(OXT)\
../obj/$(PLAT)/jsweep.$(OXT)

EXES_BLKSVD=\
../bin/$(PLAT)/sksvd0.exe\
../bin/$(PLAT)/cksvd0.exe\
../bin/$(PLAT)/dksvd0.exe\
../bin/$(PLAT)/zksvd0.exe\
../bin/$(PLAT)/sksvd1.exe\
../bin/$(PLAT)/cksvd1.exe\
../bin/$(PLAT)/dksvd1.exe\
../bin/$(PLAT)/zksvd1.exe\
../bin/$(PLAT)/sksvdd.exe\
../bin/$(PLAT)/dksvdd.exe\
../bin/$(PLAT)/cksvdd.exe\
../bin/$(PLAT)/zksvdd.exe\
../bin/$(PLAT)/xksvdd.exe\
../bin/$(PLAT)/wksvdd.exe\
../bin/$(PLAT)/ibdims.exe

EXES_DYNORD=\
../bin/$(PLAT)/smkbpq.exe\
../bin/$(PLAT)/dmkbpq.exe\
../bin/$(PLAT)/cmkbpq.exe\
../bin/$(PLAT)/zmkbpq.exe\
../bin/$(PLAT)/spqsort.exe\
../bin/$(PLAT)/dpqsort.exe

EXES_KSVD2=\
../bin/$(PLAT)/sksvd2.exe\
../bin/$(PLAT)/cksvd2.exe\
../bin/$(PLAT)/dksvd2.exe\
../bin/$(PLAT)/zksvd2.exe\
../bin/$(PLAT)/qksvd2.exe\
../bin/$(PLAT)/yksvd2.exe\
../bin/$(PLAT)/slwsv2.exe\
../bin/$(PLAT)/dlwsv2.exe\
../bin/$(PLAT)/qlwsv2.exe

EXES_FAUX=\
../bin/$(PLAT)/sthalt.exe\
../bin/$(PLAT)/jsweep.exe

EXES_TEST=\
../bin/$(PLAT)/sran.exe\
../bin/$(PLAT)/cran.exe\
../bin/$(PLAT)/dran.exe\
../bin/$(PLAT)/zran.exe\
../bin/$(PLAT)/srnd.exe\
../bin/$(PLAT)/crnd.exe\
../bin/$(PLAT)/drnd.exe\
../bin/$(PLAT)/zrnd.exe\
../bin/$(PLAT)/sran2u.exe\
../bin/$(PLAT)/sran2g.exe\
../bin/$(PLAT)/cran2g.exe\
../bin/$(PLAT)/dran2u.exe\
../bin/$(PLAT)/dran2g.exe\
../bin/$(PLAT)/zran2g.exe\
../bin/$(PLAT)/srnd2u.exe\
../bin/$(PLAT)/srnd2g.exe\
../bin/$(PLAT)/crnd2g.exe\
../bin/$(PLAT)/drnd2u.exe\
../bin/$(PLAT)/drnd2g.exe\
../bin/$(PLAT)/zrnd2g.exe

OBJS=$(OBJS_ARRBIO) $(OBJS_BLKSVD) $(OBJS_DYNORD) $(OBJS_KSVD2) $(OBJS_FAUX)

LIBS=\
../lib/$(PLAT)/libarrbio.a\
../lib/$(PLAT)/libblksvd.a\
../lib/$(PLAT)/libdynord.a\
../lib/$(PLAT)/libksvd2.a\
../lib/$(PLAT)/libfaux.a

EXES=$(EXES_BLKSVD) $(EXES_DYNORD) $(EXES_KSVD2) $(EXES_FAUX) $(EXES_TEST)
