OBJS_ARRBIO=\
../obj/$(PLAT)/bfopen.$(OXT)\
../obj/$(PLAT)/ibrd1.$(OXT)\
../obj/$(PLAT)/jbrd1.$(OXT)\
../obj/$(PLAT)/sbrd1.$(OXT)\
../obj/$(PLAT)/cbrd1.$(OXT)\
../obj/$(PLAT)/dbrd1.$(OXT)\
../obj/$(PLAT)/zbrd1.$(OXT)\
../obj/$(PLAT)/qbrd1.$(OXT)\
../obj/$(PLAT)/ybrd1.$(OXT)\
../obj/$(PLAT)/ibwr1.$(OXT)\
../obj/$(PLAT)/jbwr1.$(OXT)\
../obj/$(PLAT)/sbwr1.$(OXT)\
../obj/$(PLAT)/cbwr1.$(OXT)\
../obj/$(PLAT)/dbwr1.$(OXT)\
../obj/$(PLAT)/zbwr1.$(OXT)\
../obj/$(PLAT)/qbwr1.$(OXT)\
../obj/$(PLAT)/ybwr1.$(OXT)\
../obj/$(PLAT)/ibrd2.$(OXT)\
../obj/$(PLAT)/jbrd2.$(OXT)\
../obj/$(PLAT)/sbrd2.$(OXT)\
../obj/$(PLAT)/cbrd2.$(OXT)\
../obj/$(PLAT)/dbrd2.$(OXT)\
../obj/$(PLAT)/zbrd2.$(OXT)\
../obj/$(PLAT)/qbrd2.$(OXT)\
../obj/$(PLAT)/ybrd2.$(OXT)\
../obj/$(PLAT)/ibwr2.$(OXT)\
../obj/$(PLAT)/jbwr2.$(OXT)\
../obj/$(PLAT)/sbwr2.$(OXT)\
../obj/$(PLAT)/cbwr2.$(OXT)\
../obj/$(PLAT)/dbwr2.$(OXT)\
../obj/$(PLAT)/zbwr2.$(OXT)\
../obj/$(PLAT)/qbwr2.$(OXT)\
../obj/$(PLAT)/ybwr2.$(OXT)

OBJS_BLKSVD=\
../obj/$(PLAT)/nb2m.$(OXT)\
../obj/$(PLAT)/sbrdg.$(OXT)\
../obj/$(PLAT)/cbrdg.$(OXT)\
../obj/$(PLAT)/dbrdg.$(OXT)\
../obj/$(PLAT)/zbrdg.$(OXT)\
../obj/$(PLAT)/qbrdg.$(OXT)\
../obj/$(PLAT)/ybrdg.$(OXT)\
../obj/$(PLAT)/sksvd0.$(OXT)\
../obj/$(PLAT)/cksvd0.$(OXT)\
../obj/$(PLAT)/dksvd0.$(OXT)\
../obj/$(PLAT)/zksvd0.$(OXT)\
../obj/$(PLAT)/qksvd0.$(OXT)\
../obj/$(PLAT)/yksvd0.$(OXT)\
../obj/$(PLAT)/sksvdd.$(OXT)\
../obj/$(PLAT)/dksvdd.$(OXT)\
../obj/$(PLAT)/cksvdd.$(OXT)\
../obj/$(PLAT)/zksvdd.$(OXT)

OBJS_DYNORD=\
../obj/$(PLAT)/sabsg.$(OXT)\
../obj/$(PLAT)/cabsg.$(OXT)\
../obj/$(PLAT)/dabsg.$(OXT)\
../obj/$(PLAT)/zabsg.$(OXT)\
../obj/$(PLAT)/qabsg.$(OXT)\
../obj/$(PLAT)/yabsg.$(OXT)\
../obj/$(PLAT)/smkwpq.$(OXT)\
../obj/$(PLAT)/cmkwpq.$(OXT)\
../obj/$(PLAT)/dmkwpq.$(OXT)\
../obj/$(PLAT)/zmkwpq.$(OXT)\
../obj/$(PLAT)/qmkwpq.$(OXT)\
../obj/$(PLAT)/ymkwpq.$(OXT)\
../obj/$(PLAT)/smk3pq.$(OXT)\
../obj/$(PLAT)/cmk3pq.$(OXT)\
../obj/$(PLAT)/dmk3pq.$(OXT)\
../obj/$(PLAT)/zmk3pq.$(OXT)\
../obj/$(PLAT)/qmk3pq.$(OXT)\
../obj/$(PLAT)/ymk3pq.$(OXT)\
../obj/$(PLAT)/smkdpq.$(OXT)\
../obj/$(PLAT)/dmkdpq.$(OXT)\
../obj/$(PLAT)/cmkdpq.$(OXT)\
../obj/$(PLAT)/zmkdpq.$(OXT)\
../obj/$(PLAT)/spqcmp.$(OXT)\
../obj/$(PLAT)/dpqcmp.$(OXT)\
../obj/$(PLAT)/qpqcmp.$(OXT)\
../obj/$(PLAT)/spqmrg.$(OXT)\
../obj/$(PLAT)/dpqmrg.$(OXT)\
../obj/$(PLAT)/qpqmrg.$(OXT)\
../obj/$(PLAT)/spqsrt.$(OXT)\
../obj/$(PLAT)/dpqsrt.$(OXT)\
../obj/$(PLAT)/qpqsrt.$(OXT)

OBJS_KSVD2=\
../obj/$(PLAT)/sksvd2.$(OXT)\
../obj/$(PLAT)/cksvd2.$(OXT)\
../obj/$(PLAT)/dksvd2.$(OXT)\
../obj/$(PLAT)/zksvd2.$(OXT)\
../obj/$(PLAT)/qksvd2.$(OXT)\
../obj/$(PLAT)/yksvd2.$(OXT)\
../obj/$(PLAT)/scvgpp.$(OXT)\
../obj/$(PLAT)/ccvgpp.$(OXT)\
../obj/$(PLAT)/dcvgpp.$(OXT)\
../obj/$(PLAT)/zcvgpp.$(OXT)\
../obj/$(PLAT)/qcvgpp.$(OXT)\
../obj/$(PLAT)/ycvgpp.$(OXT)\
../obj/$(PLAT)/slmsv2.$(OXT)\
../obj/$(PLAT)/dlmsv2.$(OXT)\
../obj/$(PLAT)/qlmsv2.$(OXT)\
../obj/$(PLAT)/slwsv2.$(OXT)\
../obj/$(PLAT)/dlwsv2.$(OXT)\
../obj/$(PLAT)/qlwsv2.$(OXT)\
../obj/$(PLAT)/skerr2.$(OXT)\
../obj/$(PLAT)/ckerr2.$(OXT)\
../obj/$(PLAT)/dkerr2.$(OXT)\
../obj/$(PLAT)/zkerr2.$(OXT)\
../obj/$(PLAT)/qkerr2.$(OXT)\
../obj/$(PLAT)/ykerr2.$(OXT)

OBJS_FAUX=\
../obj/$(PLAT)/sthalt.$(OXT)\
../obj/$(PLAT)/cmul.$(OXT)\
../obj/$(PLAT)/zmul.$(OXT)\
../obj/$(PLAT)/ymul.$(OXT)\
../obj/$(PLAT)/cfma.$(OXT)\
../obj/$(PLAT)/zfma.$(OXT)\
../obj/$(PLAT)/yfma.$(OXT)\
../obj/$(PLAT)/slango.$(OXT)\
../obj/$(PLAT)/clango.$(OXT)\
../obj/$(PLAT)/dlango.$(OXT)\
../obj/$(PLAT)/zlango.$(OXT)\
../obj/$(PLAT)/qlango.$(OXT)\
../obj/$(PLAT)/ylango.$(OXT)\
../obj/$(PLAT)/srotc.$(OXT)\
../obj/$(PLAT)/srotca.$(OXT)\
../obj/$(PLAT)/crotc.$(OXT)\
../obj/$(PLAT)/crotca.$(OXT)\
../obj/$(PLAT)/drotc.$(OXT)\
../obj/$(PLAT)/drotca.$(OXT)\
../obj/$(PLAT)/drotcx.$(OXT)\
../obj/$(PLAT)/zrotc.$(OXT)\
../obj/$(PLAT)/zrotca.$(OXT)\
../obj/$(PLAT)/zrotcx.$(OXT)\
../obj/$(PLAT)/qrotc.$(OXT)\
../obj/$(PLAT)/yrotc.$(OXT)\
../obj/$(PLAT)/srotr.$(OXT)\
../obj/$(PLAT)/srotra.$(OXT)\
../obj/$(PLAT)/crotr.$(OXT)\
../obj/$(PLAT)/crotra.$(OXT)\
../obj/$(PLAT)/drotr.$(OXT)\
../obj/$(PLAT)/drotra.$(OXT)\
../obj/$(PLAT)/drotrx.$(OXT)\
../obj/$(PLAT)/zrotr.$(OXT)\
../obj/$(PLAT)/zrotra.$(OXT)\
../obj/$(PLAT)/zrotrx.$(OXT)\
../obj/$(PLAT)/qrotr.$(OXT)\
../obj/$(PLAT)/yrotr.$(OXT)\
../obj/$(PLAT)/sscalg.$(OXT)\
../obj/$(PLAT)/cscalg.$(OXT)\
../obj/$(PLAT)/dscalg.$(OXT)\
../obj/$(PLAT)/zscalg.$(OXT)\
../obj/$(PLAT)/qscalg.$(OXT)\
../obj/$(PLAT)/yscalg.$(OXT)\
../obj/$(PLAT)/jstep.$(OXT)\
../obj/$(PLAT)/jsweep.$(OXT)

EXES_BLKSVD=\
../bin/$(PLAT)/sksvd0.exe\
../bin/$(PLAT)/cksvd0.exe\
../bin/$(PLAT)/dksvd0.exe\
../bin/$(PLAT)/zksvd0.exe\
../bin/$(PLAT)/qksvd0.exe\
../bin/$(PLAT)/yksvd0.exe\
../bin/$(PLAT)/sksvdd.exe\
../bin/$(PLAT)/dksvdd.exe\
../bin/$(PLAT)/cksvdd.exe\
../bin/$(PLAT)/zksvdd.exe

EXES_DYNORD=\
../bin/$(PLAT)/spqsort.exe\
../bin/$(PLAT)/dpqsort.exe\
../bin/$(PLAT)/qpqsort.exe

EXES_KSVD2=\
../bin/$(PLAT)/sksvd2.exe\
../bin/$(PLAT)/cksvd2.exe\
../bin/$(PLAT)/dksvd2.exe\
../bin/$(PLAT)/zksvd2.exe\
../bin/$(PLAT)/qksvd2.exe\
../bin/$(PLAT)/yksvd2.exe\
../bin/$(PLAT)/slwsv2.exe\
../bin/$(PLAT)/dlwsv2.exe\
../bin/$(PLAT)/qlwsv2.exe

EXES_FAUX=\
../bin/$(PLAT)/sthalt.exe\
../bin/$(PLAT)/jsweep.exe

EXES_TEST=\
../bin/$(PLAT)/sran.exe\
../bin/$(PLAT)/cran.exe\
../bin/$(PLAT)/dran.exe\
../bin/$(PLAT)/zran.exe\
../bin/$(PLAT)/qran.exe\
../bin/$(PLAT)/yran.exe\
../bin/$(PLAT)/srnd.exe\
../bin/$(PLAT)/crnd.exe\
../bin/$(PLAT)/drnd.exe\
../bin/$(PLAT)/zrnd.exe\
../bin/$(PLAT)/qrnd.exe\
../bin/$(PLAT)/yrnd.exe\
../bin/$(PLAT)/sran2u.exe\
../bin/$(PLAT)/sran2g.exe\
../bin/$(PLAT)/cran2g.exe\
../bin/$(PLAT)/dran2u.exe\
../bin/$(PLAT)/dran2g.exe\
../bin/$(PLAT)/zran2g.exe\
../bin/$(PLAT)/qran2u.exe\
../bin/$(PLAT)/qran2g.exe\
../bin/$(PLAT)/yran2g.exe\
../bin/$(PLAT)/srnd2u.exe\
../bin/$(PLAT)/srnd2g.exe\
../bin/$(PLAT)/crnd2g.exe\
../bin/$(PLAT)/drnd2u.exe\
../bin/$(PLAT)/drnd2g.exe\
../bin/$(PLAT)/zrnd2g.exe\
../bin/$(PLAT)/qrnd2u.exe\
../bin/$(PLAT)/qrnd2g.exe\
../bin/$(PLAT)/yrnd2g.exe

ifeq ($(findstring 86,$(ARCH)),86)
OBJS_BLKSVD += \
../obj/$(PLAT)/xksvdd.$(OXT)\
../obj/$(PLAT)/wksvdd.$(OXT)
EXES_BLKSVD += \
../bin/$(PLAT)/xksvdd.exe\
../bin/$(PLAT)/wksvdd.exe
ifeq ($(COMPILER),gfortran)
OBJS_ARRBIO += \
../obj/$(PLAT)/xbrd1.$(OXT)\
../obj/$(PLAT)/wbrd1.$(OXT)\
../obj/$(PLAT)/xbwr1.$(OXT)\
../obj/$(PLAT)/wbwr1.$(OXT)\
../obj/$(PLAT)/xbrd2.$(OXT)\
../obj/$(PLAT)/wbrd2.$(OXT)\
../obj/$(PLAT)/xbwr2.$(OXT)\
../obj/$(PLAT)/wbwr2.$(OXT)
OBJS_BLKSVD += \
../obj/$(PLAT)/xbrdg.$(OXT)\
../obj/$(PLAT)/wbrdg.$(OXT)\
../obj/$(PLAT)/xksvd0.$(OXT)\
../obj/$(PLAT)/wksvd0.$(OXT)
OBJS_DYNORD += \
../obj/$(PLAT)/xabsg.$(OXT)\
../obj/$(PLAT)/wabsg.$(OXT)\
../obj/$(PLAT)/xmkwpq.$(OXT)\
../obj/$(PLAT)/wmkwpq.$(OXT)\
../obj/$(PLAT)/xmk3pq.$(OXT)\
../obj/$(PLAT)/wmk3pq.$(OXT)\
../obj/$(PLAT)/xmkdpq.$(OXT)\
../obj/$(PLAT)/wmkdpq.$(OXT)\
../obj/$(PLAT)/xpqcmp.$(OXT)\
../obj/$(PLAT)/xpqmrg.$(OXT)\
../obj/$(PLAT)/xpqsrt.$(OXT)
OBJS_KSVD2 += \
../obj/$(PLAT)/xksvd2.$(OXT)\
../obj/$(PLAT)/wksvd2.$(OXT)\
../obj/$(PLAT)/xcvgpp.$(OXT)\
../obj/$(PLAT)/wcvgpp.$(OXT)\
../obj/$(PLAT)/xlmsv2.$(OXT)\
../obj/$(PLAT)/xlwsv2.$(OXT)\
../obj/$(PLAT)/xkerr2.$(OXT)\
../obj/$(PLAT)/wkerr2.$(OXT)
OBJS_FAUX += \
../obj/$(PLAT)/wmul.$(OXT)\
../obj/$(PLAT)/wfma.$(OXT)\
../obj/$(PLAT)/xlango.$(OXT)\
../obj/$(PLAT)/wlango.$(OXT)\
../obj/$(PLAT)/xrotc.$(OXT)\
../obj/$(PLAT)/xrotca.$(OXT)\
../obj/$(PLAT)/wrotc.$(OXT)\
../obj/$(PLAT)/wrotca.$(OXT)\
../obj/$(PLAT)/xrotr.$(OXT)\
../obj/$(PLAT)/xrotra.$(OXT)\
../obj/$(PLAT)/wrotr.$(OXT)\
../obj/$(PLAT)/wrotra.$(OXT)\
../obj/$(PLAT)/xscalg.$(OXT)\
../obj/$(PLAT)/wscalg.$(OXT)
EXES_BLKSVD += \
../bin/$(PLAT)/xksvd0.exe\
../bin/$(PLAT)/wksvd0.exe
EXES_DYNORD += \
../bin/$(PLAT)/xpqsort.exe
EXES_KSVD2 += \
../bin/$(PLAT)/xksvd2.exe\
../bin/$(PLAT)/wksvd2.exe\
../bin/$(PLAT)/xlwsv2.exe
EXES_TEST += \
../bin/$(PLAT)/xran.exe\
../bin/$(PLAT)/wran.exe\
../bin/$(PLAT)/xrnd.exe\
../bin/$(PLAT)/wrnd.exe\
../bin/$(PLAT)/xran2u.exe\
../bin/$(PLAT)/xran2g.exe\
../bin/$(PLAT)/wran2g.exe\
../bin/$(PLAT)/xrnd2u.exe\
../bin/$(PLAT)/xrnd2g.exe\
../bin/$(PLAT)/wrnd2g.exe
endif # gfortran
endif # x86

OBJS=$(OBJS_ARRBIO) $(OBJS_BLKSVD) $(OBJS_DYNORD) $(OBJS_KSVD2) $(OBJS_FAUX)

LIBS=\
../lib/$(PLAT)/libarrbio.a\
../lib/$(PLAT)/libblksvd.a\
../lib/$(PLAT)/libdynord.a\
../lib/$(PLAT)/libksvd2.a\
../lib/$(PLAT)/libfaux.a

EXES=$(EXES_BLKSVD) $(EXES_DYNORD) $(EXES_KSVD2) $(EXES_FAUX) $(EXES_TEST)
