OBJS_ARRBIO=\
..\obj\$(PLAT)\bfopen.obj\
..\obj\$(PLAT)\ibrd1.obj\
..\obj\$(PLAT)\jbrd1.obj\
..\obj\$(PLAT)\sbrd1.obj\
..\obj\$(PLAT)\cbrd1.obj\
..\obj\$(PLAT)\dbrd1.obj\
..\obj\$(PLAT)\zbrd1.obj\
..\obj\$(PLAT)\qbrd1.obj\
..\obj\$(PLAT)\ybrd1.obj\
..\obj\$(PLAT)\ibwr1.obj\
..\obj\$(PLAT)\jbwr1.obj\
..\obj\$(PLAT)\sbwr1.obj\
..\obj\$(PLAT)\cbwr1.obj\
..\obj\$(PLAT)\dbwr1.obj\
..\obj\$(PLAT)\zbwr1.obj\
..\obj\$(PLAT)\qbwr1.obj\
..\obj\$(PLAT)\ybwr1.obj\
..\obj\$(PLAT)\ibrd2.obj\
..\obj\$(PLAT)\jbrd2.obj\
..\obj\$(PLAT)\sbrd2.obj\
..\obj\$(PLAT)\cbrd2.obj\
..\obj\$(PLAT)\dbrd2.obj\
..\obj\$(PLAT)\zbrd2.obj\
..\obj\$(PLAT)\qbrd2.obj\
..\obj\$(PLAT)\ybrd2.obj\
..\obj\$(PLAT)\ibwr2.obj\
..\obj\$(PLAT)\jbwr2.obj\
..\obj\$(PLAT)\sbwr2.obj\
..\obj\$(PLAT)\cbwr2.obj\
..\obj\$(PLAT)\dbwr2.obj\
..\obj\$(PLAT)\zbwr2.obj\
..\obj\$(PLAT)\qbwr2.obj\
..\obj\$(PLAT)\ybwr2.obj

OBJS_BLKSVD=\
..\obj\$(PLAT)\sbrdg.obj\
..\obj\$(PLAT)\cbrdg.obj\
..\obj\$(PLAT)\dbrdg.obj\
..\obj\$(PLAT)\zbrdg.obj\
..\obj\$(PLAT)\qbrdg.obj\
..\obj\$(PLAT)\ybrdg.obj\
..\obj\$(PLAT)\sbordg.obj\
..\obj\$(PLAT)\cbordg.obj\
..\obj\$(PLAT)\dbordg.obj\
..\obj\$(PLAT)\zbordg.obj\
..\obj\$(PLAT)\qbordg.obj\
..\obj\$(PLAT)\ybordg.obj\
..\obj\$(PLAT)\nb2m.obj

OBJS_DYNORD=\
..\obj\$(PLAT)\sabsg.obj\
..\obj\$(PLAT)\cabsg.obj\
..\obj\$(PLAT)\dabsg.obj\
..\obj\$(PLAT)\zabsg.obj\
..\obj\$(PLAT)\qabsg.obj\
..\obj\$(PLAT)\yabsg.obj\
..\obj\$(PLAT)\sabsog.obj\
..\obj\$(PLAT)\cabsog.obj\
..\obj\$(PLAT)\dabsog.obj\
..\obj\$(PLAT)\zabsog.obj\
..\obj\$(PLAT)\qabsog.obj\
..\obj\$(PLAT)\yabsog.obj\
..\obj\$(PLAT)\smkwpq.obj\
..\obj\$(PLAT)\dmkwpq.obj\
..\obj\$(PLAT)\qmkwpq.obj\
..\obj\$(PLAT)\smk1pq.obj\
..\obj\$(PLAT)\cmk1pq.obj\
..\obj\$(PLAT)\dmk1pq.obj\
..\obj\$(PLAT)\zmk1pq.obj\
..\obj\$(PLAT)\qmk1pq.obj\
..\obj\$(PLAT)\ymk1pq.obj\
..\obj\$(PLAT)\spqcmp.obj\
..\obj\$(PLAT)\dpqcmp.obj\
..\obj\$(PLAT)\qpqcmp.obj\
..\obj\$(PLAT)\spqmrg.obj\
..\obj\$(PLAT)\dpqmrg.obj\
..\obj\$(PLAT)\qpqmrg.obj\
..\obj\$(PLAT)\spqsrt.obj\
..\obj\$(PLAT)\dpqsrt.obj\
..\obj\$(PLAT)\qpqsrt.obj\
..\obj\$(PLAT)\spqsort.obj\
..\obj\$(PLAT)\dpqsort.obj\
..\obj\$(PLAT)\qpqsort.obj

OBJS_KSVD2=\
..\obj\$(PLAT)\sksvd2.obj\
..\obj\$(PLAT)\cksvd2.obj\
..\obj\$(PLAT)\dksvd2.obj\
..\obj\$(PLAT)\zksvd2.obj\
..\obj\$(PLAT)\qksvd2.obj\
..\obj\$(PLAT)\yksvd2.obj\
..\obj\$(PLAT)\slwsv2.obj\
..\obj\$(PLAT)\dlwsv2.obj

OBJS_FAUX=\
..\obj\$(PLAT)\sthalt.obj\
..\obj\$(PLAT)\slango.obj\
..\obj\$(PLAT)\clango.obj\
..\obj\$(PLAT)\dlango.obj\
..\obj\$(PLAT)\zlango.obj\
..\obj\$(PLAT)\sosum4.obj\
..\obj\$(PLAT)\dosum4.obj\
..\obj\$(PLAT)\srotc.obj\
..\obj\$(PLAT)\crotc.obj\
..\obj\$(PLAT)\drotc.obj\
..\obj\$(PLAT)\zrotc.obj\
..\obj\$(PLAT)\qrotc.obj\
..\obj\$(PLAT)\yrotc.obj

EXES_DYNORD=\
..\bin\$(PLAT)\spqsort.exe\
..\bin\$(PLAT)\dpqsort.exe\
..\bin\$(PLAT)\qpqsort.exe

EXES_KSVD2=\
..\bin\$(PLAT)\sksvd2.exe\
..\bin\$(PLAT)\cksvd2.exe\
..\bin\$(PLAT)\dksvd2.exe\
..\bin\$(PLAT)\zksvd2.exe\
..\bin\$(PLAT)\qksvd2.exe\
..\bin\$(PLAT)\yksvd2.exe\
..\bin\$(PLAT)\slwsv2.exe\
..\bin\$(PLAT)\dlwsv2.exe\
..\bin\$(PLAT)\srnd.exe

OBJS=$(OBJS_ARRBIO) $(OBJS_BLKSVD) $(OBJS_DYNORD) $(OBJS_KSVD2) $(OBJS_FAUX)

LIBS=\
..\lib\$(PLAT)\arrbio.lib\
..\lib\$(PLAT)\blksvd.lib\
..\lib\$(PLAT)\dynord.lib\
..\lib\$(PLAT)\ksvd2.lib\
..\lib\$(PLAT)\faux.lib

EXES=$(EXES_KSVD2) $(EXES_DYNORD)
