OBJS_ARRBIO=\
..\obj\$(PLAT)\bfopen.obj\
..\obj\$(PLAT)\ibrd1.obj\
..\obj\$(PLAT)\jbrd1.obj\
..\obj\$(PLAT)\sbrd1.obj\
..\obj\$(PLAT)\cbrd1.obj\
..\obj\$(PLAT)\dbrd1.obj\
..\obj\$(PLAT)\zbrd1.obj\
..\obj\$(PLAT)\qbrd1.obj\
..\obj\$(PLAT)\ybrd1.obj\
..\obj\$(PLAT)\ibwr1.obj\
..\obj\$(PLAT)\jbwr1.obj\
..\obj\$(PLAT)\sbwr1.obj\
..\obj\$(PLAT)\cbwr1.obj\
..\obj\$(PLAT)\dbwr1.obj\
..\obj\$(PLAT)\zbwr1.obj\
..\obj\$(PLAT)\qbwr1.obj\
..\obj\$(PLAT)\ybwr1.obj\
..\obj\$(PLAT)\ibrd2.obj\
..\obj\$(PLAT)\jbrd2.obj\
..\obj\$(PLAT)\sbrd2.obj\
..\obj\$(PLAT)\cbrd2.obj\
..\obj\$(PLAT)\dbrd2.obj\
..\obj\$(PLAT)\zbrd2.obj\
..\obj\$(PLAT)\qbrd2.obj\
..\obj\$(PLAT)\ybrd2.obj\
..\obj\$(PLAT)\ibwr2.obj\
..\obj\$(PLAT)\jbwr2.obj\
..\obj\$(PLAT)\sbwr2.obj\
..\obj\$(PLAT)\cbwr2.obj\
..\obj\$(PLAT)\dbwr2.obj\
..\obj\$(PLAT)\zbwr2.obj\
..\obj\$(PLAT)\qbwr2.obj\
..\obj\$(PLAT)\ybwr2.obj\
..\obj\$(PLAT)\swrout.obj\
..\obj\$(PLAT)\cwrout.obj\
..\obj\$(PLAT)\dwrout.obj\
..\obj\$(PLAT)\zwrout.obj\
..\obj\$(PLAT)\qwrout.obj\
..\obj\$(PLAT)\ywrout.obj\
..\obj\$(PLAT)\srdinp.obj\
..\obj\$(PLAT)\crdinp.obj\
..\obj\$(PLAT)\drdinp.obj\
..\obj\$(PLAT)\zrdinp.obj\
..\obj\$(PLAT)\qrdinp.obj\
..\obj\$(PLAT)\yrdinp.obj

OBJS_BLKSVD=\
..\obj\$(PLAT)\nb2m.obj\
..\obj\$(PLAT)\sbrdg.obj\
..\obj\$(PLAT)\cbrdg.obj\
..\obj\$(PLAT)\dbrdg.obj\
..\obj\$(PLAT)\zbrdg.obj\
..\obj\$(PLAT)\qbrdg.obj\
..\obj\$(PLAT)\ybrdg.obj\
..\obj\$(PLAT)\sksvd0.obj\
..\obj\$(PLAT)\cksvd0.obj\
..\obj\$(PLAT)\dksvd0.obj\
..\obj\$(PLAT)\zksvd0.obj\
..\obj\$(PLAT)\qksvd0.obj\
..\obj\$(PLAT)\yksvd0.obj

OBJS_DYNORD=\
..\obj\$(PLAT)\sabsg.obj\
..\obj\$(PLAT)\cabsg.obj\
..\obj\$(PLAT)\dabsg.obj\
..\obj\$(PLAT)\zabsg.obj\
..\obj\$(PLAT)\qabsg.obj\
..\obj\$(PLAT)\yabsg.obj\
..\obj\$(PLAT)\smkwpq.obj\
..\obj\$(PLAT)\cmkwpq.obj\
..\obj\$(PLAT)\dmkwpq.obj\
..\obj\$(PLAT)\zmkwpq.obj\
..\obj\$(PLAT)\qmkwpq.obj\
..\obj\$(PLAT)\ymkwpq.obj\
..\obj\$(PLAT)\smk3pq.obj\
..\obj\$(PLAT)\cmk3pq.obj\
..\obj\$(PLAT)\dmk3pq.obj\
..\obj\$(PLAT)\zmk3pq.obj\
..\obj\$(PLAT)\qmk3pq.obj\
..\obj\$(PLAT)\ymk3pq.obj\
..\obj\$(PLAT)\spqcmp.obj\
..\obj\$(PLAT)\dpqcmp.obj\
..\obj\$(PLAT)\qpqcmp.obj\
..\obj\$(PLAT)\spqmrg.obj\
..\obj\$(PLAT)\dpqmrg.obj\
..\obj\$(PLAT)\qpqmrg.obj\
..\obj\$(PLAT)\spqsrt.obj\
..\obj\$(PLAT)\dpqsrt.obj\
..\obj\$(PLAT)\qpqsrt.obj

OBJS_KSVD2=\
..\obj\$(PLAT)\sksvd2.obj\
..\obj\$(PLAT)\cksvd2.obj\
..\obj\$(PLAT)\dksvd2.obj\
..\obj\$(PLAT)\zksvd2.obj\
..\obj\$(PLAT)\qksvd2.obj\
..\obj\$(PLAT)\yksvd2.obj\
..\obj\$(PLAT)\scvgpp.obj\
..\obj\$(PLAT)\ccvgpp.obj\
..\obj\$(PLAT)\dcvgpp.obj\
..\obj\$(PLAT)\zcvgpp.obj\
..\obj\$(PLAT)\qcvgpp.obj\
..\obj\$(PLAT)\ycvgpp.obj\
..\obj\$(PLAT)\slwsv2.obj\
..\obj\$(PLAT)\dlwsv2.obj

OBJS_FAUX=\
..\obj\$(PLAT)\sthalt.obj\
..\obj\$(PLAT)\slango.obj\
..\obj\$(PLAT)\clango.obj\
..\obj\$(PLAT)\dlango.obj\
..\obj\$(PLAT)\zlango.obj\
..\obj\$(PLAT)\qlango.obj\
..\obj\$(PLAT)\ylango.obj\
..\obj\$(PLAT)\srotc.obj\
..\obj\$(PLAT)\crotc.obj\
..\obj\$(PLAT)\drotc.obj\
..\obj\$(PLAT)\zrotc.obj\
..\obj\$(PLAT)\qrotc.obj\
..\obj\$(PLAT)\yrotc.obj\
..\obj\$(PLAT)\srotr.obj\
..\obj\$(PLAT)\crotr.obj\
..\obj\$(PLAT)\drotr.obj\
..\obj\$(PLAT)\zrotr.obj\
..\obj\$(PLAT)\qrotr.obj\
..\obj\$(PLAT)\yrotr.obj\
..\obj\$(PLAT)\sscalg.obj\
..\obj\$(PLAT)\cscalg.obj\
..\obj\$(PLAT)\dscalg.obj\
..\obj\$(PLAT)\zscalg.obj\
..\obj\$(PLAT)\qscalg.obj\
..\obj\$(PLAT)\yscalg.obj\
..\obj\$(PLAT)\jstep.obj\
..\obj\$(PLAT)\jsweep.obj

EXES_BLKSVD=\
..\bin\$(PLAT)\sksvd0.exe\
..\bin\$(PLAT)\cksvd0.exe\
..\bin\$(PLAT)\dksvd0.exe\
..\bin\$(PLAT)\zksvd0.exe\
..\bin\$(PLAT)\qksvd0.exe\
..\bin\$(PLAT)\yksvd0.exe

EXES_DYNORD=\
..\bin\$(PLAT)\spqsort.exe\
..\bin\$(PLAT)\dpqsort.exe\
..\bin\$(PLAT)\qpqsort.exe

EXES_KSVD2=\
..\bin\$(PLAT)\sksvd2.exe\
..\bin\$(PLAT)\cksvd2.exe\
..\bin\$(PLAT)\dksvd2.exe\
..\bin\$(PLAT)\zksvd2.exe\
..\bin\$(PLAT)\qksvd2.exe\
..\bin\$(PLAT)\yksvd2.exe\
..\bin\$(PLAT)\slwsv2.exe\
..\bin\$(PLAT)\dlwsv2.exe

EXES_FAUX=\
..\bin\$(PLAT)\sthalt.exe\
..\bin\$(PLAT)\jsweep.exe

EXES_TEST=\
..\bin\$(PLAT)\srnd.exe\
..\bin\$(PLAT)\crnd.exe\
..\bin\$(PLAT)\drnd.exe\
..\bin\$(PLAT)\zrnd.exe\
..\bin\$(PLAT)\qrnd.exe\
..\bin\$(PLAT)\yrnd.exe\
..\bin\$(PLAT)\s2g101.exe\
..\bin\$(PLAT)\s2g110.exe

OBJS=$(OBJS_ARRBIO) $(OBJS_BLKSVD) $(OBJS_DYNORD) $(OBJS_KSVD2) $(OBJS_FAUX)

LIBS=\
..\lib\$(PLAT)\arrbio.lib\
..\lib\$(PLAT)\blksvd.lib\
..\lib\$(PLAT)\dynord.lib\
..\lib\$(PLAT)\ksvd2.lib\
..\lib\$(PLAT)\faux.lib

EXES=$(EXES_BLKSVD) $(EXES_DYNORD) $(EXES_KSVD2) $(EXES_FAUX) $(EXES_TEST)
