SUBROUTINE QKSVD2(G, U, V, S, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE

  INTEGER, PARAMETER :: IERR = -HUGE(0)
  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128, ONE = 1.0_REAL128

  REAL(KIND=REAL128), INTENT(IN) :: G(2,2)
  REAL(KIND=REAL128), INTENT(OUT) :: U(2,2), V(2,2), S(2)
  INTEGER, INTENT(OUT) :: INFO

  INFO = 0
END SUBROUTINE QKSVD2
