!>@brief \b QKSVD2X tests the QKSVD2 routine.
PROGRAM QKSVD2X
  IMPLICIT NONE
  EXTERNAL :: QKSVD2
  CALL QTEST(QKSVD2)
CONTAINS
  !>@brief \b QTEST calls KSVD2.
  !!
  !!@param KSVD2 is QKSVD2.
  SUBROUTINE QTEST(KSVD2)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
    IMPLICIT NONE
    INTEGER, PARAMETER :: IERR = -HUGE(0), KX = REAL128, CLAL = 64
    EXTERNAL :: KSVD2
    CHARACTER(LEN=CLAL) :: CLA
    REAL(KIND=REAL128) :: G(2,2), U(2,2), V(2,2), S(2)
    INTEGER :: INFO
    REAL(KIND=KX) :: GX(2,2), UX(2,2), VX(2,2), SX(2,2)
    INCLUDE 'tksvd2.f90'
1   FORMAT(A,ES45.36E4)
2   FORMAT(A,I6)
  END SUBROUTINE QTEST
END PROGRAM QKSVD2X
