SUBROUTINE SKSVD2
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA, IEEE_MAX_NUM, IEEE_MIN_NUM
#endif
  IMPLICIT NONE
#ifndef USE_IEEE_INTRINSIC
  INTERFACE
     FUNCTION IEEE_FMA(X, Y, Z) BIND(C,NAME='fmaf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y, Z
       REAL(KIND=c_float) :: IEEE_FMA
     END FUNCTION IEEE_FMA
  END INTERFACE
  INTERFACE
     FUNCTION IEEE_MAX_NUM(X, Y) BIND(C,NAME='fmaxf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: IEEE_MAX_NUM
     END FUNCTION IEEE_MAX_NUM
  END INTERFACE
  INTERFACE
     FUNCTION IEEE_MIN_NUM(X, Y) BIND(C,NAME='fminf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: IEEE_MIN_NUM
     END FUNCTION IEEE_MIN_NUM
  END INTERFACE
#endif
END SUBROUTINE SKSVD2
