!>@brief \b STHALT writes MSG and the stack trace to ERROR_UNIT and stops the program.
SUBROUTINE STHALT(MSG)
  USE IFCORE
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  CALL TRACEBACKQQ(NEW_LINE(MSG)//TRIM(MSG), -1_4)
  STOP
END SUBROUTINE STHALT
