!>@brief \b STHALT writes MSG and the stack trace to ERROR_UNIT and stops the program.
SUBROUTINE STHALT(MSG)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  WRITE (ERROR_UNIT,'(A)') NEW_LINE(MSG)//TRIM(MSG)
  CALL BACKTRACE
  STOP
END SUBROUTINE STHALT
