!>@brief \b STHALT writes MSG and the stack trace to ERROR_UNIT and stops the program.
SUBROUTINE STHALT(MSG)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
#else
  USE IFCORE, ONLY: TRACEBACKQQ
#endif
  USE OMP_LIB, ONLY: OMP_GET_THREAD_NUM
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  CHARACTER(LEN=6) :: THR
  WRITE (THR,'(A,I3,A)') '[', OMP_GET_THREAD_NUM(), '] '
#ifdef __GFORTRAN__
  WRITE (ERROR_UNIT,'(A)') NEW_LINE(MSG)//THR//TRIM(MSG)
  CALL BACKTRACE
#else
  CALL TRACEBACKQQ(NEW_LINE(MSG)//THR//TRIM(MSG), -1_4)
#endif
  STOP
END SUBROUTINE STHALT
