!>@brief \b STHALT writes MSG and the stack trace to ERROR_UNIT and stops the program.
SUBROUTINE STHALT(MSG)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
  USE OMP_LIB, ONLY: OMP_GET_THREAD_NUM
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  CHARACTER(LEN=6) :: THR
  WRITE (THR,'(A,I3,A)') '[', OMP_GET_THREAD_NUM(), '] '
  WRITE (ERROR_UNIT,'(A)') NEW_LINE(MSG)//THR//TRIM(MSG)
  CALL BACKTRACE
  STOP
END SUBROUTINE STHALT
