!>@brief \b STHALT writes MSG and the stack trace to ERROR_UNIT and stops the program.
SUBROUTINE STHALT(MSG)
  USE IFCORE, ONLY: TRACEBACKQQ
  USE OMP_LIB, ONLY: OMP_GET_THREAD_NUM
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  CHARACTER(LEN=6) :: THR
  WRITE (THR,'(A,I3,A)') '[', OMP_GET_THREAD_NUM(), '] '
  CALL TRACEBACKQQ(NEW_LINE(MSG)//THR//TRIM(MSG), -1_4)
  STOP
END SUBROUTINE STHALT
