SUBROUTINE XKSVD2(G, U, V, S, INFO)
  IMPLICIT NONE

  INTEGER, PARAMETER :: REAL80 = 10, IERR = -HUGE(0)
  REAL(KIND=REAL80), PARAMETER :: ZERO = 0.0_REAL80, ONE = 1.0_REAL80

  REAL(KIND=REAL80), INTENT(IN) :: G(2,2)
  REAL(KIND=REAL80), INTENT(OUT) :: U(2,2), V(2,2), S(2)
  INTEGER, INTENT(OUT) :: INFO

  INFO = 0
END SUBROUTINE XKSVD2
