SUBROUTINE XKSVD2
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA, IEEE_MAX_NUM, IEEE_MIN_NUM
#endif
  IMPLICIT NONE
#ifndef USE_IEEE_INTRINSIC
#ifdef EXTENDED_KIND
  INTERFACE
     FUNCTION IEEE_FMA(X, Y, Z) BIND(C,NAME='fmal')
       REAL(KIND=EXTENDED_KIND), INTENT(IN), VALUE :: X, Y, Z
       REAL(KIND=EXTENDED_KIND) :: IEEE_FMA
     END FUNCTION IEEE_FMA
  END INTERFACE
  INTERFACE
     FUNCTION IEEE_MAX_NUM(X, Y) BIND(C,NAME='fmaxl')
       REAL(KIND=EXTENDED_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=EXTENDED_KIND) :: IEEE_MAX_NUM
     END FUNCTION IEEE_MAX_NUM
  END INTERFACE
  INTERFACE
     FUNCTION IEEE_MIN_NUM(X, Y) BIND(C,NAME='fminl')
       REAL(KIND=EXTENDED_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=EXTENDED_KIND) :: IEEE_MIN_NUM
     END FUNCTION IEEE_MIN_NUM
  END INTERFACE
#else
#error extended precision not supported
#endif
#endif
END SUBROUTINE XKSVD2
