../obj/$(PLAT)/qbrd1.$(OXT): arrbio/qbrd1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbrd1.F90

../obj/$(PLAT)/ybrd1.$(OXT): arrbio/ybrd1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybrd1.F90

../obj/$(PLAT)/xbrd1.$(OXT): arrbio/xbrd1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbrd1.F90

../obj/$(PLAT)/wbrd1.$(OXT): arrbio/wbrd1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbrd1.F90

../obj/$(PLAT)/qbwr1.$(OXT): arrbio/qbwr1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbwr1.F90

../obj/$(PLAT)/ybwr1.$(OXT): arrbio/ybwr1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybwr1.F90

../obj/$(PLAT)/xbwr1.$(OXT): arrbio/xbwr1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbwr1.F90

../obj/$(PLAT)/wbwr1.$(OXT): arrbio/wbwr1.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbwr1.F90

../obj/$(PLAT)/qbrd2.$(OXT): arrbio/qbrd2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbrd2.F90

../obj/$(PLAT)/ybrd2.$(OXT): arrbio/ybrd2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybrd2.F90

../obj/$(PLAT)/xbrd2.$(OXT): arrbio/xbrd2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbrd2.F90

../obj/$(PLAT)/wbrd2.$(OXT): arrbio/wbrd2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbrd2.F90

../obj/$(PLAT)/qbwr2.$(OXT): arrbio/qbwr2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/qbwr2.F90

../obj/$(PLAT)/ybwr2.$(OXT): arrbio/ybwr2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/ybwr2.F90

../obj/$(PLAT)/xbwr2.$(OXT): arrbio/xbwr2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/xbwr2.F90

../obj/$(PLAT)/wbwr2.$(OXT): arrbio/wbwr2.F90 $(MKFS) arrbio/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/arrbio/wbwr2.F90
