!>@brief \b CMK1PQ builds at most one \f$(p,q)\f$ pivot index pair for the next transformation of \f$G\f$.
SUBROUTINE CMK1PQ(K, N, G, LDG, W, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32
  INTEGER, INTENT(IN) :: K, N, LDG
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL32), INTENT(OUT) :: W(N*N)
  INTEGER, INTENT(OUT) :: O(2*N*(N-1)), INFO
  INTEGER :: M, M_2
  EXTERNAL :: CABSG, SMKWPQ, SPQSRT
#define ABSG CABSG
#define MKWPQ SMKWPQ
#define PQSRT SPQSRT
#include "gmk1pq.F90"
END SUBROUTINE CMK1PQ
