!>@brief \b CMKBPQ computes O from G w.r.t. B.
SUBROUTINE CMKBPQ(N, G, LDG, B, W, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
#ifndef __GFORTRAN__
  INTERFACE
     SUBROUTINE CNRM2B(N, G, LDG, B, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG, B
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: W(N/B,N/B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CNRM2B
  END INTERFACE
  INTERFACE
     SUBROUTINE SB2ENC(N, W, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, O(2,*)
       REAL(KIND=REAL32), INTENT(IN) :: W(N,N)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SB2ENC
  END INTERFACE
  INTERFACE
     SUBROUTINE CMKDPQ(N, G, LDG, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: O(2,*), INFO
     END SUBROUTINE CMKDPQ
  END INTERFACE
#endif
  INTEGER, INTENT(IN) :: N, LDG, B
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL32), INTENT(OUT) :: W(N/B,N/B)
  REAL(KIND=REAL64), INTENT(OUT) :: D(*)
  INTEGER, INTENT(INOUT) :: O(2,*), INFO
#ifdef __GFORTRAN__
  EXTERNAL :: CNRM2B, SB2ENC, CMKDPQ
#endif
  INTEGER :: K, L, M
#define NRM2B CNRM2B
#define B2ENC SB2ENC
#define MKDPQ CMKDPQ
#include "gmkbpq.F90"
END SUBROUTINE CMKBPQ
