!>@brief \b CMKBPQ computes OD from G w.r.t. B.
SUBROUTINE CMKBPQ(M, G, LDG, B, W, D, O, OD, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE CNRM2B(M, G, LDG, B, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, LDG, B
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,M)
       REAL(KIND=REAL32), INTENT(OUT) :: W(M/B,M/B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CNRM2B
  END INTERFACE
  INTERFACE
     SUBROUTINE SB2ENC(N, W, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, O(2,*)
       REAL(KIND=REAL32), INTENT(IN) :: W(N,N)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SB2ENC
  END INTERFACE
  INTERFACE
     SUBROUTINE SMKDPQ(N, M, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, M
       REAL(KIND=REAL64), INTENT(INOUT) :: D(M+1)
       INTEGER, INTENT(OUT) :: O(2,N/2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SMKDPQ
  END INTERFACE

  INTEGER, INTENT(IN) :: M, LDG, B, O(2,*)
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,M)
  REAL(KIND=REAL32), INTENT(OUT) :: W(M/B,M/B)
  REAL(KIND=REAL64), INTENT(OUT) :: D(*)
  INTEGER, INTENT(OUT) :: OD(2,*)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: K, L, N
#define NRM2B CNRM2B
#define B2ENC SB2ENC
#define MKDPQ SMKDPQ
#include "gmkbpq.F90"
END SUBROUTINE CMKBPQ
