!>@brief \b CMKDPQ builds N/2 pivot index pairs for the next transformation of G.
SUBROUTINE CMKDPQ(N, G, LDG, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE SUBROUTINE DENC(E, S, P, Q) BIND(C,NAME='pvn_djs_denc_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       REAL(KIND=REAL64), INTENT(OUT) :: E
       REAL(KIND=REAL32), INTENT(IN) :: S
       INTEGER, INTENT(IN) :: P, Q
     END SUBROUTINE DENC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DDEC(E, P, Q) BIND(C,NAME='pvn_djs_ddec_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       REAL(KIND=REAL64), INTENT(IN) :: E
       INTEGER, INTENT(OUT) :: P, Q
     END SUBROUTINE DDEC
  END INTERFACE

  REAL(KIND=REAL64), PARAMETER :: WZERO = 0.0_REAL64, MONE = -1.0_REAL64
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32, ONE = 1.0_REAL32

  INTEGER, INTENT(IN) :: N, LDG
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL64), INTENT(OUT) :: D(*)
  INTEGER, INTENT(INOUT) :: O(2,*), INFO

  REAL(KIND=REAL64) :: W
  REAL(KIND=REAL32) :: H
  INTEGER :: I, J, K, L, M, P, Q, R

  L = INFO
  INFO = 0
  IF (LDG .LT. N) INFO = -3
  IF (N .LT. 0) INFO = -1
  IF (N .GT. 16384) INFO = -1
  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN
#define XENC DENC
#define XDEC DDEC
#include "hmkdpq.F90"
END SUBROUTINE CMKDPQ
