!>@brief \b CNRM2B computes ||off(X)||_F or ||X||_F for all BxB blocks X of G.
SUBROUTINE CNRM2B(M, G, LDG, B, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE FUNCTION CNRM2O(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, INFO
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32) :: CNRM2O
     END FUNCTION CNRM2O
  END INTERFACE

  INTEGER, INTENT(IN) :: M, LDG, B
  COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,M)
  REAL(KIND=REAL32), INTENT(OUT) :: W(M/B,M/B)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, N, P, Q
#define NRM2O CNRM2O
#include "gnrm2b.F90"
END SUBROUTINE CNRM2B
