!>@brief \b DABSG sequentially computes \f$W=|G|\f$.
PURE SUBROUTINE DABSG(M, N, G, LDG, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  REAL(KIND=REAL64), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL64), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL64) :: H
  INTEGER :: I, J
#include "gabsg.F90"
END SUBROUTINE DABSG
