!>@brief \b DB2ENC computes D from W.
SUBROUTINE DB2ENC(N, W, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE SUBROUTINE QENC(E, S, P, Q) BIND(C,NAME='pvn_djs_qenc_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
       REAL(KIND=REAL128), INTENT(OUT) :: E
       REAL(KIND=REAL64), INTENT(IN) :: S
       INTEGER, INTENT(IN) :: P, Q
     END SUBROUTINE QENC
  END INTERFACE

  REAL(KIND=REAL128), PARAMETER :: MONE = -1.0_REAL128
  INTEGER, INTENT(IN) :: N, O(2,*)
  REAL(KIND=REAL64), INTENT(IN) :: W(N,N)
  REAL(KIND=REAL128), INTENT(OUT) :: D(*)
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=REAL128) :: X
  REAL(KIND=REAL64) :: H
  INTEGER :: K, L, M, P, Q
#define XENC QENC
#include "gb2enc.F90"
END SUBROUTINE DB2ENC
