!>@brief \b DMKDPQ builds at most N/2 pivot index pairs for the next transformation of G.
SUBROUTINE DMKDPQ(N, M, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE QDEC(E, P, Q) BIND(C,NAME='pvn_djs_qdec_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: E
       INTEGER, INTENT(OUT) :: P, Q
     END SUBROUTINE QDEC
  END INTERFACE

  REAL(KIND=REAL128), PARAMETER :: WZERO = 0.0_REAL128
  INTEGER, INTENT(IN) :: N, M
  REAL(KIND=REAL128), INTENT(INOUT) :: D(M+1)
  INTEGER, INTENT(OUT) :: O(2,N/2)
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=REAL128) :: W
  INTEGER :: I, J, K, L, P, Q, R
#define XDEC QDEC
#include "gmkdpq.F90"
END SUBROUTINE DMKDPQ
