!>@brief \b DNRM2B computes ||off(X)||_F or ||X||_F for all 2Bx2B blocks X of G.
SUBROUTINE DNRM2B(N, G, LDG, B, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE FUNCTION DNRM2O(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, INFO
       REAL(KIND=REAL64), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64) :: DNRM2O
     END FUNCTION DNRM2O
  END INTERFACE

  INTEGER, INTENT(IN) :: N, LDG, B
  REAL(KIND=REAL64), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL64), INTENT(OUT) :: W((N/B)*(N/B))
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: N_B, I, J, K, L, M, P, Q
#define NRM2O DNRM2O
#include "gnrm2b.F90"
END SUBROUTINE DNRM2B
