!>@brief \b DPQSRT sorts the arrays AW,AP,AQ by the merge sort algorithm, using the workspace arrays BW,BP,BQ of the same length N, according to the ordering defined by the WPQCMP subroutine, and returns a non-negative value in INFO if successful, or a negative value on failure.
SUBROUTINE DPQSRT(WPQCMP, N, AW, AP, AQ, BW, BP, BQ, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE

  ABSTRACT INTERFACE
     PURE SUBROUTINE PQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
       REAL(KIND=REAL64), INTENT(IN) :: XW, YW
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE PQCMP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DPQMRG(WPQCMP, M, N, AW, AP, AQ, BW, BP, BQ, XW, XP, XQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       ABSTRACT INTERFACE
          PURE SUBROUTINE PQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
            USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
            IMPLICIT NONE
            INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
            REAL(KIND=REAL64), INTENT(IN) :: XW, YW
            INTEGER, INTENT(OUT) :: INFO
          END SUBROUTINE PQCMP
       END INTERFACE
       INTEGER, INTENT(IN) :: M, N, AP(M), AQ(M), BP(N), BQ(N)
       REAL(KIND=REAL64), INTENT(IN) :: AW(M), BW(N)
       REAL(KIND=REAL64), INTENT(OUT) :: XW(M+N)
       INTEGER, INTENT(OUT) :: XP(M+N), XQ(M+N), INFO
       PROCEDURE(PQCMP) :: WPQCMP
     END SUBROUTINE DPQMRG
  END INTERFACE

  INTEGER, INTENT(IN) :: N
  REAL(KIND=REAL64), INTENT(INOUT) :: AW(N)
  INTEGER, INTENT(INOUT) :: AP(N), AQ(N), INFO
  REAL(KIND=REAL64), INTENT(OUT) :: BW(N)
  INTEGER, INTENT(OUT) :: BP(N), BQ(N)
  PROCEDURE(PQCMP) :: WPQCMP
  INTEGER :: I, J, K, L, M, X, Y, Z
  LOGICAL :: FLIP
#define WPQMRG DPQMRG
#include "gpqsrt.F90"
END SUBROUTINE DPQSRT
