PURE FUNCTION DENC(S, P, Q)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64
  IMPLICIT NONE
  REAL(KIND=REAL32), INTENT(IN) :: S
  INTEGER, INTENT(IN) :: P, Q
  REAL(KIND=REAL64) :: DENC
  DENC = TRANSFER(&
       IOR(TRANSFER(REAL(S,REAL64), 0_INT64), IOR(ISHFT(INT(IAND(P-1,16383),INT64),14), INT(IAND(Q-1,16383),INT64))), DENC)
END FUNCTION DENC

PURE SUBROUTINE DDEC(D, P, Q)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), INTENT(IN) :: D
  INTEGER, INTENT(OUT) :: P, Q
  INTEGER(KIND=INT64) :: J
  J = TRANSFER(D, J)
  Q = INT(IAND(J, 16383_INT64)) + 1
  J = ISHFT(J, -14)
  P = INT(IAND(J, 16383_INT64)) + 1
END SUBROUTINE DDEC

! #ifdef __GFORTRAN__
! PURE FUNCTION QENC(S, P, Q)
!   USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
!   IMPLICIT NONE
!   REAL(KIND=REAL64), INTENT(IN) :: S
!   INTEGER, INTENT(IN) :: P, Q
!   REAL(KIND=REAL128) :: QENC
!   QENC = TRANSFER(&
!        IOR(TRANSFER(REAL(S,REAL128), 0_16), IOR(ISHFT(INT(IAND(P-1,1073741823),16),30), INT(IAND(Q-1,1073741823),16))), QENC)
! END FUNCTION QENC

! PURE SUBROUTINE QDEC(D, P, Q)
!   USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
!   IMPLICIT NONE
!   REAL(KIND=REAL128), INTENT(IN) :: D
!   INTEGER, INTENT(OUT) :: P, Q
!   INTEGER(KIND=16) :: J
!   J = TRANSFER(D, J)
!   Q = INT(IAND(J, 1073741823_16)) + 1
!   J = ISHFT(J, -30)
!   P = INT(IAND(J, 1073741823_16)) + 1
! END SUBROUTINE QDEC
! #endif
