PURE FUNCTION DENC(S, P, Q)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64
  IMPLICIT NONE
  REAL(KIND=REAL32), INTENT(IN) :: S
  INTEGER, INTENT(IN) :: P, Q
  REAL(KIND=REAL64) :: DENC
  DENC = TRANSFER(&
       IOR(TRANSFER(REAL(S,REAL64), 0_INT64), IOR(ISHFT(INT(IAND(P-1,16383),INT64),14), INT(IAND(Q-1,16383),INT64))), DENC)
END FUNCTION DENC

PURE SUBROUTINE DDEC(D, P, Q)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32, REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), INTENT(IN) :: D
  INTEGER, INTENT(OUT) :: P, Q
  INTEGER(KIND=INT64) :: J
  J = TRANSFER(D, J)
  Q = INT(IAND(J, 16383_INT64)) + 1
  J = ISHFT(J, -14)
  P = INT(IAND(J, 16383_INT64)) + 1
END SUBROUTINE DDEC
