../lib/$(PLAT)/libdynord.a: $(OBJS_DYNORD) $(MKFS) dynord/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_DYNORD)

../obj/$(PLAT)/sabsg.$(OXT): dynord/sabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/sabsg.F90

../obj/$(PLAT)/cabsg.$(OXT): dynord/cabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/cabsg.F90

../obj/$(PLAT)/dabsg.$(OXT): dynord/dabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/dabsg.F90

../obj/$(PLAT)/zabsg.$(OXT): dynord/zabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/zabsg.F90

../obj/$(PLAT)/qabsg.$(OXT): dynord/qabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qabsg.F90

../obj/$(PLAT)/yabsg.$(OXT): dynord/yabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/yabsg.F90

../obj/$(PLAT)/xabsg.$(OXT): dynord/xabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xabsg.F90

../obj/$(PLAT)/wabsg.$(OXT): dynord/wabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wabsg.F90

../obj/$(PLAT)/smkwpq.$(OXT): dynord/smkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/smkwpq.F90

../obj/$(PLAT)/cmkwpq.$(OXT): dynord/cmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/cmkwpq.F90

../obj/$(PLAT)/dmkwpq.$(OXT): dynord/dmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/dmkwpq.F90

../obj/$(PLAT)/zmkwpq.$(OXT): dynord/zmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/zmkwpq.F90

../obj/$(PLAT)/qmkwpq.$(OXT): dynord/qmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qmkwpq.F90

../obj/$(PLAT)/ymkwpq.$(OXT): dynord/ymkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/ymkwpq.F90

../obj/$(PLAT)/xmkwpq.$(OXT): dynord/xmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xmkwpq.F90

../obj/$(PLAT)/wmkwpq.$(OXT): dynord/wmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wmkwpq.F90

../obj/$(PLAT)/smk3pq.$(OXT): dynord/smk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/smk3pq.F90

../obj/$(PLAT)/cmk3pq.$(OXT): dynord/cmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/cmk3pq.F90

../obj/$(PLAT)/dmk3pq.$(OXT): dynord/dmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/dmk3pq.F90

../obj/$(PLAT)/zmk3pq.$(OXT): dynord/zmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/zmk3pq.F90

../obj/$(PLAT)/qmk3pq.$(OXT): dynord/qmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qmk3pq.F90

../obj/$(PLAT)/ymk3pq.$(OXT): dynord/ymk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/ymk3pq.F90

../obj/$(PLAT)/xmk3pq.$(OXT): dynord/xmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xmk3pq.F90

../obj/$(PLAT)/wmk3pq.$(OXT): dynord/wmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/wmk3pq.F90

../obj/$(PLAT)/smkdpq.$(OXT): dynord/smkdpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/smkdpq.F90

../obj/$(PLAT)/cmkdpq.$(OXT): dynord/cmkdpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/cmkdpq.F90

../obj/$(PLAT)/spqcmp.$(OXT): dynord/spqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/spqcmp.f90

../obj/$(PLAT)/dpqcmp.$(OXT): dynord/dpqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/dpqcmp.f90

../obj/$(PLAT)/qpqcmp.$(OXT): dynord/qpqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qpqcmp.f90

../obj/$(PLAT)/xpqcmp.$(OXT): dynord/xpqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xpqcmp.f90

../obj/$(PLAT)/spqmrg.$(OXT): dynord/spqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/spqmrg.f90

../obj/$(PLAT)/dpqmrg.$(OXT): dynord/dpqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/dpqmrg.f90

../obj/$(PLAT)/qpqmrg.$(OXT): dynord/qpqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qpqmrg.f90

../obj/$(PLAT)/xpqmrg.$(OXT): dynord/xpqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xpqmrg.f90

../obj/$(PLAT)/spqsrt.$(OXT): dynord/spqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/spqsrt.F90

../obj/$(PLAT)/dpqsrt.$(OXT): dynord/dpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/dpqsrt.F90

../obj/$(PLAT)/qpqsrt.$(OXT): dynord/qpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/qpqsrt.F90

../obj/$(PLAT)/xpqsrt.$(OXT): dynord/xpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) $(CFLG) ../../../src/dynord/xpqsrt.F90
