../lib/$(PLAT)/libdynord.a: $(OBJS_DYNORD) $(MKFS) dynord/GNUmakefile
	$(AR) $(ARFLAGS) $@ $(OBJS_DYNORD)

../obj/$(PLAT)/sabsg.o: dynord/sabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/sabsg.F90

../obj/$(PLAT)/cabsg.o: dynord/cabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/cabsg.F90

../obj/$(PLAT)/dabsg.o: dynord/dabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/dabsg.F90

../obj/$(PLAT)/zabsg.o: dynord/zabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/zabsg.F90

../obj/$(PLAT)/qabsg.o: dynord/qabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/qabsg.F90

../obj/$(PLAT)/yabsg.o: dynord/yabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/yabsg.F90

../obj/$(PLAT)/xabsg.o: dynord/xabsg.F90 dynord/gabsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/xabsg.F90

../obj/$(PLAT)/wabsg.o: dynord/wabsg.F90 dynord/habsg.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/wabsg.F90

../obj/$(PLAT)/smkwpq.o: dynord/smkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/smkwpq.F90

../obj/$(PLAT)/cmkwpq.o: dynord/cmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/cmkwpq.F90

../obj/$(PLAT)/dmkwpq.o: dynord/dmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/dmkwpq.F90

../obj/$(PLAT)/zmkwpq.o: dynord/zmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/zmkwpq.F90

../obj/$(PLAT)/qmkwpq.o: dynord/qmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/qmkwpq.F90

../obj/$(PLAT)/ymkwpq.o: dynord/ymkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/ymkwpq.F90

../obj/$(PLAT)/xmkwpq.o: dynord/xmkwpq.F90 dynord/gmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/xmkwpq.F90

../obj/$(PLAT)/wmkwpq.o: dynord/wmkwpq.F90 dynord/hmkwpq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/wmkwpq.F90

../obj/$(PLAT)/smk3pq.o: dynord/smk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/smk3pq.F90

../obj/$(PLAT)/cmk3pq.o: dynord/cmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/cmk3pq.F90

../obj/$(PLAT)/dmk3pq.o: dynord/dmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/dmk3pq.F90

../obj/$(PLAT)/zmk3pq.o: dynord/zmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/zmk3pq.F90

../obj/$(PLAT)/qmk3pq.o: dynord/qmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/qmk3pq.F90

../obj/$(PLAT)/ymk3pq.o: dynord/ymk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/ymk3pq.F90

../obj/$(PLAT)/xmk3pq.o: dynord/xmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/xmk3pq.F90

../obj/$(PLAT)/wmk3pq.o: dynord/wmk3pq.F90 dynord/gmk3pq.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/wmk3pq.F90

../obj/$(PLAT)/spqcmp.o: dynord/spqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/spqcmp.f90

../obj/$(PLAT)/dpqcmp.o: dynord/dpqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/dpqcmp.f90

../obj/$(PLAT)/qpqcmp.o: dynord/qpqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/qpqcmp.f90

../obj/$(PLAT)/xpqcmp.o: dynord/xpqcmp.f90 dynord/gpqcmp.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/xpqcmp.f90

../obj/$(PLAT)/spqmrg.o: dynord/spqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/spqmrg.f90

../obj/$(PLAT)/dpqmrg.o: dynord/dpqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/dpqmrg.f90

../obj/$(PLAT)/qpqmrg.o: dynord/qpqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/qpqmrg.f90

../obj/$(PLAT)/xpqmrg.o: dynord/xpqmrg.f90 dynord/gpqmrg.f90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/xpqmrg.f90

../obj/$(PLAT)/spqsrt.o: dynord/spqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/spqsrt.F90

../obj/$(PLAT)/dpqsrt.o: dynord/dpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/dpqsrt.F90

../obj/$(PLAT)/qpqsrt.o: dynord/qpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/qpqsrt.F90

../obj/$(PLAT)/xpqsrt.o: dynord/xpqsrt.F90 dynord/gpqsrt.F90 $(MKFS) dynord/GNUmakefile
	cd ../obj/$(PLAT) && $(FC) $(FCFLAGS) -c ../../../src/dynord/xpqsrt.F90
