..\lib\$(PLAT)\dynord.lib: $(OBJS_DYNORD) $(MKFS) dynord\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_DYNORD)

..\obj\$(PLAT)\sabsg.obj: dynord\sabsg.F90 dynord\gabsg.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\sabsg.F90 /Fo$@

..\obj\$(PLAT)\cabsg.obj: dynord\cabsg.F90 dynord\habsg.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\cabsg.F90 /Fo$@

..\obj\$(PLAT)\dabsg.obj: dynord\dabsg.F90 dynord\gabsg.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dabsg.F90 /Fo$@

..\obj\$(PLAT)\zabsg.obj: dynord\zabsg.F90 dynord\habsg.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\zabsg.F90 /Fo$@

..\obj\$(PLAT)\qabsg.obj: dynord\qabsg.F90 dynord\gabsg.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qabsg.F90 /Fo$@

..\obj\$(PLAT)\yabsg.obj: dynord\yabsg.F90 dynord\habsg.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\yabsg.F90 /Fo$@

..\obj\$(PLAT)\sabsog.obj: dynord\sabsog.F90 dynord\gabsog.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\sabsog.F90 /Fo$@

..\obj\$(PLAT)\cabsog.obj: dynord\cabsog.F90 dynord\habsog.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\cabsog.F90 /Fo$@

..\obj\$(PLAT)\dabsog.obj: dynord\dabsog.F90 dynord\gabsog.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dabsog.F90 /Fo$@

..\obj\$(PLAT)\zabsog.obj: dynord\zabsog.F90 dynord\habsog.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\zabsog.F90 /Fo$@

..\obj\$(PLAT)\qabsog.obj: dynord\qabsog.F90 dynord\gabsog.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qabsog.F90 /Fo$@

..\obj\$(PLAT)\yabsog.obj: dynord\yabsog.F90 dynord\habsog.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\yabsog.F90 /Fo$@

..\obj\$(PLAT)\smkwpq.obj: dynord\smkwpq.F90 dynord\gmkwpq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\smkwpq.F90 /Fo$@

..\obj\$(PLAT)\cmkwpq.obj: dynord\cmkwpq.F90 dynord\hmkwpq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\cmkwpq.F90 /Fo$@

..\obj\$(PLAT)\dmkwpq.obj: dynord\dmkwpq.F90 dynord\gmkwpq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dmkwpq.F90 /Fo$@

..\obj\$(PLAT)\zmkwpq.obj: dynord\zmkwpq.F90 dynord\hmkwpq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\zmkwpq.F90 /Fo$@

..\obj\$(PLAT)\qmkwpq.obj: dynord\qmkwpq.F90 dynord\gmkwpq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qmkwpq.F90 /Fo$@

..\obj\$(PLAT)\ymkwpq.obj: dynord\ymkwpq.F90 dynord\hmkwpq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\ymkwpq.F90 /Fo$@

..\obj\$(PLAT)\smk1pq.obj: dynord\smk1pq.F90 dynord\gmk1pq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\smk1pq.F90 /Fo$@

..\obj\$(PLAT)\cmk1pq.obj: dynord\cmk1pq.F90 dynord\gmk1pq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\cmk1pq.F90 /Fo$@

..\obj\$(PLAT)\dmk1pq.obj: dynord\dmk1pq.F90 dynord\gmk1pq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dmk1pq.F90 /Fo$@

..\obj\$(PLAT)\zmk1pq.obj: dynord\zmk1pq.F90 dynord\gmk1pq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\zmk1pq.F90 /Fo$@

..\obj\$(PLAT)\qmk1pq.obj: dynord\qmk1pq.F90 dynord\gmk1pq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qmk1pq.F90 /Fo$@

..\obj\$(PLAT)\ymk1pq.obj: dynord\ymk1pq.F90 dynord\gmk1pq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\ymk1pq.F90 /Fo$@

..\obj\$(PLAT)\smkopq.obj: dynord\smkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\smkopq.F90 /Fo$@

..\obj\$(PLAT)\cmkopq.obj: dynord\cmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\cmkopq.F90 /Fo$@

..\obj\$(PLAT)\dmkopq.obj: dynord\dmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dmkopq.F90 /Fo$@

..\obj\$(PLAT)\zmkopq.obj: dynord\zmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\zmkopq.F90 /Fo$@

..\obj\$(PLAT)\qmkopq.obj: dynord\qmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qmkopq.F90 /Fo$@

..\obj\$(PLAT)\ymkopq.obj: dynord\ymkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\ymkopq.F90 /Fo$@

..\obj\$(PLAT)\spqcmp.obj: dynord\spqcmp.f90 dynord\gpqcmp.f90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /c dynord\spqcmp.f90 /Fo$@

..\obj\$(PLAT)\dpqcmp.obj: dynord\dpqcmp.f90 dynord\gpqcmp.f90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /c dynord\dpqcmp.f90 /Fo$@

..\obj\$(PLAT)\qpqcmp.obj: dynord\qpqcmp.f90 dynord\gpqcmp.f90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /c dynord\qpqcmp.f90 /Fo$@

..\obj\$(PLAT)\spqmrg.obj: dynord\spqmrg.f90 dynord\gpqmrg.f90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /c dynord\spqmrg.f90 /Fo$@

..\obj\$(PLAT)\dpqmrg.obj: dynord\dpqmrg.f90 dynord\gpqmrg.f90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /c dynord\dpqmrg.f90 /Fo$@

..\obj\$(PLAT)\qpqmrg.obj: dynord\qpqmrg.f90 dynord\gpqmrg.f90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /c dynord\qpqmrg.f90 /Fo$@

..\obj\$(PLAT)\spqsrt.obj: dynord\spqsrt.F90 dynord\gpqsrt.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\spqsrt.F90 /Fo$@

..\obj\$(PLAT)\dpqsrt.obj: dynord\dpqsrt.F90 dynord\gpqsrt.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dpqsrt.F90 /Fo$@

..\obj\$(PLAT)\qpqsrt.obj: dynord\qpqsrt.F90 dynord\gpqsrt.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qpqsrt.F90 /Fo$@

..\obj\$(PLAT)\spqsort.obj: dynord\spqsort.F90 dynord\gpqsort.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\spqsort.F90 /Fo$@

..\obj\$(PLAT)\dpqsort.obj: dynord\dpqsort.F90 dynord\gpqsort.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\dpqsort.F90 /Fo$@

..\obj\$(PLAT)\qpqsort.obj: dynord\qpqsort.F90 dynord\gpqsort.F90 $(MKFS) dynord\Makefile
	$(FC) $(FCFLAGS) /fpp /c dynord\qpqsort.F90 /Fo$@
