..\lib\$(PLAT)\dynord.lib: $(OBJS_DYNORD) $(MKFS) dynord\Makefile
	$(AR) $(ARFLAGS) /OUT:$@ $(OBJS_DYNORD)

..\obj\$(PLAT)\sabsg.obj: dynord\sabsg.F90 dynord\gabsg.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\sabsg.F90 && popd

..\obj\$(PLAT)\cabsg.obj: dynord\cabsg.F90 dynord\habsg.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\cabsg.F90 && popd

..\obj\$(PLAT)\dabsg.obj: dynord\dabsg.F90 dynord\gabsg.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dabsg.F90 && popd

..\obj\$(PLAT)\zabsg.obj: dynord\zabsg.F90 dynord\habsg.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\zabsg.F90 && popd

..\obj\$(PLAT)\qabsg.obj: dynord\qabsg.F90 dynord\gabsg.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qabsg.F90 && popd

..\obj\$(PLAT)\yabsg.obj: dynord\yabsg.F90 dynord\habsg.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\yabsg.F90 && popd

..\obj\$(PLAT)\sabsog.obj: dynord\sabsog.F90 dynord\gabsog.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\sabsog.F90 && popd

..\obj\$(PLAT)\cabsog.obj: dynord\cabsog.F90 dynord\habsog.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\cabsog.F90 && popd

..\obj\$(PLAT)\dabsog.obj: dynord\dabsog.F90 dynord\gabsog.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dabsog.F90 && popd

..\obj\$(PLAT)\zabsog.obj: dynord\zabsog.F90 dynord\habsog.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\zabsog.F90 && popd

..\obj\$(PLAT)\qabsog.obj: dynord\qabsog.F90 dynord\gabsog.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qabsog.F90 && popd

..\obj\$(PLAT)\yabsog.obj: dynord\yabsog.F90 dynord\habsog.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\yabsog.F90 && popd

..\obj\$(PLAT)\smkwpq.obj: dynord\smkwpq.F90 dynord\gmkwpq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\smkwpq.F90 && popd

..\obj\$(PLAT)\cmkwpq.obj: dynord\cmkwpq.F90 dynord\hmkwpq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\cmkwpq.F90 && popd

..\obj\$(PLAT)\dmkwpq.obj: dynord\dmkwpq.F90 dynord\gmkwpq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dmkwpq.F90 && popd

..\obj\$(PLAT)\zmkwpq.obj: dynord\zmkwpq.F90 dynord\hmkwpq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\zmkwpq.F90 && popd

..\obj\$(PLAT)\qmkwpq.obj: dynord\qmkwpq.F90 dynord\gmkwpq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qmkwpq.F90 && popd

..\obj\$(PLAT)\ymkwpq.obj: dynord\ymkwpq.F90 dynord\hmkwpq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\ymkwpq.F90 && popd

..\obj\$(PLAT)\smk3pq.obj: dynord\smk3pq.F90 dynord\gmk3pq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\smk3pq.F90 && popd

..\obj\$(PLAT)\cmk3pq.obj: dynord\cmk3pq.F90 dynord\gmk3pq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\cmk3pq.F90 && popd

..\obj\$(PLAT)\dmk3pq.obj: dynord\dmk3pq.F90 dynord\gmk3pq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dmk3pq.F90 && popd

..\obj\$(PLAT)\zmk3pq.obj: dynord\zmk3pq.F90 dynord\gmk3pq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\zmk3pq.F90 && popd

..\obj\$(PLAT)\qmk3pq.obj: dynord\qmk3pq.F90 dynord\gmk3pq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qmk3pq.F90 && popd

..\obj\$(PLAT)\ymk3pq.obj: dynord\ymk3pq.F90 dynord\gmk3pq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\ymk3pq.F90 && popd

..\obj\$(PLAT)\smkopq.obj: dynord\smkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\smkopq.F90 && popd

..\obj\$(PLAT)\cmkopq.obj: dynord\cmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\cmkopq.F90 && popd

..\obj\$(PLAT)\dmkopq.obj: dynord\dmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dmkopq.F90 && popd

..\obj\$(PLAT)\zmkopq.obj: dynord\zmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\zmkopq.F90 && popd

..\obj\$(PLAT)\qmkopq.obj: dynord\qmkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qmkopq.F90 && popd

..\obj\$(PLAT)\ymkopq.obj: dynord\ymkopq.F90 dynord\gmkopq.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\ymkopq.F90 && popd

..\obj\$(PLAT)\spqcmp.obj: dynord\spqcmp.f90 dynord\gpqcmp.f90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\dynord\spqcmp.f90 && popd

..\obj\$(PLAT)\dpqcmp.obj: dynord\dpqcmp.f90 dynord\gpqcmp.f90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\dynord\dpqcmp.f90 && popd

..\obj\$(PLAT)\qpqcmp.obj: dynord\qpqcmp.f90 dynord\gpqcmp.f90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\dynord\qpqcmp.f90 && popd

..\obj\$(PLAT)\spqmrg.obj: dynord\spqmrg.f90 dynord\gpqmrg.f90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\dynord\spqmrg.f90 && popd

..\obj\$(PLAT)\dpqmrg.obj: dynord\dpqmrg.f90 dynord\gpqmrg.f90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\dynord\dpqmrg.f90 && popd

..\obj\$(PLAT)\qpqmrg.obj: dynord\qpqmrg.f90 dynord\gpqmrg.f90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /c ..\..\..\src\dynord\qpqmrg.f90 && popd

..\obj\$(PLAT)\spqsrt.obj: dynord\spqsrt.F90 dynord\gpqsrt.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\spqsrt.F90 && popd

..\obj\$(PLAT)\dpqsrt.obj: dynord\dpqsrt.F90 dynord\gpqsrt.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dpqsrt.F90 && popd

..\obj\$(PLAT)\qpqsrt.obj: dynord\qpqsrt.F90 dynord\gpqsrt.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qpqsrt.F90 && popd

..\obj\$(PLAT)\spqsort.obj: dynord\spqsort.F90 dynord\gpqsort.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\spqsort.F90 && popd

..\obj\$(PLAT)\dpqsort.obj: dynord\dpqsort.F90 dynord\gpqsort.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\dpqsort.F90 && popd

..\obj\$(PLAT)\qpqsort.obj: dynord\qpqsort.F90 dynord\gpqsort.F90 $(MKFS) dynord\Makefile
	pushd ..\obj\$(PLAT) && $(FC) $(FCFLAGS) /fpp /c ..\..\..\src\dynord\qpqsort.F90 && popd
