!>@brief \b QABSOG computes \f$W=|G|\f$ in parallel.
SUBROUTINE QABSOG(M, N, G, LDG, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  REAL(KIND=REAL128), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL128), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL128) :: H
  INTEGER :: I, J
#include "gabsog.F90"
END SUBROUTINE QABSOG
