!>@brief \b SABSOG computes \f$W=|G|\f$ in parallel.
SUBROUTINE SABSOG(M, N, G, LDG, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL32), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL32) :: H
  INTEGER :: I, J
#include "gabsog.F90"
END SUBROUTINE SABSOG
