!>@brief \b SB2ENC computes D from W.
SUBROUTINE SB2ENC(N, W, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE SUBROUTINE DENC(E, S, P, Q) BIND(C,NAME='pvn_djs_denc_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       REAL(KIND=REAL64), INTENT(OUT) :: E
       REAL(KIND=REAL32), INTENT(IN) :: S
       INTEGER, INTENT(IN) :: P, Q
     END SUBROUTINE DENC
  END INTERFACE

  INTEGER, INTENT(IN) :: N, O(2,*)
  REAL(KIND=REAL32), INTENT(IN) :: W(N,N)
  REAL(KIND=REAL64), INTENT(OUT) :: D(*)
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=REAL32) :: H
  INTEGER :: K, L, M, P, Q
#define XENC DENC
#include "gb2enc.F90"
END SUBROUTINE SB2ENC
