!>@brief \b SMKBPQ computes O from G w.r.t. B.
SUBROUTINE SMKBPQ(N, G, LDG, B, W, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
#ifndef __GFORTRAN__
  INTERFACE
     SUBROUTINE SNRM2B(N, G, LDG, B, W, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG, B
       REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: W(N/B,N/B)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SNRM2B
  END INTERFACE
  INTERFACE
     SUBROUTINE SB2ENC(N, W, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, O(2,*)
       REAL(KIND=REAL32), INTENT(IN) :: W(N,N)
       REAL(KIND=REAL64), INTENT(OUT) :: D(*)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SB2ENC
  END INTERFACE
  INTERFACE
     SUBROUTINE SMKDPQ(N, M, D, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, M
       REAL(KIND=REAL64), INTENT(INOUT) :: D(M+1)
       INTEGER, INTENT(OUT) :: O(2,N/2)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SMKDPQ
  END INTERFACE
#endif
  INTEGER, INTENT(IN) :: N, LDG, B
  REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL32), INTENT(OUT) :: W(N/B,N/B)
  REAL(KIND=REAL64), INTENT(OUT) :: D(*)
  INTEGER, INTENT(INOUT) :: O(2,*), INFO
#ifdef __GFORTRAN__
  EXTERNAL :: SNRM2B, SB2ENC, SMKDPQ
#endif
  INTEGER :: K, L, M
#define NRM2B SNRM2B
#define B2ENC SB2ENC
#define MKDPQ SMKDPQ
#include "gmkbpq.F90"
END SUBROUTINE SMKBPQ
