!>@brief \b SMKDPQ builds at most N/2 pivot index pairs for the next transformation of G.
SUBROUTINE SMKDPQ(N, M, D, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
#ifndef __GFORTRAN__
  INTERFACE
     PURE SUBROUTINE DDEC(E, P, Q) BIND(C,NAME='pvn_djs_ddec_')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       REAL(KIND=REAL64), INTENT(IN) :: E
       INTEGER, INTENT(OUT) :: P, Q
     END SUBROUTINE DDEC
  END INTERFACE
#endif
  REAL(KIND=REAL64), PARAMETER :: WZERO = 0.0_REAL64
  INTEGER, INTENT(IN) :: N, M
  REAL(KIND=REAL64), INTENT(INOUT) :: D(M+1)
  INTEGER, INTENT(OUT) :: O(2,N/2)
  INTEGER, INTENT(INOUT) :: INFO

  REAL(KIND=REAL64) :: W
  INTEGER :: I, J, K, L, P, Q, R
#ifdef __GFORTRAN__
  EXTERNAL :: PVN_DJS_DDEC
#define XDEC PVN_DJS_DDEC
#else
#define XDEC DDEC
#endif
#include "gmkdpq.F90"
END SUBROUTINE SMKDPQ
