!>@brief \b WABSG sequentially computes \f$W=|G|\f$.
PURE SUBROUTINE WABSG(M, N, G, LDG, W, LDW, INFO)
  IMPLICIT NONE

#define CR_HYPOT HYPOT

  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  COMPLEX(KIND=10), INTENT(IN) :: G(LDG,N)
  REAL(KIND=10), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=10) :: H
  INTEGER :: I, J
#include "habsg.F90"
END SUBROUTINE WABSG
