!>@brief \b XABSG computes W=|G|.
SUBROUTINE XABSG(M, N, G, LDG, W, LDW, INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  REAL(KIND=10), INTENT(IN) :: G(LDG,N)
  REAL(KIND=10), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=10) :: H
  INTEGER :: I, J
#include "gabsg.F90"
END SUBROUTINE XABSG
