!>@brief \b XABSOG computes \f$W=|G|\f$ in parallel.
SUBROUTINE XABSOG(M, N, G, LDG, W, LDW, INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  REAL(KIND=10), INTENT(IN) :: G(LDG,N)
  REAL(KIND=10), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=10) :: H
  INTEGER :: I, J
#include "gabsog.F90"
END SUBROUTINE XABSOG
