  PURE FUNCTION XENCAP(H, P, Q)
    USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT8 ! TODO: UNIT8
    IMPLICIT NONE
    REAL(KIND=c_long_double), INTENT(IN) :: H
    INTEGER, INTENT(IN) :: P, Q
    REAL(KIND=c_long_double) :: XENCAP, W
    ! TODO: UNSIGNED(KIND=UINT8) :: B(16)
    INTEGER(KIND=INT8) :: B(16)
    EQUIVALENCE(W, B)
    W = H
    ! TODO: B(1) = UINT((Q - 1), UINT8)
    B(1) = INT((Q - 1), INT8)
    ! TODO: B(2) = UINT((P - 1), UINT8)
    B(2) = INT((P - 1), INT8)
    XENCAP = W
  END FUNCTION XENCAP
