!>@brief \b XMK3PQ builds at most \f$K\f$ pivot index pairs for the next transformation of \f$G\f$.
PURE SUBROUTINE XMK3PQ(K, N, G, LDG, W, O, INFO)
  IMPLICIT NONE

#define CR_HYPOT HYPOT
  INTERFACE
     PURE SUBROUTINE XABSG(M, N, G, LDG, W, LDW, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDW
       REAL(KIND=10), INTENT(IN) :: G(LDG,N)
       REAL(KIND=10), INTENT(OUT) :: W(LDW,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XABSG
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XMKWPQ(N, G, LDG, W, O, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       REAL(KIND=10), INTENT(IN) :: G(LDG,N)
       REAL(KIND=10), INTENT(INOUT) :: W(N,N)
       INTEGER, INTENT(OUT) :: O(N*(N-1)), INFO
     END SUBROUTINE XMKWPQ
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XPQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
       REAL(KIND=10), INTENT(IN) :: XW, YW
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XPQCMP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XPQSRT(WPQCMP, N, AW, AP, AQ, BW, BP, BQ, INFO)
       IMPLICIT NONE
       ABSTRACT INTERFACE
          PURE SUBROUTINE PQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
            IMPLICIT NONE
            INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
            REAL(KIND=10), INTENT(IN) :: XW, YW
            INTEGER, INTENT(OUT) :: INFO
          END SUBROUTINE PQCMP
       END INTERFACE
       INTEGER, INTENT(IN) :: N
       REAL(KIND=10), INTENT(INOUT) :: AW(N)
       INTEGER, INTENT(INOUT) :: AP(N), AQ(N)
       REAL(KIND=10), INTENT(OUT) :: BW(N)
       INTEGER, INTENT(OUT) :: BP(N), BQ(N), INFO
       PROCEDURE(PQCMP) :: WPQCMP
     END SUBROUTINE XPQSRT
  END INTERFACE

  REAL(KIND=10), PARAMETER :: ZERO = 0.0_10, MONE = -1.0_10
  INTEGER, INTENT(IN) :: K, N, LDG
  REAL(KIND=10), INTENT(IN) :: G(LDG,N)
  REAL(KIND=10), INTENT(OUT) :: W(N*N)
  INTEGER, INTENT(OUT) :: O(2*N*(N-1)), INFO
  INTEGER :: I, J, L, M, M_2
#define ABSG XABSG
#define MKWPQ XMKWPQ
#define PQCMP XPQCMP
#define PQSRT XPQSRT
#include "gmk3pq.F90"
END SUBROUTINE XMK3PQ
