!>@brief \b YABSG sequentially computes \f$W=|G|\f$.
PURE SUBROUTINE YABSG(M, N, G, LDG, W, LDW, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE

#define CR_HYPOT HYPOT

  INTEGER, INTENT(IN) :: M, N, LDG, LDW
  COMPLEX(KIND=REAL128), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL128), INTENT(OUT) :: W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=REAL128) :: H
  INTEGER :: I, J
#include "habsg.F90"
END SUBROUTINE YABSG
