!>@brief \b YMK1PQ builds at most one \f$(p,q)\f$ pivot index pair for the next transformation of \f$G\f$.
SUBROUTINE YMK1PQ(K, N, G, LDG, W, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128
  INTEGER, INTENT(IN) :: K, N, LDG
  COMPLEX(KIND=REAL128), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL128), INTENT(OUT) :: W(N*N)
  INTEGER, INTENT(OUT) :: O(2*N*(N-1)), INFO
  INTEGER :: M, M_2
  EXTERNAL :: YABSG, QMKWPQ, QPQCMP, QPQSRT
#define ABSG YABSG
#define MKWPQ QMKWPQ
#define PQCMP QPQCMP
#define PQSRT QPQSRT
#include "gmk1pq.F90"
END SUBROUTINE YMK1PQ
