!>@brief \b YMKOPQ builds at most \f$K\f$ pivot index pairs for the next transformation of \f$G\f$.
SUBROUTINE YMKOPQ(K, N, G, LDG, W, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE

#define CR_HYPOT HYPOT
  INTERFACE
     SUBROUTINE YABSOG(M, N, G, LDG, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDW
       COMPLEX(KIND=REAL128), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL128), INTENT(OUT) :: W(LDW,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE YABSOG
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE YMKWPQ(N, G, LDG, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL128), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL128), INTENT(INOUT) :: W(N,N)
       INTEGER, INTENT(OUT) :: O(N*(N-1)), INFO
     END SUBROUTINE YMKWPQ
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE QPQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
       REAL(KIND=REAL128), INTENT(IN) :: XW, YW
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE QPQCMP
  END INTERFACE
  INTERFACE
     SUBROUTINE QPQSORT(WPQCMP, N, AW, AP, AQ, BW, BP, BQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       IMPLICIT NONE
       ABSTRACT INTERFACE
          PURE SUBROUTINE PQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
            USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
            IMPLICIT NONE
            INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
            REAL(KIND=REAL128), INTENT(IN) :: XW, YW
            INTEGER, INTENT(OUT) :: INFO
          END SUBROUTINE PQCMP
       END INTERFACE
       INTEGER, INTENT(IN) :: N
       REAL(KIND=REAL128), INTENT(INOUT) :: AW(N)
       INTEGER, INTENT(INOUT) :: AP(N), AQ(N)
       REAL(KIND=REAL128), INTENT(OUT) :: BW(N)
       INTEGER, INTENT(OUT) :: BP(N), BQ(N), INFO
       PROCEDURE(PQCMP) :: WPQCMP
     END SUBROUTINE QPQSORT
  END INTERFACE

  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128, MONE = -1.0_REAL128
  INTEGER, INTENT(IN) :: K, N, LDG
  COMPLEX(KIND=REAL128), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL128), INTENT(OUT) :: W(N*N)
  INTEGER, INTENT(OUT) :: O(2*N*(N-1)), INFO
  INTEGER :: I, J, L, M, M_2
#define ABSOG YABSOG
#define MKWPQ YMKWPQ
#define PQCMP QPQCMP
#define PQSORT QPQSORT
#include "gmkopq.F90"
END SUBROUTINE YMKOPQ
