!>@brief \b YMKWPQ builds the weights W and the corresponding indexes O from the NxN quadruple precision matrix W.
PURE SUBROUTINE YMKWPQ(N, G, LDG, W, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE

#define CR_HYPOT HYPOT

  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128, ONE = 1.0_REAL128
  INTEGER, INTENT(IN) :: N, LDG
  COMPLEX(KIND=REAL128), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL128), INTENT(INOUT) :: W(N,N)
  INTEGER, INTENT(OUT) :: O(N*(N-1)), INFO
  REAL(KIND=REAL128) :: H
  INTEGER :: I, J, K, L, M, N2
#include "hmkwpq.F90"
END SUBROUTINE YMKWPQ
