!>@brief \b ZMK1PQ builds at most \f$K\f$ pivot index pairs for the next transformation of \f$G\f$.
PURE SUBROUTINE ZMK1PQ(K, N, G, LDG, W, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE

#ifdef CR_MATH
  INTERFACE
     ! TODO: cr_hypot might change errno but a copy can be made that does not
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE SUBROUTINE ZABSG(G, LDG, W, LDW, P, Q, B, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: LDG, LDW, P, Q, B
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,*)
       REAL(KIND=REAL64), INTENT(OUT) :: W(LDW,*)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ZABSG
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE ZMKWPQ(N, G, LDG, W, O, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(INOUT) :: W(N,N)
       INTEGER, INTENT(OUT) :: O(N*(N-1)), INFO
     END SUBROUTINE ZMKWPQ
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DPQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
       REAL(KIND=REAL64), INTENT(IN) :: XW, YW
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DPQCMP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DPQSRT(WPQCMP, N, AW, AP, AQ, BW, BP, BQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       ABSTRACT INTERFACE
          PURE SUBROUTINE PQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
            USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
            IMPLICIT NONE
            INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
            REAL(KIND=REAL64), INTENT(IN) :: XW, YW
            INTEGER, INTENT(OUT) :: INFO
          END SUBROUTINE PQCMP
       END INTERFACE
       INTEGER, INTENT(IN) :: N
       REAL(KIND=REAL64), INTENT(INOUT) :: AW(N)
       INTEGER, INTENT(INOUT) :: AP(N), AQ(N)
       REAL(KIND=REAL64), INTENT(OUT) :: BW(N)
       INTEGER, INTENT(OUT) :: BP(N), BQ(N), INFO
       PROCEDURE(PQCMP) :: WPQCMP
     END SUBROUTINE DPQSRT
  END INTERFACE

  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, MONE = -1.0_REAL64
  INTEGER, INTENT(IN) :: K, N, LDG
  COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL64), INTENT(OUT) :: W(N*N)
  INTEGER, INTENT(OUT) :: O(2*N*(N-1)), INFO
  INTEGER :: I, J, L, M, M_2
#define ABSG ZABSG
#define MKWPQ ZMKWPQ
#define PQCMP DPQCMP
#define PQSRT DPQSRT
#include "gmk1pq.F90"
END SUBROUTINE ZMK1PQ
