!>@brief \b ZMK3PQ builds at most K pivot index pairs for the next transformation of G.
SUBROUTINE ZMK3PQ(K, N, G, LDG, W, O, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
#ifdef NDEBUG
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
#else
     FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
#endif
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     SUBROUTINE ZABSG(M, N, G, LDG, W, LDW, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDW
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(OUT) :: W(LDW,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE ZABSG
  END INTERFACE
  INTERFACE
#ifdef NDEBUG
     PURE SUBROUTINE ZMKWPQ(N, G, LDG, W, O, INFO)
#else
     SUBROUTINE ZMKWPQ(N, G, LDG, W, O, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDG
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64), INTENT(INOUT) :: W(N,N)
       INTEGER, INTENT(OUT) :: O(N*(N-1)), INFO
     END SUBROUTINE ZMKWPQ
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DPQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
       REAL(KIND=REAL64), INTENT(IN) :: XW, YW
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DPQCMP
  END INTERFACE
  INTERFACE
     SUBROUTINE DPQSRT(WPQCMP, N, AW, AP, AQ, BW, BP, BQ, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       ABSTRACT INTERFACE
          PURE SUBROUTINE PQCMP(XW, XP, XQ, YW, YP, YQ, INFO)
            USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
            IMPLICIT NONE
            INTEGER, INTENT(IN) :: XP, XQ, YP, YQ
            REAL(KIND=REAL64), INTENT(IN) :: XW, YW
            INTEGER, INTENT(OUT) :: INFO
          END SUBROUTINE PQCMP
       END INTERFACE
       INTEGER, INTENT(IN) :: N
       REAL(KIND=REAL64), INTENT(INOUT) :: AW(N)
       INTEGER, INTENT(INOUT) :: AP(N), AQ(N), INFO
       REAL(KIND=REAL64), INTENT(OUT) :: BW(N)
       INTEGER, INTENT(OUT) :: BP(N), BQ(N)
       PROCEDURE(PQCMP) :: WPQCMP
     END SUBROUTINE DPQSRT
  END INTERFACE

  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, MONE = -1.0_REAL64
  INTEGER, INTENT(IN) :: K, N, LDG
  COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL64), INTENT(OUT) :: W(N*N)
  INTEGER, INTENT(OUT) :: O(2*N*(N-1))
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J, L, M, M_2
#define ABSG ZABSG
#define MKWPQ ZMKWPQ
#define PQCMP DPQCMP
#define PQSRT DPQSRT
#include "gmk3pq.F90"
END SUBROUTINE ZMK3PQ
