!>@brief \b ZNRM2B computes ||off(X)||_F or ||X||_F for all BxB blocks X of G.
SUBROUTINE ZNRM2B(N, G, LDG, B, W, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
#ifdef CR_MATH
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
#else
#define CR_HYPOT HYPOT
#endif
  INTERFACE
     PURE FUNCTION ZNRM2O(M, N, G, LDG, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, INFO
       COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL64) :: ZNRM2O
     END FUNCTION ZNRM2O
  END INTERFACE

  INTEGER, INTENT(IN) :: N, LDG, B
  COMPLEX(KIND=REAL64), INTENT(IN) :: G(LDG,N)
  REAL(KIND=REAL64), INTENT(OUT) :: W(N/B,N/B)
  INTEGER, INTENT(INOUT) :: INFO

  INTEGER :: I, J, K, L, M, P, Q
#define NRM2O ZNRM2O
#include "gnrm2b.F90"
END SUBROUTINE ZNRM2B
